### ISSUE TITLE
No module named 'kaolin.cuda.sided_distance

### ISSUE THREAD

**Issue by mpicci** [NVIDIAGameWorks/kaolin#1]
Hello,
I'm using torch_cluster, 
it cannot find cuda.sided_distatce

ModuleNotFoundError: No module named 'kaolin.cuda.sided_distance

**Comment by krrish94** [comment]
Were you running this from inside of the `kaolin` directory (i.e., the root directory of the repo)? Do you still get this error if you setp out of this directory and re-run?
