### ISSUE TITLE
ShapeNet.Points error at ShapeNetCore.v2

### ISSUE THREAD

**Issue by dkasuga** [NVIDIAGameWorks/kaolin#101]
I tried to apply [examples/ImageRecon/Image_Mesh_Recon_Direct/train.py](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/ImageRecon/Image_Mesh_Recon_Direct/train.py) to ShapeNetCore.v2 Dataset, but I encountered this error:

> File "train_Core.py", line 104, in <module>
>     train = True, split = .7, num_points=3000 )
>   File "~/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/datasets/shapenet.py", line 563, in __init__
>   File "~/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/datasets/shapenet.py", line 443, in __init__
>   File "~/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/datasets/shapenet.py", line 368, in __init__
>   File "~/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/transforms/transforms.py", line 98, in __call__
>   File "~/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/transforms/transforms.py", line 54, in __call__
>   File "~/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/transforms/transforms.py", line 694, in __call__
>   File "~/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/conversions/meshconversions.py", line 141, in trianglemesh_to_voxelgrid
> IndexError: index 101 is out of bounds for dimension 0 with size 100

Does anybody have the same problem?

In the first place, the original code has some bugs and can solve it easily(https://github.com/NVIDIAGameWorks/kaolin/issues/25).

**Comment by GeronimoRoeder1** [comment]
same problem here, also with ShapeNetCore.v2, is there a solution yet? @dkasuga

**Comment by PeterTor** [comment]
Hi maybe your error is related to this fix?  
In my case I was able to load ShapeNet v2 with the following fix
https://github.com/NVIDIAGameWorks/kaolin/pull/159

**Comment by realptkkit** [comment]
Have you found a way to fix this @dkasuga @GeronimoRoeder1 ? 
I already tried something like [#292](https://github.com/NVIDIAGameWorks/kaolin/pull/292), but it just gave me a SIGKILL error which I couldn't figure out yet.

**Comment by kosuke55** [comment]
@realptkkit 
Can you share the error when using #292 ? 
What will happen to the result of running a simple script on a mesh that causes an error? 
```
# mesh is your mesh that causes an error
voxels = kal.conversions.trianglemesh_to_voxelgrid(mesh, 32, normalize=False, vertex_offset=0.5, voxel_range=1.08)
```

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

Closing the bug as it is no longer relevant to this repo.
