### ISSUE TITLE
Pointcloud visualization does not work.

### ISSUE THREAD

**Issue by s0217391** [NVIDIAGameWorks/kaolin#104]
kaolin.visualize.show_pointcloud(pc) hangs due to the following issue with pptk:

https://github.com/heremaps/pptk/issues/24: [https://github.com/heremaps/pptk/issues/24](url)

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

We are not relying on pptk anymore for visualization, please check our custom visualizer the [Omniverse Kaolin App](https://kaolin.readthedocs.io/en/latest/notes/checkpoints.html#visualizing-with-kaolin-omniverse-app) and [Dash3D](https://kaolin.readthedocs.io/en/latest/notes/checkpoints.html#visualizing-with-kaolin-dash3d)!

Closing the bug as it is no longer relevant to this repo.
