### ISSUE TITLE
How to set the background images for rendering?

### ISSUE THREAD

**Issue by Arthur151** [NVIDIAGameWorks/kaolin#109]
Thanks for your effort!
I am confused about how to set the background images for rendering? I want to render the textured 3D mesh to spacific images using DIB renderer.
Looking forward to replys!

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

What I would suggest is to use a background image, is to generate a hard mask and then do a weighted sum of the rendered image and your background image.

Closing the bug as it is no longer relevant to this repo.
