### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by Dene33** [NVIDIAGameWorks/kaolin#11]
https://gameworksdocs.nvidia.com/kaolin doesn't work. 404

**Comment by krrish94** [comment]
We are currently working on the logistics for hosting a documentation page. Until then, you can access the docs by following the build instructions from the [README](https://github.com/NVIDIAGameWorks/kaolin#building-the-documentation)

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and this issue is no longer current. Please refer to our latest documentation:
https://kaolin.readthedocs.io/en/latest/
