### ISSUE TITLE
inconsistency between of library and example

### ISSUE THREAD

**Issue by tau-yihouxiang** [NVIDIAGameWorks/kaolin#110]
Run `examples/ImageRecon/Dib` will get the error `No module named 'graphics' `, I noticed that it was because of the inconsistency between the library and some examples. Please update these examples immediately.

**Comment by KernelA** [comment]
I have the same problem.

**Comment by KernelA** [comment]
After some fixes it is absolutely not working example.
What i got:
`Traceback (most recent call last):
  File "./train.py", line 251, in <module>
    trainer.train()
  File "./train.py", line 136, in train
    image_pred, alpha_pred, face_norms = renderer.forward(points=[(pred_verts*.57), mesh.faces], colors=[colours])
  File "/.../.conda/envs/kaolin/lib/python3.6/site-packages/kaolin/graphics/dib_renderer/renderer/base.py", line 62, in forward
    return self.renderer(points, self.camera_params, *args, **kwargs)
  File "/.../.conda/envs/kaolin/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'colors'`

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates.

Closing the bug as it is no longer relevant to this repo.
