### ISSUE TITLE
Example of using camera_mode='projection' in NMR

### ISSUE THREAD

**Issue by HassanAbbas92** [NVIDIAGameWorks/kaolin#111]
I'm trying to render teapot object using camera_mode='projection' using these parameters
`k=np.array([[80., 0, 512], [0, 80., 512], [0, 0, 1]])
R=np.array([[1., 0, 0], [0, 1., 0], [0, 0, 1.]])
t=np.array([[0., 0, 0]])
dist_coeffs= np.array([[0., 0., 0., 0., 0.]])
` 
but get wrong results
![_tmp_0000](https://user-images.githubusercontent.com/32170019/71479627-d7442d00-27fd-11ea-9ce2-2251c1ea0f9b.png)

Am I doing something wrong?

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

Closing the bug as it is no longer relevant to this repo.
