### ISSUE TITLE
How to load pointcloud from .pcd files directly?

### ISSUE THREAD

**Issue by meng-zha** [NVIDIAGameWorks/kaolin#114]
Thanks for your wonderful effort!
I am confused about how to read pointcloud from pcd files. Only the method of loading up a triangle mesh is available.
Or maybe should I load it by pcl or open3d and convert it into kal.rep.PointCloud?

**Comment by NicoBux** [comment]
Did this ever get resolved?

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
https://kaolin.readthedocs.io/en/latest/

We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates.

Closing the bug as it is no longer relevant to this repo.
