### ISSUE TITLE
Headless Rendering

### ISSUE THREAD

**Issue by nicolasugrinovic** [NVIDIAGameWorks/kaolin#116]
Hi than you for releasing this great library. In your paper you state that the library does **headless rendering**: 

> For headless applications
such as when running on a server that has no attached display, we provide compact utilities to render images and animations to disk, for visualization at a later point.

Where can I find the code for this? Is there explicit code or you do this headless rendering with the neural renders available?

Thank you

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

For visualization you can now use Dash3D and the Omniverse Kaolin App for headless rendering! Please check our [documentation](https://kaolin.readthedocs.io/en/latest/notes/checkpoints.html)!

Closing the bug as it is no longer relevant to this repo.
