### ISSUE TITLE
ModuleNotFoundError: No module named 'heroes'

### ISSUE THREAD

**Issue by Ljove87** [NVIDIAGameWorks/kaolin#117]
I have an error like this when i run my insert_heroes utility file that need to gather data from DOTA2 API(only hero name and hero attribute) and to transfer all via graphql mutation to my postgres database.
After i run a program i get this error:
```
C:\Users\Veljko\Desktop\Desktop\Dev\dota2-api\utility>python insert_heroes.py
Traceback (most recent call last):
  File "insert_heroes.py", line 4, in <module>
    from heroes.models import Hero
ModuleNotFoundError: No module named 'heroes'

So i tried to import my model from folder heroes, model called Hero. 
I think  I didnt set importing correctly.. I really don`t know were is mistake.

dota2-api/utility/insert_heroes.py

```
import requests
import json

from heroes.models import Hero

import self as self

if __name__ == '__main__':
    r = requests.get("https://api.opendota.com/api/heroes")
    all_heroes_info = json.loads(r.content.decode('UTF-8'))

    for hero_info in all_heroes_info:
        name = hero_info['localized_name']
        hero_type = hero_info['primary_attr']

        mutation_create_hero = '''
                  mutation ($name: String!, $heroType: String!) {
                      createHero(name: $name, heroType: $heroType) {
                          name
                      }
                  }
              '''
        hero = Hero.objects.create(
            name=name,
            hero_type=hero_type,
        )

        hero.save()

        r = self.client_.execute(mutation_create_
```

**Comment by Jean-Francois-Lafleche** [comment]
This issue does not seem to have anything to do with kaolin. Closing.
