### ISSUE TITLE
Incorrect occupancy labelings

### ISSUE THREAD

**Issue by mvandermerwe** [NVIDIAGameWorks/kaolin#119]
While playing around with the SDF functionality of Kaolin, I found an error with regards to the occupancy calculations. 

I pulled out just the occupancy portion of the SDF calculation to attempt to identify the issue. When running occupancy tests on a grid of samples around a simple sphere mesh, I get the following result:

![Figure_1](https://user-images.githubusercontent.com/6373238/72106914-83514200-32ed-11ea-9be8-a65ac73478fc.png)

Here the black sphere is the object and the uniform grid is the sampled points. Points in purple are labeled as unoccupied, points in yellow are considered occupied. Notice that a collection of points to the left of the object here are labeled as occupied.

Code to recreate are at this [gist](https://gist.github.com/mvandermerwe/2fbbd40eb6ac310c351717bb27e6f1b4).

**Comment by krrish94** [comment]
Fixed in https://github.com/NVIDIAGameWorks/kaolin/pull/137
