### ISSUE TITLE
nvcc error in Windows

### ISSUE THREAD

**Issue by ronakkaoshik42** [NVIDIAGameWorks/kaolin#12]
![Screenshot (3)](https://user-images.githubusercontent.com/49129684/68989490-ab806f80-086d-11ea-8862-bf2d00701912.png)

**Comment by ronakkaoshik42** [comment]
Setup includes :
1) Cuda 10.1 and cudnn7.5
2) Pytorch 1.3.1

**Comment by arozantsev** [comment]
Hello @ronakkaoshik42, 

This is likely an NVCC bug, which was supposed to be fixed in the latest version. Can you try loading the latest cuda compiler from https://developer.nvidia.com/cuda-10.1-download-archive-update2 

This one worked fine for me with PyTorch 1.3.1.

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and this issue is no longer current. Please refer to our latest documentation:
https://kaolin.readthedocs.io/en/latest/
