### ISSUE TITLE
How to get Shapenet Images Dataset

### ISSUE THREAD

**Issue by denkorzh** [NVIDIAGameWorks/kaolin#120]
Where can I get Shapenet Images Dataset? The standard ShapeNetCore.v1 does not contain `rendering` subdirectories

**Comment by Caenorst** [comment]
Hi @denkorzh ! You can fine the dataset here: ftp://cs.stanford.edu/cs/cvgl/ShapeNetRendering.tgz

**Comment by denkorzh** [comment]
Thanks, @Caenorst ! Finally, I obtained the dataset at http://ftp.cs.stanford.edu/cs/cvgl/ShapeNetRendering.tgz

**Comment by dahyedahye** [comment]
Hi, I was looking for the exact source of the dataset and I found that you can also download the same one at http://cvgl.stanford.edu/data2/ShapeNetRendering.tgz and it is provided by https://github.com/chrischoy/3D-R2N2. Thanks!
