### ISSUE TITLE
Segmentation fault when running tests/models/test_PointNet2.py

### ISSUE THREAD

**Issue by Zhangsihao-Yang** [NVIDIAGameWorks/kaolin#123]
It looks like the following figure.
![image](https://user-images.githubusercontent.com/29811853/72307414-0d234700-362f-11ea-9ef8-c0ccc2dc6d3c.png)

**Comment by anaru** [comment]
I am seeing the same pattern of failures. Here are my details:

**OS**: Ubuntu 16.04
**Python version**: 3.6.10
**PyTorch version**: 1.4.0
**CUDA version**: 10.2

**Revision**: dcacac5baa78640186084f25cd8574347f9363a8

I have been closely following the setup instructions in the README

**Comment by anaru** [comment]
In my case, I think this might have been due to a CUDA version mismatch. I wrote CUDA 10.2 in the previous message, but I was mistaken about that, and actually have CUDA 10.0. But following the instructions in the README, the CUDA toolkit module I got was version 10.1. So I installed an older version of Torch + CUDA toolkit, and it seems to be working after that.

**Comment by samuelsunarjo96** [comment]
@anaru which older version of Torch and CUDA toolkit did you exactly use that worked?

**Comment by samuelsunarjo96** [comment]
The version that worked for me was:

conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch

, since my machine has CUDA 10.0 but I was compiling things with 10.1 cuda toolkit. Also had to downgrade pillow from 7 to 6.2.2 because of the older version of Torch.

**Comment by anaru** [comment]
Sorry, maybe I should have mentioned my specific versions. Those are the versions I'm using too, and I also had to downgrade Pillow to get it to work

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
https://kaolin.readthedocs.io/en/latest/

We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates.

Closing the bug as it is no longer relevant to this repo.
