### ISSUE TITLE
Atlasnet Missing?

### ISSUE THREAD

**Issue by pclucas14** [NVIDIAGameWorks/kaolin#125]
Hi, 

I can't find your Atlasnet implementation. Could you point me to it ?

Thanks!
Lucas

**Comment by pclucas14** [comment]
😔

**Comment by ThibaultGROUEIX** [comment]
Hi,
I could try making a PR with some guidance from @Jean-Francois-Lafleche ?
Best 
Thibault

**Comment by Jean-Francois-Lafleche** [comment]
Hi @pclucas14, we have had AtlasNet on our roadmap for a while but unfortunately our attention has been taken away by other priorities. @ThibaultGROUEIX your help would be hugely appreciated, thank you for offering!

Please contact me at jlafleche@nvidia.com and I'll be more than happy to offer any assistance I can!

Thank you both for your interest in Kaolin! (And @pclucas14 I really apologize for the delay in getting back to you. Thanks for bringing to our attention the discrepancy with our README).

**Comment by pclucas14** [comment]
Hi,

Thanks for getting back to me. I’ll leave the issue open as a gentle reminder :)

Cheers,
Lucas

**Comment by shumash** [comment]
Following v0.9.0 project restructuring, Kaolin no longer provides model training code or baselines, but rather a set of modular functions to support DL research. Thanks for your suggestion.
