### ISSUE TITLE
How to save the rendered image

### ISSUE THREAD

**Issue by Zhangsihao-Yang** [NVIDIAGameWorks/kaolin#129]
I tried to run kal.visualize.show() on the server but it seems not working.
So is there an alternative way like saving the rendered images?

**Comment by shumash** [comment]
@Zhangsihao-Yang I hope you answered your question -- sorry to take a long time to respond.

If not, please re-file the bug with more specific information. What rendered images do you mean? `kaolin.visualize.show()` is not a function in the library. To save rendered images you can use any one of standard python libraries like `PIL` or `skimage.io`. 

Here is a tutorial on visualization features in Kaolin:
https://kaolin.readthedocs.io/en/latest/notes/checkpoints.html
