### ISSUE TITLE
Visualization in Jupyter Notebooks

### ISSUE THREAD

**Issue by Rvbens** [NVIDIAGameWorks/kaolin#13]
It seems that `kal.visualize.show(mesh)` won't work in Jupyter Notebooks without returning the trimesh.Trimesh().show() call

**Comment by krrish94** [comment]
Thanks for this note. This seems like a relatively high priority feature.

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and this issue is no longer current. Please refer to our latest documentation:
https://kaolin.readthedocs.io/en/latest/
