### ISSUE TITLE
Kaolin on Linux CPU support

### ISSUE THREAD

**Issue by dhirajsuvarna** [NVIDIAGameWorks/kaolin#130]
Does the present version of Kaolin works on a non GPU based Linux System?

If not is it planned to be supported?

**Comment by Jean-Francois-Lafleche** [comment]
Currently, only GPU-based installations are supported. This is in part because much of the operations supported by Kaolin would be impractically slow running only on a CPU. Were there any specific features of Kaolin you were looking to use with a CPU?

**Comment by dhirajsuvarna** [comment]
Thanks Jean and no I wasn't looking for any specific feature of Kaolin to be run on CPU. I was asking because, I do not have Nvidia GPU on my desktop which I upgraded last year. It was a poor decision I made :(
