### ISSUE TITLE
How to get depth from DIB-Renderer?

### ISSUE THREAD

**Issue by wangg12** [NVIDIAGameWorks/kaolin#134]
Currently the DIB-R only returns the differentiable color and mask, I wonder how to get depth from it?

**Comment by aluo-x** [comment]
Their rasterizer actually produces the depth: tfimdeps_bxhxwx1. However I don't think you can produce a gradient directly from this. 

A hack could be to perform the projection function and assign vertex attributes as depth. Looks like you will need to modify [Line62-67](https://github.com/NVIDIAGameWorks/kaolin/blob/63e15f3e0b77f3e103e748b1a73f4848ec78bd2c/kaolin/graphics/dib_renderer/renderer/vcrender.py#L62-L67) and the bit in the projection function if you want to do one pass only along with color. Or you could just do two passes, one for color and one for depth, or use neural mesh.

**Comment by wangg12** [comment]
Should I normalize the depth values between [0, 1] if I assign them as vertex attributes?

**Comment by aluo-x** [comment]
Should be [0, 1] I think, which I think is a requirement for DIB-R vertex attributes. 

I am unsure what the behavior will be if the faces are large, and how accurate the interpolation would be, but as an approximation it should be okay.

In the mean time check out [facebookresearch/pytorch3d](https://github.com/facebookresearch/pytorch3d), they have a SoftRas like differentiable renderer which seems to support depth output and multi gpu out of the box.
