### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by tchaton** [NVIDIAGameWorks/kaolin#138]
Dear people of kaolin,

We plan to regroup in one framework all the SOTA models for point cloud analysis and we were wondering if you would foresee any possible collaboration

You can find the repo here: https://github.com/nicolas-chaulet/deeppointcloud-benchmarks

Best,
Thomas Chaton

**Comment by Caenorst** [comment]
Hi Thomas,

Thank you for your interest in Kaolin.

First of all, you are welcome to make any contribution to Kaolin, on which we will try our best to review and merge.
And if you'd like to use Kaolin within your FW we would gladly help you using it and follow the issues that you may face. 

Do you have a further collaborative ideas in mind that you would like to share ?

You can reach out to me at cfujitsang@nvidia.com.

Best,
Clement Fuji Tsang

**Comment by shumash** [comment]
Hi @tchaton, first of all - your repo looks great! Not sure what you had in mind in terms of collaboration, but we'd be very interested to know what features Kaolin could add to make it useful for your work. 

For example, I see that you have also implemented your own 3D dashboard, and would like to draw your attention to our work on visualization: [Tutorial on 3D Checkpoints](https://kaolin.readthedocs.io/en/latest/notes/checkpoints.html). 
This is currently a work in progress, and we're working on adding support for semantic labels for point clouds and other features. Would love to hear what else is needed.

**Comment by shumash** [comment]
Closing the issue, but please stay in touch. If there is any functionality we could add to Kaolin to support your work -- let us know!
