### ISSUE TITLE
Kaolin with Google Colab 

### ISSUE THREAD

**Issue by christinezuzart** [NVIDIAGameWorks/kaolin#142]
Hi,
Since Kaolin on windows is not supported and I do not have a linux machine, I decided to use Colab to setup Kaolin.

I was successful in following the setup instructions without any error.
However, when i try to print the version of Kaolin, it says the following 

```
kal.__version__

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-27-0eb511c760b2> in <module>()
----> 1 kal.__version__

AttributeError: module 'kaolin' has no attribute '__version__'
```

Please have a look at my notebook here to see my workflow https://github.com/christinezuzart/kaolin_tests/blob/master/Kaolin_V3.ipynb

**Comment by aweinmann** [comment]
Hi, 
I got Kaolin to install on colab (py3, GPU) with:
`!pip install git+https://github.com/NVIDIAGameWorks/kaolin`
`import kaolin as kal`
`print(kal.__version__)`

>> 0.1.0

I did not try anything further, hope this helps.

**Comment by christinezuzart** [comment]
That worked.Thanks !!!!

**Comment by dhirajsuvarna** [comment]
@aweinmann : can you explain what does the commad does, and why it works after this command?
