### ISSUE TITLE
Best practice for looping over affine transformations with distance metrics

### ISSUE THREAD

**Issue by mm04926412** [NVIDIAGameWorks/kaolin#145]
Hello

I apologise if the github is not the place for these sorts of queries but I am attempting to create a chamfer distance function that gives the approximate minimum chamfer distance across all relative orientations of the point cloud to create a loss metric that is rotation invariant. Is there anything in the library to perform an efficient search in a parallel manner over the affine transformations or over any set of arbitary matrix multiplications of one of the point clouds?

Thanks in advance for any assistance.

**Comment by shumash** [comment]
Thank you for your query, and sorry we were not able to answer your question, as the team has limited bandwidth. Closing this as an old issue.
