### ISSUE TITLE
cannot import 'graphics' when running the DIB-R testing script

### ISSUE THREAD

**Issue by ZhiyeTang** [NVIDIAGameWorks/kaolin#146]
When I run `python3 ./test_dibr.py` under the directory "/kaolin/examples/renderers/test", there is an import error saying that there is no module called 'graphics'.
At first I supposed that it's a missing module in my computer, so I search for graphics.py in Pypi.org and install it. But the error still exist. This time it says there is no module called 'graphics.utils'. Then I suspected that maybe the graphics module required here isn't the graphics.py I installed just now. Thus I deleted all the code importing graphics and then import the DIBRenderer from kaolin.
I replaced rows 15 to 18:  

```
import graphics
from graphics.utils.utils_perspective import lookatnp, perspectiveprojectionnp
from graphics.utils.utils_sphericalcoord import get_spherical_coords_x
from graphics.render.base import Render as Dib_Renderer
```

with:

```
from kaolin.graphics import DIBRenderer as Dib_Renderer
```

But it seems that there do exist other problems. Error information is below:

```
Drawing DIBRenderer VertexColor:   0%|                   | 0/90 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test_dibr.py", line 90, in <module>
    main()
  File "test_dibr.py", line 83, in main
    predictions, _, _ = renderer(points=[vertices, faces[0].long()], colors=[textures])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/graphics/dib_renderer/renderer/base.py", line 62, in forward
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'colors'
```

After reading the original code, I revise the code at row 83:

```
# predictions, _, _ = renderer.forward(points=[vertices, faces[0].long()], colors=[textures])
predictions, _, _ = renderer.forward(points=[vertices, faces[0].long()], colors_bxpx3=textures)
```

It works well.

**Comment by shapovalov** [comment]
I am trying to run `kaolin/examples/ImageRecon/Dib/train.py` and run into similar problems. It looks like it is using an older version of Kaolin. I’ve tried to change the imports and interfaces but they seem to have diverged quite a bit. Can you maybe provide the commit where it was working? Thanks.

**Comment by archana1998** [comment]
Have the same problem with running train.py for DIB-R, if anyone's able to provide a working code please do so! Thanks.

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
https://kaolin.readthedocs.io/en/latest/

Closing the bug as it is no longer relevant to this repo.
