### ISSUE TITLE
Correctness of EMD loss

### ISSUE THREAD

**Issue by gkioxari** [NVIDIAGameWorks/kaolin#149]
Hi kaolin team! It just came to our attention that the code that you include for EMD (original source: https://github.com/fxia22/pointGAN) has no guarantees of correctness. This is also discussed here: https://github.com/fxia22/pointGAN/issues/5. Just fyi!

**Comment by krrish94** [comment]
Thanks for bringing this to our notice @gkioxari. We're investigating this further, and any input you have is much appreciated!

**Comment by gkioxari** [comment]
Hi @krrish94! The author of the implementation said "... the code was designed by [author] and has no guarantee on its correctness or approximation accuracy. [Author] recommended not to use it in a serious use case." I spent a significant amount of time trying to prove its bound and found no theoretical guarantees either. It's not related to the epsilon relaxation of the Bertsekas auction algorithm whatsoever. I hope this is useful.

**Comment by shumash** [comment]
Closing old issue.
