### ISSUE TITLE
Render an object with background picture

### ISSUE THREAD

**Issue by zhjscut** [NVIDIAGameWorks/kaolin#155]
How can I use a soft_renderer.SoftRenderer instance to render an object with a background picture,  such as a chair object on a grass picture?

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation.

Closing the bug as it is no longer relevant to this repo.
