### ISSUE TITLE
Whether 'set_look_at_parameters' is Differentiable 

### ISSUE THREAD

**Issue by tau-yihouxiang** [NVIDIAGameWorks/kaolin#156]
I wonder whether 'set_look_at_parameters' is differentiable since its function 'compute_camera_params' is implemented by numpy.

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation.

Our camera functions are now fully differentiable

Closing the bug as it is no longer relevant to this repo.
