### ISSUE TITLE
TriangleMesh bad shape

### ISSUE THREAD

**Issue by P4uL7** [NVIDIAGameWorks/kaolin#157]
I was trying to implement the "**Hello, 3D world!**" example from the documentation but something seems to be off.

First of all, after loading the mesh and calling **mesh.faces.shape**, I get torch.Size([**960**, 3]) instead of torch.Size([**482**, 3]).  (The mesh visualization seems to be OK at this point)

Secondly, after converting the TriangleMesh to a **VoxelGrid** and calling kal.visualize on it, this is what I get [Click!](https://i.imgur.com/zWUP8rC.png).

[HERE](https://pastebin.com/raw/Qbvvh9Ms) is a pip freeze output. 
I am running python 3.6.7 and CUDA 10.0.130 with Driver Version: 440.33.01.

**Comment by rfuruta** [comment]
Same problem on my environment: python 3.6.10, numpy 1.17.5 and CUDA 10.2.89 with Driver Version 440.33.01.

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
https://kaolin.readthedocs.io/en/latest/

Closing the bug as it is no longer relevant to this repo.
