### ISSUE TITLE
sdf_to_trianglemesh does not halt

### ISSUE THREAD

**Issue by mrkulk** [NVIDIAGameWorks/kaolin#158]
Creating a spherical mesh from verts/faces, followed by trianglemesh_to_sdf and then sdf_to_trianglemesh is failing. However directly creating an SDF using 'kal.rep.SDF.sphere()' works. 

This works: 
```
sdf = kal.rep.SDF.sphere()
verts, faces = kal.conversions.sdf_to_trianglemesh(sdf, bbox_dim=2)
mesh = kal.rep.TriangleMesh.from_tensors(verts, faces) 
```

This never halts (at sdf_to_trianglemesh): 
```
mesh1 = kal.rep.TriangleMesh.from_tensors(verts1.clone(), faces1.clone())
sdf1 = kal.conversions.trianglemesh_to_sdf(mesh1)
verts, faces = kal.conversions.sdf_to_trianglemesh(sdf, bbox_dim=2)
```

The output of:
```
 print(sdf)
print(sdf1)
```

returns: 

```
<function sphere.<locals>.eval_sdf at 0x7f19f806b048>
<function trianglemesh_to_sdf.<locals>.eval_query at 0x7f19c9d980d0>
```

This issue seems to be due to the form of the eval query

**Comment by krrish94** [comment]
Thanks for digging into this! Might I know what version of pytorch / cuda / python you're using?

**Comment by mrkulk** [comment]
pytorch: 1.4.0

cuda: Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

Python 3.6.9

thank you!

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation.

Closing the bug as it is no longer relevant to this repo.
