### ISSUE TITLE
Where can I download "kaolin/examples/renderers/test/data/banana.obj"?

### ISSUE THREAD

**Issue by wangg12** [NVIDIAGameWorks/kaolin#16]

**Comment by Kuldaen** [comment]
I have the same question. where did you find it?

**Comment by felixboevr** [comment]
it's originally in /kaolin/examples/renderers/DIB-R/graphics/test/banana.obj
you have to copy it to /kaolin/examples/renderers/test/data/banana.obj

**Comment by tejank10** [comment]
Is there a `banana.mtl` and `banana.jpg` available as well?
