### ISSUE TITLE
help with exporting models to onnx

### ISSUE THREAD

**Issue by antmillar** [NVIDIAGameWorks/kaolin#160]
Hello

I was hoping to try export pointnet++ to onnx via torch. However I get the following error

`RuntimeError: ONNX export failed: Couldn't export Python operator FurthestPointSampling`

I suspect this is because the sampling is implemented in c ?

I wondered if there's a viable way to export. Should I rewrite some of the components in python?

Thanks!

**Comment by krrish94** [comment]
Good question! I think it is doable (see [this tutorial](https://github.com/onnx/tutorials/blob/master/PyTorchCustomOperator/README.md)).

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation.

Closing the bug as it is no longer relevant to this repo.

**Comment by WeilunDai66** [comment]
Hi, @antmillar. Have you solved the problem? I found FurthestPointSampling in lots of point cloud related work and it is difficult to export the onnx model. Could you please share your solution?
