### ISSUE TITLE
SoftRas example data is missing

### ISSUE THREAD

**Issue by anaru** [NVIDIAGameWorks/kaolin#161]
When I try to run the example here:
`kaolin/examples/renderers/SoftRas/examples/demo_render.py`
I get this error:
`FileNotFoundError: [Errno 2] No such file or directory: '/home/andrewwilson/projects/diff_render/kaolin/examples/renderers/SoftRas/examples/../data/obj/spot/spot_triangulated.obj'`

I went looking for the example data, and there's no _data_ folder in the SoftRas root. There is a _data_ folder in the original SoftRas project, so either this wasn't carried over, or it was deleted at some point. Is the data supposed to be included in this project?

**Comment by krrish94** [comment]
The examples to run are [here](https://github.com/NVIDIAGameWorks/kaolin/tree/master/examples/renderers/test). And the requisite `obj` files are [here](https://github.com/NVIDIAGameWorks/kaolin/tree/master/examples/renderers/DIB-R).
