### ISSUE TITLE
How to load input mesh from .ply file? 

### ISSUE THREAD

**Issue by samuelsunarjo96** [NVIDIAGameWorks/kaolin#163]
Currently I only know of two ways of constructing a Mesh object, either from_obj or from_tensor.

**Comment by Jean-Francois-Lafleche** [comment]
Hi @samuelsunarjo96, Kaolin currently only provides .obj and from_tensor functions to import meshes, but we are working on adding more support for all common mesh formats. If you need this functionality immediately, I can recommend Assimp https://github.com/assimp/assimp which you can use to extract vertices and face indices of common 3D file formats.

**Comment by samuelsunarjo96** [comment]
@Jean-Francois-Lafleche Okay! Thanks for your help and the recommendation!
