### ISSUE TITLE
Potential error in Image Reconstruction using DIB-R

### ISSUE THREAD

**Issue by avik-pal** [NVIDIAGameWorks/kaolin#164]
From what I understand, laplacian loss is used as a regularizer in single view mesh reconstruction pipelines. However, [this code](https://github.com/NVIDIAGameWorks/kaolin/blob/cbd057cb8e4ab620b964c2b6b1bd39e4671815d3/examples/ImageRecon/Dib/train.py#L152) seems to compute the laplacian smoothening factor for the original base spherical mesh, instead of the reconstructed mesh which has vertices `pred_verts`.

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
https://kaolin.readthedocs.io/en/latest/

We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates.

Closing the bug as it is no longer relevant to this repo.
