### ISSUE TITLE
Kaolin installation on jetson nano

### ISSUE THREAD

**Issue by jvschw** [NVIDIAGameWorks/kaolin#166]
Dear All, 

does kaolin run on a jetson nano? If yes, can you point me to installation instructions? 

Best,
Jens

**Comment by lunarpulse** [comment]
I have tried it on jetson Xavier.

Due to to the pptk module, runtime error occurs.
Kaolin installs well but not callable.

**Comment by krrish94** [comment]
Currently, there is no official support for Kaolin on Jetson. However, it can be installed on Jetson provided `pptk` is built from source.

**Comment by jvschw** [comment]
Thank you very much, I will give it a try. 

Best
Jens

> On 6. Apr 2020, at 20:28, Krishna Murthy <notifications@github.com> wrote:
> 
> Currently, there is no official support for Kaolin on Jetson. However, it can
be installed on Jetson provided pptk is built from source.

**Comment by neutrum** [comment]
Hello, 
can someone please point me how to run Kaolin on Jetson Nano? 
I tried to built it from source but got error on usd-core python package that is not shipped for aarch64 architecture.

Thank you

**Comment by shumash** [comment]
Closing this as an old issue. Kaolin now provides wheels. If the wheels do not work on your system, please file a new bug.
