### ISSUE TITLE
Batched Chamfer ?

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [NVIDIAGameWorks/kaolin#167]
Thanks for Kaolin :)
Is there a way to have a batch chamfer distance without a for loop ?

```
Input :
 points1 : batch x num_points_1 x 3
 points2 : batch x num_points_2 x 3

Output 
points1 ->  points2 : batch, num_points_1
points2 ->  points1 : batch, num_points_2
```
Best regards,
Thibault

**Comment by Caenorst** [comment]
Hi Thibault !

Thank you for your interest in Kaolin !
We are currently working on batching, but we don't have the feature yet.

Best regards,
Clement

**Comment by ThibaultGROUEIX** [comment]
Thanks, i'll make the AtlasNet PR with a for loop then.

**Comment by krrish94** [comment]
Leaving this open, as batched Chamfer is a high-priority  feature.

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation.

Closing the bug as it is no longer relevant to this repo.
