### ISSUE TITLE
Cuda

### ISSUE THREAD

**Issue by shersoni610** [NVIDIAGameWorks/kaolin#17]
Hello,

I am using Ubuntu which has Cuda 10.1 installed. I checked that torch is working with it.

However, when I run pytest tests, I get the following Cuda error

 RuntimeError: CUDA error: no kernel image is available for execution on the device
__________________________________ ERROR collecting tests/datasets/test_usdfile.py 

what should I do?

**Comment by krrish94** [comment]
Could I ask for more details on your setup? Specifically, the type of GPU you're on, and it's "compute capability"?

**Comment by shersoni610** [comment]
I use Titan X black on Ubuntu 18.04. The cuda version is 10.1.

**Comment by shersoni610** [comment]
Hello,
It seems that I have pytorch correctly installed but the Kaolin is not
working:


(kaolin) csverma@blackhole:$ python
Python 3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>>

**Comment by quyanqiu** [comment]
@krrish94, Is Kaolin only support CUDA10.1?When I use cuda10.0 assertionError occur and it said NVIDIA driver on my system is too old(found version 10000). My GPU is TelsaM40

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and this issue is no longer current. Please refer to our latest documentation:
https://kaolin.readthedocs.io/en/latest/
