### ISSUE TITLE
Dataloader deprecated?

### ISSUE THREAD

**Issue by otmanon** [NVIDIAGameWorks/kaolin#170]
Hi, I'm trying to run train.py in Dib-R and i keep getting that module kaolin does not have a dataloader attribute. Looking at the other ImageRecon examples , they all seem to use this attribute that is nowhere to be found in the rest of the codebase.

What should I be using?

**Comment by Caenorst** [comment]
Hi @otmanon !

Thank you for your interest in Kaolin.

Can you specify if you are talking about `examples/ImageRecon/Dib` or `examples/renderers/DIB-R` ?

**Comment by otmanon** [comment]
Sorry, I am talking about examples/ImageRecon/Dib

**Comment by Caenorst** [comment]
Closing as this is related to v0.1
