### ISSUE TITLE
Compiling error: ‘TORCH_CHECK’ was not declared in this scope

### ISSUE THREAD

**Issue by miaoqiz** [NVIDIAGameWorks/kaolin#171]
Hi,

When running:

python3 setup.py build_ext --inplace

There is a compiling error:

---------------------------------------------------------------------------------------------------------

kaolin/cuda/util.h:9:3: error: ‘TORCH_CHECK’ was not declared in this scope
   TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
   ^
kaolin/cuda/util.h:9:3: note: in definition of macro ‘CHECK_CUDA’
   TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
   ^~~~~~~~~~~
kaolin/cuda/furthest_point_sampling.cpp:39:3: note: in expansion of macro ‘CHECK_INPUT’
   CHECK_INPUT(points);
   ^
kaolin/cuda/util.h:9:3: note: suggested alternative: ‘TORCH_API’
   TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
   ^
kaolin/cuda/util.h:9:3: note: in definition of macro ‘CHECK_CUDA’
   TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
   ^~~~~~~~~~~
kaolin/cuda/furthest_point_sampling.cpp:39:3: note: in expansion of macro ‘CHECK_INPUT’
   CHECK_INPUT(points);
   ^
kaolin/cuda/furthest_point_sampling.cpp: In function ‘at::Tensor gather_by_index_grad(at::Tensor, at::Tensor, int)’:
kaolin/cuda/util.h:9:3: error: ‘TORCH_CHECK’ was not declared in this scope
   TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
   ^
kaolin/cuda/util.h:9:3: note: in definition of macro ‘CHECK_CUDA’
   TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
   ^~~~~~~~~~~
kaolin/cuda/furthest_point_sampling.cpp:57:3: note: in expansion of macro ‘CHECK_INPUT’
   CHECK_INPUT(grad_out);
   ^
kaolin/cuda/util.h:9:3: note: suggested alternative: ‘TORCH_API’
   TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
   ^
kaolin/cuda/util.h:9:3: note: in definition of macro ‘CHECK_CUDA’
   TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
   ^~~~~~~~~~~
kaolin/cuda/furthest_point_sampling.cpp:57:3: note: in expansion of macro ‘CHECK_INPUT’
   CHECK_INPUT(grad_out);
   ^
kaolin/cuda/furthest_point_sampling.cpp: In function ‘at::Tensor furthest_point_sampling(at::Tensor, int)’:
kaolin/cuda/util.h:9:3: error: ‘TORCH_CHECK’ was not declared in this scope
   TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
   ^
kaolin/cuda/util.h:9:3: note: in definition of macro ‘CHECK_CUDA’
   TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
   ^~~~~~~~~~~
kaolin/cuda/furthest_point_sampling.cpp:73:3: note: in expansion of macro ‘CHECK_INPUT’
   CHECK_INPUT(points);
   ^
kaolin/cuda/util.h:9:3: note: suggested alternative: ‘TORCH_API’
   TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
   ^
kaolin/cuda/util.h:9:3: note: in definition of macro ‘CHECK_CUDA’
   TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
   ^~~~~~~~~~~
kaolin/cuda/furthest_point_sampling.cpp:73:3: note: in expansion of macro ‘CHECK_INPUT’
   CHECK_INPUT(points);
   ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

---------------------------------------------------------------------------------------------------------

Is this caused by the pytorch version mismatch?

Thanks,

**Comment by ynyBonfennil** [comment]
I have the same issue with the latest version of pytorch (1.4).
This error doesn't happen with pytorch 1.2, as miaoqiz says.

**Comment by miaoqiz** [comment]
@ynyBonfennil Thanks for the suggestion! I got it installed with pytorch 1.2

When I ran "pytest tests/", it looks like the "pxr" module cannot be found.


==================================== ERRORS ====================================
_______________ ERROR collecting tests/datasets/test_usdfile.py ________________
ImportError while importing test module '/home/filmlight/Downloads/kaolin/tests/datasets/test_usdfile.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/datasets/test_usdfile.py:19: in <module>
    from kaolin.datasets.usdfile import USDMeshes
kaolin/datasets/usdfile.py:19: in <module>
    from pxr import Usd, UsdGeom, UsdLux, Sdf, Gf, Vt
E   ModuleNotFoundError: No module named 'pxr'
_______________ ERROR collecting tests/visualize/test_vis_usd.py _______________
ImportError while importing test module '/home/filmlight/Downloads/kaolin/tests/visualize/test_vis_usd.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/visualize/test_vis_usd.py:8: in <module>
    from kaolin.visualize.vis_usd import VisUsd
kaolin/visualize/vis_usd.py:24: in <module>
    from pxr import Usd, UsdGeom, UsdLux, Sdf, Gf, Vt
E   ModuleNotFoundError: No module named 'pxr'

**Comment by Jean-Francois-Lafleche** [comment]
Run`source setenv.sh` before running the tests to avoid that import error.

Thanks for bringing up the other issue, we will look into reproducing it and hopefully find a fix soon.

**Comment by miaoqiz** [comment]
@Jean-Francois-Lafleche Thanks for your suggestion! I appreciate it.

It actually got the same error after running "setenv.sh". I am running it inside a NGC container. Will it be an issue?

Thanks and have a good day!

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation.

Closing the bug as it is no longer relevant to this repo.
