### ISSUE TITLE
TypeError when iterating over DataLoader initialized with kaolin.datasets.modelnet.ModelNet

### ISSUE THREAD

**Issue by kondela** [NVIDIAGameWorks/kaolin#172]
I am trying to iterate over the ModelNet dataset as in example available in [docs](https://kaolin.readthedocs.io/en/latest/modules/datasets.modelnet.html)

Using latest PyTorch 1.4.0, Kaolin 0.1.0 and ModelNet10 dataset downloaded from
[Princeton website](https://modelnet.cs.princeton.edu/) I get the following error:
`TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'kaolin.rep.TriangleMesh.TriangleMesh'>
`

Code to reproduce:

```
from kaolin.datasets.modelnet import ModelNet
from torch.utils.data import Dataset, DataLoader

dataset = ModelNet(basedir='/Datasets/ModelNet10')
train_loader = DataLoader(dataset, batch_size=1, shuffle=True, num_workers=8)
obj, label = next(iter(train_loader))
```

**Comment by krrish94** [comment]
We recently updated our `Dataset` classes. Will add documentation with "best-use" guidelines.
