### ISSUE TITLE
Bilinear sampling texture from image with vertices

### ISSUE THREAD

**Issue by zheLim** [NVIDIAGameWorks/kaolin#175]
Greetings.
I have a set of vertices inferenced from Face Reconstruction Network such as 3DDFA. And I would like to sample the texture so that I can render the face image.
How am I suppose to do that with kaolin?
I read neural mesh rendering, and find that texture are predefined or optimized from image. These method cannot be done if I am going train 3DDFA. 
If you can provide some hints, I'd be grateful.

**Comment by krrish94** [comment]
You can use one of our differentiable renderers for this https://github.com/NVIDIAGameWorks/kaolin/tree/master/kaolin/graphics
