### ISSUE TITLE
'kaolin' has no attribut 'dataloader

### ISSUE THREAD

**Issue by ghost** [NVIDIAGameWorks/kaolin#178]
When running pixel2mesh train.py I get the following error

Traceback (most recent call last):
  File "/home/griffin/Kaolin/kaolin/examples/ImageRecon/Pixel2Mesh/train_6layer.py", line 54, in <module>
    points_set = kal.dataloader.ShapeNet.Points(root ='../../datasets/',categories =args.categories , \
AttributeError: module 'kaolin' has no attribute 'dataloader'

I have tried running train.py from the pixel2mesh folder and the kaolin root folder. but get the same error.

**Comment by krrish94** [comment]
Closing, as the error is from an old version.
