### ISSUE TITLE
math deprecated... replace with mathutils?

### ISSUE THREAD

**Issue by otmanon** [NVIDIAGameWorks/kaolin#179]
Hi, every time I try importing Soft_Renderer I fail because there is no math module... though there is a mathutils module with apparently the same classes + functions I need.

**Comment by krrish94** [comment]
This PR should address: https://github.com/NVIDIAGameWorks/kaolin/pull/177

**Comment by shumash** [comment]
The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and this issue is no longer current.
