### ISSUE TITLE
Where to download ShapeNet-Images

### ISSUE THREAD

**Issue by otmanon** [NVIDIAGameWorks/kaolin#180]
To run a trial for geometrics, I need to have downloaded the Shapenet images dataset arleady... I am stuggling where to find this dataset. I have the Shapenet core dataset, of meshes.... but that doesn't come with corresponding images. Should I render these images myself or is there a place I can download them? The Shapenet website requires some sort of administrative approval...

**Comment by krrish94** [comment]
This should answer your question
https://github.com/NVIDIAGameWorks/kaolin/issues/120#issuecomment-574046657
