### ISSUE TITLE
Hello3Dworld tutorial - strange voxelgrid, pptk viewer permission error  

### ISSUE THREAD

**Issue by chrispduck** [NVIDIAGameWorks/kaolin#185]
I installed Kaolin using the `python setup.py install` command, in a conda env with:
Ubuntu 16.04
pytorch 1.3.1. 

The installation has been verified to work correctly with the pointnet classifier. 

When trying to run the following code, below, from the Hello3Dworld example the mesh is rendered OK. However, the voxel conversion is behaving strangely  - see image below, and an error is thrown when trying to visualize the point cloud version. 

Any help would be much appreciated!

My code:
```
import kaolin as kal
mesh = kal.rep.TriangleMesh.from_obj('model.obj')
kal.visualize.show_mesh(mesh)  #OK
voxels = kal.conversions.trianglemesh_to_voxelgrid(mesh, 32)
kal.visualize.show(voxels, mode='voxels')    # Strange representation from this
points, _ = kal.conversions.trianglemesh_to_pointcloud(mesh, 1000)
kal.visualize.show(points, mode='points') # Error thrown from this line
```

A mesh of a plain sphere was transformed into this voxel representation: 
![Pointcloud Conversion 2](https://user-images.githubusercontent.com/32284498/77564705-0cbeec00-6ebb-11ea-85a3-6934d1ae99f6.png)

![Pointcloud Conversion](https://user-images.githubusercontent.com/32284498/77564712-0f214600-6ebb-11ea-90fa-bf7eeabc91d0.png)

Permission error:
```
> Traceback (most recent call last):
>   File "/home/chris/anaconda3/envs/4YP/lib/python3.7/subprocess.py", line 800, in __init__
>     restore_signals, start_new_session)
>   File "/home/chris/anaconda3/envs/4YP/lib/python3.7/subprocess.py", line 1551, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> PermissionError: [Errno 13] Permission denied: '/home/chris/anaconda3/envs/4YP/lib/python3.7/site-packages/pptk-0.1.0-py3.7-linux-x86_64.egg/pptk/viewer/viewer'
> Process finished with exit code 1
> 

```

**Comment by krrish94** [comment]
Seems to be a known `pptk` error. See https://github.com/heremaps/pptk/issues/3

**Comment by kosuke55** [comment]
I also installed Kaolin using the python setup.py install command, in a conda env with:
Ubuntu 16.04  
pytorch 1.5.1    
torchvision 0.6.1   

and I found the same problem. 
![Screenshot from 2020-07-08 17-08-56](https://user-images.githubusercontent.com/39142679/86894270-caee4480-c13d-11ea-8bea-8c95f76a7c3b.png)



I think there are two other problems with this.  
- Voxel 
I don't think this is a visualization problem, but rather a misaligned voxel index.
https://github.com/NVIDIAGameWorks/kaolin/blob/6609114e9be78bdff6ab3536c7ec155e3936d391/kaolin/conversions/meshconversions.py#L136
I think the following changes to this line will give you the correct voxels.
```
points = (points * (resolution - 1) + resolution / 2).long()
```
![Screenshot from 2020-07-08 17-09-08](https://user-images.githubusercontent.com/39142679/86894298-d3df1600-c13d-11ea-8f7f-df453f2ab321.png)


- PointCloud 
Giving permissions could be run.
```
sudo chmod 755 /home/kosuke/.pyenv/versions/anaconda3-5.3.1/envs/kaolin/lib/python3.6/site-packages/pptk/viewer/viewer
```
Also reinstalling it was able to run as well.
```
pip unsintall pptk
pip install pptk
```

**Comment by kosuke55** [comment]
The original program also displays correctly when vertex_offset is set to 0.5. This is due to an error in the documentation and needs to be fixed. I also think the default value of vertext_offset should be 0.5.
```
voxels = kal.conversions.trianglemesh_to_voxelgrid(mesh, 32, vertex_offset=0.5)
```

https://kaolin.readthedocs.io/en/latest/notes/hello3d.html
![image](https://user-images.githubusercontent.com/39142679/86927913-dc9c1000-c16e-11ea-9c7f-245f1675f300.png)
