### ISSUE TITLE
Can't setup on Windows

### ISSUE THREAD

**Issue by Yukarun** [NVIDIAGameWorks/kaolin#19]
![QQ图片20191118111715](https://user-images.githubusercontent.com/29618787/69022107-21fba980-09f5-11ea-8e63-36a1aeae94ed.png)

**Comment by MtlsBart** [comment]
https://github.com/NVIDIAGameWorks/kaolin/issues/4#issuecomment-555090465

**Comment by wangyibin0011** [comment]
I am the same problem as you, and I do not know how to solve it at present. If you have a good solution, please contact me, thank you

**Comment by wissalsayhi** [comment]
I solved this error by seperatly installing shapely via : pip install shapely.

**Comment by Yukarun** [comment]
> 
> 
> I solved this error by seperatly installing shapely via : pip install shapely.

using "conda install -c conda-forge shapely " can pass this,but another error appears
![QQ图片20191120102130](https://user-images.githubusercontent.com/29618787/69203564-a417d980-0b7f-11ea-9b48-c91c6910834b.png)

**Comment by wissalsayhi** [comment]
I don't know about that but currently I have this error : 
![kaolin_error](https://user-images.githubusercontent.com/13519346/69246878-cd4d5f80-0ba9-11ea-99fd-82858975163a.JPG)

If anyone managed to set it correctly on Windows 10 please help

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates.

Closing the bug as it is no longer relevant to this repo.
