### ISSUE TITLE
Is there a differentiable function for inverse perspective geometry?

### ISSUE THREAD

**Issue by SeokjuLee** [NVIDIAGameWorks/kaolin#191]
Thanks for releasing such a powerful library for 3D vision.
I am interested in estimating depth by differentiable rendering.
If a dense correspondence map (F_12) and relative camera pose (T_12) between two frames (I_1, I_2) are given, can I inversely compute a relative reference depth in a differentiable way?
Could you recommend some scripts to achieve this?

**Comment by krrish94** [comment]
Currently the differentiable renderers support rendering of depth. Although there isn't a goto tutorial at the moment, it is a good suggestion and we will expose our depth image API in a future release.

**Comment by shumash** [comment]
Closing old issue.
