### ISSUE TITLE
Failed installation due to higher version of gcc

### ISSUE THREAD

**Issue by YiruS** [NVIDIAGameWorks/kaolin#192]
Hi there,
 
I followed the instructions to install kaolin. However, the error shows below: 

error: #error -- unsupported GNU version! gcc versions later than 7 are not supported!
  129 | #error -- unsupported GNU version! gcc versions later than 7 are not supported!

Here are the configurations of my machine:
Fedora 30
CUDA 10.0.130
Display Driver: 440.31
gcc version: gcc (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1)
Pytorch: 1.4
Python: 3.6

Is there any workaround to fix the higher version of gcc?

Thanks!

**Comment by krrish94** [comment]
Hi, unfortunately it seems to be a CUDA error, and there's very less we can do about it (see https://stackoverflow.com/questions/53344283/gcc-versions-later-than-7-are-not-supported-by-cuda-10-qt-error-in-arch-linux)

**Comment by shumash** [comment]
Closing old issue.
