### ISSUE TITLE
Error of importing kaolin

### ISSUE THREAD

**Issue by YiruS** [NVIDIAGameWorks/kaolin#193]
After the installation when I tried to import kaolin, it shows error below:
`import kaolin as kal`

File "kaolin/conversions/meshconversions.py", line 23
    def trianglemesh_to_pointcloud(mesh: kaolin.rep.Mesh, num_points: int):
                                       ^
SyntaxError: invalid syntax

===============================
The configurations are:
Ubuntu 16.04
CUDA 10.1.243
Display driver:  418.87
Pytorch: 1.4
Python: 3.6
numpy: 1.18.1

How could I fix this? Thanks!

**Comment by krrish94** [comment]
Hi @YiruS,

I reran `flake8` on the file you mentioned, and I don't get a syntax error. Could you pull afresh and recompile?

Thanks!

**Comment by YiruS** [comment]
> Hi @YiruS,
> 
> I reran `flake8` on the file you mentioned, and I don't get a syntax error. Could you pull afresh and recompile?
> 
> Thanks!

Problem got solved after pulling the newest master branch. Thanks!
