### ISSUE TITLE
Compilation failed in CUDA load_texture module

### ISSUE THREAD

**Issue by suntaochun** [NVIDIAGameWorks/kaolin#20]
![image](https://user-images.githubusercontent.com/31800139/69024054-13fd5700-09fc-11ea-85c6-0c4b61793ae1.png)
I try to install kaolin library in Windows 10 platform.
I search for torch/torch.h to find possible solutions and also search for Internet for solutions. I have tried giving the administor access to VS code for cl.exe status problem but failed. 
I already installed CUDA 10.0 and cudnn 7.6.4. I also use "conda upgrade pytorch" to upgrade pytorch.
Thanks for helping me:)

**Comment by krrish94** [comment]
Ah, we haven't unfortunately tested Windows support yet. I know of a few users who got this to successfully build (and work) on Windows. Isn't it weird that you have a combination of forward and back slashes in `G:\Anaconda\lib\site-packages\torch\lib\include\torch\csrc\api\include\torch/torch.h(7)`.  (Shouldn't the `torch/torch.h` instead be `torch\torch.h`?)

Disclaimer: I'm not a Windows expert, so I might just be speculating.

**Comment by suntaochun** [comment]
Thanks so much for asking my question !!! I'm looking forward to your testing on Windows and also I will test on Linux.
----- 原始邮件 -----
发件人：Krishna Murthy <notifications@github.com>
收件人：NVIDIAGameWorks/kaolin <kaolin@noreply.github.com>
抄送人：suntaochun <suntaochun@sina.com>,  Author <author@noreply.github.com>
主题：Re: [NVIDIAGameWorks/kaolin] Compilation failed in CUDA load_texture module (#20)
日期：2019年11月18日 13点01分

Ah, we haven't unfortunately tested Windows support yet. I know of a few users who got this to successfully build (and work) on Windows. Isn't it weird that you have a combination of forward and back slashes in G:\Anaconda\lib\site-packages\torch\lib\include\torch\csrc\api\include\torch/torch.h(7).  (Shouldn't the torch/torch.h instead be torch\torch.h?)
Disclaimer: I'm not a Windows expert, so I might just be speculating.

&mdash;

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)
Closing the bug as it is no longer relevant to this repo.
