### ISSUE TITLE
pyglet requires an X server with GLX

### ISSUE THREAD

**Issue by zhangmozhe** [NVIDIAGameWorks/kaolin#206]
Hi there,

When I try to visualize the mesh with `kal.visualize.show(mesh)`, it prompts that:
pyglet.gl.glx_info.GLXInfoException: pyglet requires an X server with GLX.

After google, I find that I need to reinstall the gpu driver and cuda with `--no-opengl-libs` option. However, I am using a remote gpu server and I do not the privilege to change the gpu driver. I wonder whether there is other method to solve this issue? Is there any plan to use library other than pyglet for visualization?

Thanks!

**Comment by krrish94** [comment]
I think this is an issue with the trimesh visualizer we are invoking internally. We haven't built visualization support for remote servers in Kaolin.

To be fair, `kal.visualize.show(mesh)` doesn't need a GPU unless rendering very high quality meshes at interactive rates. I'd use a local workstation/laptop for visualizing.

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation.

We now have different tools for visualization.

Closing the bug as it is no longer relevant to this repo.
