### ISSUE TITLE
Nuscenes dataloader 

### ISSUE THREAD

**Issue by jonahthelion** [NVIDIAGameWorks/kaolin#209]
Kaolin claims to support `PyTorch >=1.2, <1.5` but the nuscenes-devkit is only supported for `PyTorch >= 1.3.1`.

Nuscenes pytorch version requirement: https://github.com/nutonomy/nuscenes-devkit/issues/367

**Comment by Caenorst** [comment]
Here is the plan to put nuscenes back in Kaolin:
1) Make a simple way to install nuscenes-devkit and it's specific dependencies without touching Kaolin's general dependencies (pytorch, torchvision, numpy, ...).
2) Try to see if nuscenes in Kaolin can actually run with lower version of pytorch / torchvision / pillow.

**Comment by holger-motional** [comment]
@jonahthelion @Caenorst Hopefully our latest nuscenes-devkit PR will make things easier for you (to be merged soon): https://github.com/nutonomy/nuscenes-devkit/pull/510.
We are removing the default dependency on torch, motmetrics and pandas.

**Comment by shumash** [comment]
Closing old issue.
