### ISSUE TITLE
Need simple run test for ImageRecon/Dib

### ISSUE THREAD

**Issue by Caenorst** [NVIDIAGameWorks/kaolin#219]
We don't keep track of https://github.com/NVIDIAGameWorks/kaolin/tree/master/examples/ImageRecon/Dib proper behavior in the CI.

We need to add a quick tests such as in https://github.com/NVIDIAGameWorks/kaolin/blob/master/tests/examples/run/test_classification.sh
And then add it's execution as in:
https://github.com/NVIDIAGameWorks/kaolin/blob/master/.gitlab-ci.yml#L20
(you can also add in .drone.yml if the example doesn't involve a dataset)

The arguments used should test different branching (gpu and cpu if necessary) but make the test run as short as possible (smallest categories of the dataset, fewest numbers of epochs) would check that the example run (we don't verify final performance).

**Comment by shumash** [comment]
Closing old issue, no longer relevant to library.
