### ISSUE TITLE
DGCNN - Call contiguous() after permute() in pytorch model 

### ISSUE THREAD

**Issue by chrispduck** [NVIDIAGameWorks/kaolin#242]
Requires .contiguous() call after .permute() on line 176 as noted on the original implementation repo : [See link](https://github.com/WangYueFt/dgcnn/commit/98b744a7c37b1be928d0c5356a58d46bbe96ee7b?diff=unified
)

This causes cudnn issues on torch 1.4.0

On the kaolin repo:
https://github.com/NVIDIAGameWorks/kaolin/blob/be02fa3c621682da713e41426e65f63c7531a4ff/kaolin/models/dgcnn.py#L176

**Comment by pushkalkatara** [comment]
@chrispduck Yes, the author also recently made the change https://github.com/WangYueFt/dgcnn/commit/98b744a7c37b1be928d0c5356a58d46bbe96ee7b and quoted 
```
This avoids an error in some versions (e.g., 1.4) of PyTorch, and also brings sizable speed improvement.
```

**Comment by krrish94** [comment]
Good catch! @chrispduck or @pushkalkatara, would one of you like to submit a PR for this?

Contrib instructions: https://github.com/NVIDIAGameWorks/kaolin/blob/master/CONTRIBUTING.md

**Comment by chrispduck** [comment]
It looks as thought he DGCNN model is no longer in the repo
