### ISSUE TITLE
2D-3D-S Dataset

### ISSUE THREAD

**Issue by pushkalkatara** [NVIDIAGameWorks/kaolin#246]
Currently 2D-3D-S dataset is not part of kaolin.datasets. Would it be a useful addition?

http://buildingparser.stanford.edu/dataset.html#Download

**Comment by krrish94** [comment]
It'd certainly be useful. While don't have this in our current milestone, we'd be happy to merge if someone made a PR.

**Comment by pushkalkatara** [comment]
i would like to work on the issue @krrish94 , I think we can integrate the `S3DIS` dataset rather than the full 2D-3D-S dataset. 

Further when the DGCNN Semantic Segmentation model is added, we can create an example using the S3DIS dataset. Let me know your thoughts on this.

**Comment by krrish94** [comment]
That sounds good to me. You can proceed to work on this issue

**Comment by pushkalkatara** [comment]
Hi @krrish94 , please find minimal dataset loading here - https://github.com/pushkalkatara/kaolin/blob/s3dis/kaolin/datasets/s3dis.py

I had few doubts:
The structure of the dataset is as follows: 
Areas -> Rooms -> ObjectName.txt Annotations -> XYZRGB.
The annotations has XYZRGB format, in which XYZ is the pointcloud, RGB is the image. In the current implementation (focused to develop dataset for semantic segmentation), given a room id, it would load all objects in the room and return labels (object names) and point clouds. This is feeded as an input to a sem-seg model.

As it would be better to implement a generalized dataset rather than a specific task, it would be helpful if you could suggest the design pattern which I should follow for loading the dataset.

**Comment by AP-49** [comment]
> Currently 2D-3D-S dataset is not part of kaolin.datasets. Would it be a useful addition?
> 
> http://buildingparser.stanford.edu/dataset.html#Download

Hi! Unfortunately this link is not available anymore. Could you please let me know how I can download the S3DIS dataset?

**Comment by shumash** [comment]
Closing old issue.
