### ISSUE TITLE
ModelNet10 dataloader does not have argument `device`

### ISSUE THREAD

**Issue by pushkalkatara** [NVIDIAGameWorks/kaolin#249]
While running the pointcloud classification jupyter notebook:

```bash
TypeError                                 Traceback (most recent call last)
<ipython-input-19-7199a3a420c5> in <module>
      1 train_loader = DataLoader(
----> 2     ModelNet(modelnet_path, categories=categories, split='train', transform=transform, device=device),
      3     batch_size=12, shuffle=True
      4 )

~/kaolin/kaolin/datasets/base.py in __init__(self, preprocessing_transform, preprocessing_params, transform, no_progress, *args, **kwargs)
     89             no_progress (bool): disable tqdm progress bar for preprocessing.
     90         """
---> 91         self.initialize(*args, **kwargs)
     92         if preprocessing_transform is not None:
     93             desc = 'Applying preprocessing'

TypeError: initialize() got an unexpected keyword argument 'device
```

I think when the ModelNet dataset class was revised with base class Kaolin dataset, the device parameter was removed. Also, example would need this update.

**Comment by pushkalkatara** [comment]
We can resolve this issue i think in two ways, 

1. We can update [classification_engine](https://github.com/NVIDIAGameWorks/kaolin/blob/c3ec5484c326e83d6e1a9fdfd170b4c67343c68b/kaolin/engine/classification.py#L174) and add a condition that if device is specified, then load the data batch to specified CUDA device. Also, add `torch.set_default_tensor_type('torch.cuda.FloatTensor')` to use cuda tensors as default in order to make models free from device argument. i.e. models might have torch functions which require device parameter i.e. (https://github.com/pushkalkatara/kaolin/blob/907fd5bf34601ee767c070f45c410d1681dc8a49/kaolin/models/dgcnn.py#L111). If device is not specified it takes default `cpu` which can cause errors.

 I have made a branch for this change - https://github.com/pushkalkatara/kaolin/commit/e69b6ca816f4ed7326bcce63eff301b45c9cad57


2. Another way, we can have argument `device` in each dataset, model, engine classes. 

@krrish94 please let me know your thoughts on this.

**Comment by krrish94** [comment]
You're right, this issue is due to a recent refactor of the dataset classes. You wouldn't need the `device` argument any longer.

I'd recommend against adding a default tensor type. In Kaolin, we usually infer tensor types and devices based on the other tensors in context.

**Comment by Caenorst** [comment]
I recommend following the .py, we recently fixed it to follow our new datasets, but we still need to modify the jupyter notebook

**Comment by krrish94** [comment]
@pushkalkatara this is the example @Caenorst is referring to https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/Classification/pointcloud_classification.py

**Comment by pushkalkatara** [comment]
Thanks for pointing me to the example.

**Comment by pushkalkatara** [comment]
The example doesn't use the `ClassificationEngine` as base class. https://github.com/NVIDIAGameWorks/kaolin/blob/c3ec5484c326e83d6e1a9fdfd170b4c67343c68b/examples/Classification/pointcloud_classification.py#L55

created same as the PointNet PC classification example - https://github.com/pushkalkatara/kaolin/blob/dgcnn-seg/examples/Classification/point_cloud_classification.ipynb
