### ISSUE TITLE
AttributeError: module 'kaolin' has no attribute 'dataloader'

### ISSUE THREAD

**Issue by nikepupu** [NVIDIAGameWorks/kaolin#25]
I am trying to run eval.py for pixel2Mesh . Somehow I got this error.

OS: Ubuntu 18.04
Python: 3.6.9
Cuda: 10.1
pytorch: 1.3.1

**Comment by ujjawalcse** [comment]
I'm also facing the same error while running Pixel2Mesh example: $python eval.py - 
Traceback (most recent call last):
  File "eval.py", line 41, in <module>
    points_set_valid = kal.dataloader.ShapeNet.Points(root ='../../datasets/',categories =args.categories , \
AttributeError: module 'kaolin' has no attribute 'dataloader'

Have you solved @nikepupu?
Please guide @heronog  @ViktorM  @keithroe  @moconnor725 @dmitryduka

**Comment by ZiyunClaudeWang** [comment]
The code has been changed such that kal.dataloader.ShapeNet.Points becomes kal.datasets.shapenet.ShapeNet_Points

**Comment by ujjawalcse** [comment]
Thank you very much @ZiyunClaudeWang.

**Comment by deepali-c** [comment]
This similar issue is seen while executing the `ODM_ModelNet` and `voxel-ModelNet` examples:

```
$ python train_Direct.py

Traceback (most recent call last):
  File "train_Direct.py", line 57, in <module>
    download = True)
  File "<mydir>/kaolin/examples/SuperResolution/ODM-ModelNet/dataloaders.py", line 55, in __init__
    voxel_set = kal.dataloader.ModelNet( root, train=train, download=download, categories=categories, single_view=single_view)
AttributeError: module 'kaolin' has no attribute 'dataloader'
```

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates.

Closing the bug as it is no longer relevant to this repo.
