### ISSUE TITLE
TranslatePointCloud transform

### ISSUE THREAD

**Issue by pushkalkatara** [NVIDIAGameWorks/kaolin#250]
Adding a new transform function in kaolin.Transform : translatePointCloud.

In dgcnn, author have used it as a preprocessing function: https://github.com/WangYueFt/dgcnn/blob/20fdb459ca5d10fe8aba1d296e66340f65990b85/pytorch/data.py#L50

**Comment by pushkalkatara** [comment]
The preprocessing function is 
```
(pc + xyz1) * xyz2
```

The mulitplication operation on pointcloud can be performed through https://github.com/NVIDIAGameWorks/kaolin/blob/c3ec5484c326e83d6e1a9fdfd170b4c67343c68b/kaolin/transforms/transforms.py#L201
but the addition operation is missing. Adding translate as a transform function might be useful

**Comment by krrish94** [comment]
Thanks for opening this issue! This would be a nice addition, and relatively simple to implement.

**Comment by SomTambe** [comment]
Can I work on this issue ? This seems interesting to implement 😀

**Comment by SomTambe** [comment]
I aim to do this by the following-
- Add a translate function to kaolin.transforms.pointcloudfunc
- Add the translatePointCloud  transform to kaolin.transforms.transforms, by making use of ScalePointCloud transforms also.

Could you assign this to me ?

**Comment by shumash** [comment]
Closing old issue, as it is no longer relevant to the library.
