### ISSUE TITLE
Generate tarball release?

### ISSUE THREAD

**Issue by rluria14** [NVIDIAGameWorks/kaolin#251]
There are no tarball files released for this package here on GitHub. The pypi release (https://pypi.org/project/kaolin/) does not seem to contain the proper files needed to build. Is it possible to generate/compile one either here or on pypi. Working on building this for conda-forge.

**Comment by Caenorst** [comment]
Hi @rluria14 !

Thank you for your interest in Kaolin, we are currently working toward a release, there is a feature in github that allows you to "watch for release" so you will be notified when it's up :)

**Comment by rluria14** [comment]
@Caenorst thanks!
