### ISSUE TITLE
How to transform a Mesh to TriangleMesh in kaolin

### ISSUE THREAD

**Issue by BrandoZhang** [NVIDIAGameWorks/kaolin#256]
Hi, thanks for your great work!
I am wondering how to save a mesh to a obj file.
Specifically, I want to load a cube and sample 2562 vertices on it, and then export to another file, given "cube.obj", I tried:

```python
import kaolin as kal

kaolin_cube = kal.rep.TriangleMesh.from_obj('cube.obj')
sampler = kal.transforms.SampleTriangleMesh(num_samples=2562)
k_cube = sampler(kaolin_cube)
k_cube_m_t = kal.conversions.pointcloudconversions.pointcloud_to_trianglemesh(k_cube)
k_cube_m = kal.rep.Mesh.from_tensors(vertices=k_cube_m_t[0], faces=k_cube_m_t[1])
k_cube_m.save_mesh("cube2562.obj")
```

And I got error:
```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-56-bd52cf58c5ca> in <module>
----> 1 k_cube_m.save_mesh("cube2562.obj")

AttributeError: 'Mesh' object has no attribute 'save_mesh'
```

I check the doc, it seems like there is no method to convert a `Mesh` to `TriangleMesh`, right? Then, how can I export this result?

**Comment by Caenorst** [comment]
You can do:
```
k_cube_m = kal.rep.TriangleMesh.from_tensors(vertices=k_cube_m_t[0], faces=k_cube_m_t[1])
```

**Comment by BrandoZhang** [comment]
Can I save a point cloud? I found that after `pointcloud_to_trianglemesh`, the number of vertices reduces from `2562` to `1608`. I want to preserve the number of vertices after remeshing.

**Comment by Caenorst** [comment]
Yes you can directly use `torch.save` to save a point cloud.
For your second question our current conversion doesn't allow that, feel free to suggest / add one :)
