### ISSUE TITLE
Mesh to Points to Mesh error on reconstruction

### ISSUE THREAD

**Issue by dhrosquete** [NVIDIAGameWorks/kaolin#257]
Hi!

I want to reconstruct the mesh after transforming it to points with the following routine.

```
mesh = kal.rep.TriangleMesh.from_obj(model_path)
points, _  = kal.conversions.trianglemesh_to_pointcloud(mesh, 1000)
mesh2 = kal.conversions.pointcloud_to_trianglemesh(points)
```
On the 3rd line, there is the following error:` "ValueError: Surface level must be within volume data range."`

I must say that I checked using kal.visualize.show(mesh) and is working perfectly, but the point cloud is not displaying, I've tried with show(points, mode='points) and with show_pointcloud(points) and is not working either.

Thank you so much!

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
https://kaolin.readthedocs.io/en/latest/

Closing the bug as it is no longer relevant to this repo.
