### ISSUE TITLE
rendering multiple textured meshes in single scene

### ISSUE THREAD

**Issue by alex-helm** [NVIDIAGameWorks/kaolin#267]
Hi! Sorry for the basic question. I'm attempting to render one image of a scene with several meshes that each have a different image texture. I haven't been able to figure out how to do this with the DIB-R or NMR. Is this functionality built in and if so could you please point me to the documentation for it and/or examples. Thank you so much!

**Comment by Caenorst** [comment]
Hi @alex-helm batching is an incoming feature (watch for release ! :D), meanwhile here is a little tips for you:
you can concatenate `vertices` of multiple meshes on the dim=0, offset the indices stored inside `faces` (using the cumulative sum of the number of vertices of previous meshes) and concatenated them on dim=0.

**Comment by zoezhou1999** [comment]
Hi @Caenorst where are the batching features in 2022? 😊 for the solution mentioned here, how to deal with multiple meshes with multiple texture maps..? Thank you!

**Comment by Caenorst** [comment]
Hi @zoezhou1999 , there are some batching features in Kaolin (most ops in mesh are batched by default). for the rendering with multiple texture maps is depend on the size of those texture maps, you can see the approach taken in our [camera and rasterization tutorial](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/camera_and_rasterization.ipynb)

**Comment by shumash** [comment]
This is an old issue, but we are able to offer a solution now. 

1. Import your meshes into a `SurfaceMesh` representation using `kaolin.io.import_mesh`, which supports `obj`, `usd`, and `gltf/glb`
2. Use [SurfaceMesh.flatten](https://kaolin.readthedocs.io/en/latest/modules/kaolin.rep.surface_mesh.html#kaolin.rep.SurfaceMesh.flatten) method to turn your list of meshes into a single mesh. 
3. Finally, run newly added [kaolin.render.easy_render.render_mesh](https://kaolin.readthedocs.io/en/latest/modules/kaolin.render.easy_render.mesh.html#kaolin.render.easy_render.mesh.render_mesh) on your flattended to get image (with spherical guassians lighting) and your chosen back end (dib-r or nvdiffrast), also obtaining channels like normals and albedo. 

The wheels for this functionality are coming with the next release (please subscribe to repo), or you can build from source today ([instructions](https://kaolin.readthedocs.io/en/latest/notes/installation.html#installation-from-source)). 
Try out [Mesh Easy Render Tutorial](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/easy_mesh_render.ipynb) to get started.

**Comment by Learningm** [comment]
> This is an old issue, but we are able to offer a solution now.
> 
> 1. Import your meshes into a `SurfaceMesh` representation using `kaolin.io.import_mesh`, which supports `obj`, `usd`, and `gltf/glb`
> 2. Use [SurfaceMesh.flatten](https://kaolin.readthedocs.io/en/latest/modules/kaolin.rep.surface_mesh.html#kaolin.rep.SurfaceMesh.flatten) method to turn your list of meshes into a single mesh.
> 3. Finally, run newly added [kaolin.render.easy_render.render_mesh](https://kaolin.readthedocs.io/en/latest/modules/kaolin.render.easy_render.mesh.html#kaolin.render.easy_render.mesh.render_mesh) on your flattended to get image (with spherical guassians lighting) and your chosen back end (dib-r or nvdiffrast), also obtaining channels like normals and albedo.
> 
> The wheels for this functionality are coming with the next release (please subscribe to repo), or you can build from source today ([instructions](https://kaolin.readthedocs.io/en/latest/notes/installation.html#installation-from-source)). Try out [Mesh Easy Render Tutorial](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/easy_mesh_render.ipynb) to get started.

Hi，@shumash, I encountered some errors following the method mentioned aboved.
I load a glb model, and this glb model has several meshes and multiple uvs & materials.
I use [SurfaceMesh.flatten] to get a whole mesh and use [kaolin.render.easy_render.render_mesh] to render. The rendering albedo is different from the visulization in Blender.
I found out the reason is that [SurfaceMesh.flatten] just concat the mesh.uvs, how can the uvs make correct corresponding mapping on multiple uv map during render time?
