### ISSUE TITLE
ModuleNotFoundError: No module named 'kaolin.nnsearch'

### ISSUE THREAD

**Issue by prateep03** [NVIDIAGameWorks/kaolin#27]
Hi,

 I am unable to compile on Linux. Please help.

OS: Debian 9
Python: 3.6.9
Cuda: 10.0
pytorch: 1.3.1

**Comment by OldConcept** [comment]
I had the same problem on Win10
![Z (@5W)Z )E_TGX4@WRR624](https://user-images.githubusercontent.com/46376624/69231649-67220600-0bc4-11ea-87c0-42543ec0569f.png)

**Comment by krrish94** [comment]
Need to step outside of the `kaolin` base directory when running this.

https://github.com/NVIDIAGameWorks/kaolin/issues/3#issue-523193927
