### ISSUE TITLE
Point metrics Reference Issue

### ISSUE THREAD

**Issue by evinpinar** [NVIDIAGameWorks/kaolin#270]
There is a weird behavior when using `metrics.point.chamfer_distance` and `metrics.point.f_score`. When they used subsequently, it seems they modify the input points and the answers change. One should only use them as a metric and by cloning the point object. It needs to be fixed for usage as a loss.

**Comment by JerryJiehanWang** [comment]
Hi @evinpinar ,
Could you give me the scripts that you run these two functions on?

**Comment by evinpinar** [comment]
Not very specific scripts, I run them on some input that I generate from real point cloud data.

**Comment by shumash** [comment]
Closing old issue.

If you run into issues with [new versions](https://kaolin.readthedocs.io/en/latest/modules/kaolin.metrics.pointcloud.html) of chamfer distance and f_score, please do post a new issue.
