### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by juleslambert345** [NVIDIAGameWorks/kaolin#275]
Hi, 

I have an error while installing kaolin(python setup.py install). I am on windows 10 and the error message is 

kaolin/graphics/nmr/cuda/rasterize_cuda_kernel.cu(33): error: function "atomicAdd(double *, double)" has already been defined

1 error detected in the compilation of "C:/Users/user/AppData/Local/Temp/tmpxft_0000c444_00000000-8_rasterize_cuda_kernel.cpp4.ii".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2\\bin\\nvcc.exe' failed with exit status 2

**Comment by juleslambert345** [comment]
Thank you, now it's work with the fix.

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation.

Closing the bug as it is no longer relevant to this repo.
