### ISSUE TITLE
Partial representations from meshes or point clouds

### ISSUE THREAD

**Issue by fbottarel** [NVIDIAGameWorks/kaolin#276]
Hello everyone,

I am trying to implement a shape completion encoder-decoder with Kaolin. Since the premise of shape completion is to have as input an incomplete point cloud, mesh or voxel grid, I wonder if there if I could adapt any of the existing `kaolin.transforms` to obtain this or I need to implement it from the ground up.

The idea is to be able to load examples from ModelNet or ShapeNet as partial representations in order to use them as input to the encoder.

**Comment by shumash** [comment]
Closing an old issue, as it's no longer relevant to the library.
