### ISSUE TITLE
SHREC dataset

### ISSUE THREAD

**Issue by mattans** [NVIDIAGameWorks/kaolin#277]
The class SHREC16 expected folder hierarchy of ./train/{class name} and ./test/{class name}.
However when downloading from the SHREC16 website there is no such organization. All files are scattered, and there's a CSV file that links a mesh file name to its class.
Where can we download the dataset in the format that is needed to the SHREC16 class?

**Comment by amirbarda** [comment]
I Also have this problem. Would be nice to get a response...

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

We are [currently working on putting back the SHREC16 dataset](https://github.com/NVIDIAGameWorks/kaolin/pull/375), it seems that the one we are using has a different structure, we will be exploring that.

**Comment by JerryJiehanWang** [comment]
Hi @mattans @amir90, where do you download the SHREC16 dataset? I'm using this link: http://shapenet.cs.stanford.edu/shrec16/ Are you using the same one?

**Comment by shumash** [comment]
Closing old issue. Please open new issue if running into trouble with[ latest library version](https://kaolin.readthedocs.io/en/latest/modules/kaolin.io.shrec.html).
