### ISSUE TITLE
Python3 pptk not found

### ISSUE THREAD

**Issue by kaanaksit** [NVIDIAGameWorks/kaolin#280]
Post installation, I ended up with ` No module named 'pptk'` error. I tried to install it with `pip3 install pptk`, however no matchin distribution found for `pptk` in pip3. I see in github page for `pptk`, there is a Python 2 version. There seems to be no Python 3 version:

[https://github.com/heremaps/pptk/issues/39](url)

Please advise.

```
In [2]: import kaolin as kal                                                                             
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-679789fed074> in <module>
----> 1 import kaolin as kal

<frozen zipimport> in load_module(self, fullname)

/usr/local/lib/python3.8/dist-packages/kaolin-0.1.0-py3.8-linux-x86_64.egg/kaolin/__init__.py in <module>
     22 from kaolin import rep
     23 from kaolin import vision
---> 24 from kaolin import visualize
     25 from kaolin import metrics
     26 from kaolin import models

<frozen zipimport> in load_module(self, fullname)

/usr/local/lib/python3.8/dist-packages/kaolin-0.1.0-py3.8-linux-x86_64.egg/kaolin/visualize/__init__.py in <module>
----> 1 from .vis import *

<frozen zipimport> in load_module(self, fullname)

/usr/local/lib/python3.8/dist-packages/kaolin-0.1.0-py3.8-linux-x86_64.egg/kaolin/visualize/vis.py in <module>
     20 import kaolin
     21 import kaolin as kal
---> 22 import pptk
     23 
     24 

ModuleNotFoundError: No module named 'pptk'
```

**Comment by Caenorst** [comment]
what is your `pip` version ? Also Kaolin support 3.6.

I tried with pip==20.1.1 and python==3.6 and pip install pptk worked

**Comment by kaanaksit** [comment]
I was using pip `20.0.2` with python `3.8.2`. I have just upgraded to pip `20.1.1`. Again no matching distribution found for pptk.

**Comment by mattans** [comment]
> I was using pip `20.0.2` with python `3.8.2`. I have just upgraded to pip `20.1.1`. Again no matching distribution found for pptk.

Probably pptk did not release a package to Python 3.8 yet

**Comment by Siddhant-K-code** [comment]
@kunguz Try Python 3.7, it is best for all type of packages, it is very stable also.

Try : 

`pip install pptk`

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

We are not relying on pptk anymore for visualization, please check our custom visualizer the [Omniverse Kaolin App](https://kaolin.readthedocs.io/en/latest/notes/checkpoints.html#visualizing-with-kaolin-omniverse-app) and [Dash3D](https://kaolin.readthedocs.io/en/latest/notes/checkpoints.html#visualizing-with-kaolin-dash3d)!

Closing the bug as it is no longer relevant to this repo.
