### ISSUE TITLE
AttributeError: module 'kaolin.datasets' has no attribute 'ModelNetVoxels'

### ISSUE THREAD

**Issue by adityavadalkar** [NVIDIAGameWorks/kaolin#281]
I'm trying to run the 3DGAN model by running 
`python train.py --modelnet-root <path/to/modelnet-root>`
I'm getting the attribute error. If it is not available is there an updated code? I'm working on Windows 10 and I have created the environment as per the readme.

```
Traceback (most recent call last):
  File "train.py", line 45, in <module>
    train_set = kal.datasets.ModelNetVoxels(basedir=args.modelnet_root, cache_dir=args.cache_dir,
AttributeError: module 'kaolin.datasets' has no attribute 'ModelNetVoxels'
```

**Comment by javi-99** [comment]
Yes I am also facing the same error. I am using ubuntu 18.04. Plz help.

**Comment by adityavadalkar** [comment]
> Yes I am also facing the same error. I am using ubuntu 18.04. Plz help.

I solved this error by replacing 
`train_set = kal.datasets.ModelNetVoxels(basedir=args.modelnet_root, cache_dir=args.cache_dir,`
with
`train_set = kal.datasets.ModelNet(root=args.modelnet_root)`

I'm not sure if this is the right way, but that error isn't occurring now.

**Comment by javi-99** [comment]
Are you feeding the same ModelNet10 dataset as used in the point cloud classification example?
I am using the ModelNet10 dataset and after replacing ModelNetVoxels with ModelNet I am facing another error.
TypeError: initialize() got an unexpected keyword argument 'basedir'

**Comment by adityavadalkar** [comment]
> Are you feeding the same ModelNet10 dataset as used in the point cloud classification example?
> I am using the ModelNet10 dataset and after replacing ModelNetVoxels with ModelNet I am facing another error.
> TypeError: initialize() got an unexpected keyword argument 'basedir'

The ModelNet function only has the root argument according to the modelnet.py file. I have given the example above.

**Comment by javi-99** [comment]
Yes, I see, I changed 'basedir' with 'root' then 'cache_dir' does not exist, it means ModelNetVoxels is a separate function which is not present here.

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates.

Closing the bug as it is no longer relevant to this repo.
