### ISSUE TITLE
The directory to run the command could not be found

### ISSUE THREAD

**Issue by DingLe139** [NVIDIAGameWorks/kaolin#282]
Hello, I'm very sorry to disturb you with this question. I'm a beginner. I don't know which root directory contains readme, that is, I can't find a suitable directory to run: Python setup.py Install. After searching many folders, I still can't find it. So can I ask you about this problem? Thank you

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

I would suggest to follow our documentation here: https://kaolin.readthedocs.io/en/latest/notes/installation.html
