### ISSUE TITLE
Size error when using laplacian_loss

### ISSUE THREAD

**Issue by bharadwajdhornala** [NVIDIAGameWorks/kaolin#284]
Hi, @jasongorski @heronog @ViktorM @keithroe @moconnor725 
I am calculating laplacian_loss for two meshs. I get error in matching tensor sizes.

Code:
import kaolin as kal
mesh = kal.rep.TriangleMesh.from_obj(filename)
mesh1 = kal.rep.TriangleMesh.from_obj(filename1)
lap = kal.metrics.mesh.laplacain_loss(mesh,mesh1)

Error:
RuntimeError: The size of tensor a (65804) must match the size of tensor b (89408) at non-singleton dimension 0

Any suggestions will be helpful.

**Comment by Caenorst** [comment]
Please return the full error logs with the traceback.

I'm guessing that your two mesh have different number of vertices, I don't think laplacian loss would make sense in this context ?

**Comment by bharadwajdhornala** [comment]
Can you give a more detail about laplacian loss for two meshs
