### ISSUE TITLE
DGCNN Semantic Segmentation

### ISSUE THREAD

**Issue by jonhejde** [NVIDIAGameWorks/kaolin#29]
Will you implement the DGCNN semantic segmentation model? Currently, it seems that the classification model is implemented.

**Comment by pushkalkatara** [comment]
I think part/semantic segmentation, both of these models (https://arxiv.org/pdf/1801.07829.pdf) are not implemented. @krrish94 Are these models required to be implemented in kaolin? If yes, can i work on the issue?

**Comment by krrish94** [comment]
@pushkalkatara Yeah, it'll be great if you can take this up!

**Comment by pushkalkatara** [comment]
Thanks. I'll start working on it.

**Comment by krrish94** [comment]
Great, looking forward to your PR! If you need anything, feel free to reach out on this thread.

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates.

Closing the bug as it is no longer relevant to this repo.
