### ISSUE TITLE
Error in the Kaolin Pixel2Mesh example

### ISSUE THREAD

**Issue by RyanStark223232** [NVIDIAGameWorks/kaolin#290]
Traceback (most recent call last):
  File "shapenet_test.py", line 78, in <module>
    projected_image_features = pooling(img_features, pool_indices)
  File "/mnt/c/Users/wongh/.spyder-py3/Pixel2Mesh/utils.py", line 110, in pooling
    C =torch.index_select(block, 1, x1s).view(block.shape[0], -1 )
IndexError: index out of range in self

I got the above error when running train.py in the example of Pixel2Mesh. I changed some of the code regarding shapenet data loading, but the graph convolution part should be unchanged. Thank you for your patience

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates.

Closing the bug as it is no longer relevant to this repo.
