### ISSUE TITLE
MeshCNN example not working

### ISSUE THREAD

**Issue by CallumMcMahon** [NVIDIAGameWorks/kaolin#295]
I can't seem to run the MeshCNN example `mesh_classification`. 

Using the original code, the error `Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same` occurs, which seems to be fixed by adding .to("cuda") to the mesh features argument to the model.

Another error then occurs, `Expected object of backend CUDA but got backend CPU for sequence element 1 in sequence argument at position #1 'tensors'`. That seems to be taken care of by modifying `padded_gemm = mesh.gemm_edges.clone().float().to(device)` in the pad_gemm function. 

The pooling operation does not appear to work, raising a `ValueError: list.remove(x): x not in list` after a few edges have been removed. Removing pooling does allow training to occur however, not producing any more errors.

The example also uses nll loss when cross entropy seems more appropriate. 

Also, is this implementation supposed to be quicker then the original meshCNN implementation? Currently with my hardware, on shrec16 with all classes and batch size 16, this code runs in about 100 seconds vs around 30 seconds in the original implementation. I would love for this implementation to work as the code is formatted in a much simpler and more standard format than the meshCNN repo.

I am happy to help if needed.

**Comment by Caenorst** [comment]
Hi @CallumMcMahon , thank you for you interest in Kaolin.

We are currently in a way for a reformat of Kaolin, which include fixing and optimizing MeshCNN.
We will keep you updated :)

**Comment by CallumMcMahon** [comment]
Thanks for the quick reply @Caenorst :) I was hoping to use kaolin for my master's project which is only over summer. Do you expect an update to come out in the next week or two? Otherwise is there a preview build available with the latest fixes/optimisation before an official update comes out?

Thanks again

**Comment by Caenorst** [comment]
I would doubt the update will be ready by next week, we will try to present the reformat as a branch to the public ASAP

**Comment by JoeLambourne** [comment]
Hello kaolin authors,

Is there any plan to add the segmentation task to your MeshCNN implementation.  I see the MeshCNNClassifier but not any way to run the segmentation.  Thank you for your help

**Comment by siyuan2018** [comment]
> I can't seem to run the MeshCNN example `mesh_classification`.
> 
> Using the original code, the error `Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same` occurs, which seems to be fixed by adding .to("cuda") to the mesh features argument to the model.
> 
> Another error then occurs, `Expected object of backend CUDA but got backend CPU for sequence element 1 in sequence argument at position #1 'tensors'`. That seems to be taken care of by modifying `padded_gemm = mesh.gemm_edges.clone().float().to(device)` in the pad_gemm function.
> 
> The pooling operation does not appear to work, raising a `ValueError: list.remove(x): x not in list` after a few edges have been removed. Removing pooling does allow training to occur however, not producing any more errors.
> 
> The example also uses nll loss when cross entropy seems more appropriate.
> 
> Also, is this implementation supposed to be quicker then the original meshCNN implementation? Currently with my hardware, on shrec16 with all classes and batch size 16, this code runs in about 100 seconds vs around 30 seconds in the original implementation. I would love for this implementation to work as the code is formatted in a much simpler and more standard format than the meshCNN repo.
> 
> I am happy to help if needed.

I have the same issue. I tried to convert each element in mesh to tensor, so that it is possible to put them on GPU. However, I found mesh.ve is difficult to convert to tensor directly.

**Comment by ishanb97** [comment]
did anyone resolve this

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
https://kaolin.readthedocs.io/en/latest/

We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates.

Closing the bug as it is no longer relevant to this repo.
