### ISSUE TITLE
No module named 'kaolin.nnsearch'

### ISSUE THREAD

**Issue by aradhyamathur** [NVIDIAGameWorks/kaolin#3]
After installation the import gives the following error,  please guide.
 `import kaolin as kal `

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-679789fed074> in <module>
----> 1 import kaolin as kal

~/soft/kaolin/kaolin/__init__.py in <module>
     15 from .version import __version__
     16 
---> 17 from kaolin import conversions
     18 from kaolin import datasets
     19 from kaolin import graphics

~/soft/kaolin/kaolin/conversions/__init__.py in <module>
----> 1 from kaolin.conversions.meshconversions import *
      2 from kaolin.conversions.pointcloudconversions import *
      3 from kaolin.conversions.sdfconversions import *
      4 from kaolin.conversions.voxelgridconversions import *

~/soft/kaolin/kaolin/conversions/meshconversions.py in <module>
     20 
     21 import kaolin as kal
---> 22 from kaolin.metrics.point import directed_distance as directed_distance
     23 
     24 

~/soft/kaolin/kaolin/metrics/__init__.py in <module>
      1 from .voxel import *
----> 2 from .point import *
      3 from .mesh import *

~/soft/kaolin/kaolin/metrics/point.py in <module>
     14 
     15 import torch
---> 16 from kaolin.nnsearch import nnsearch
     17 import kaolin.cuda.sided_distance as sd
     18 from scipy.spatial import cKDTree as Tree

ModuleNotFoundError: No module named 'kaolin.nnsearch'

`

**Comment by aradhyamathur** [comment]
The issue was  at my end. The path was incorrect perhaps i did not notice.

**Comment by ToniRV** [comment]
I have the same error though:     
```
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kaolin as kal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tonirv/Documents/Research/Papers/2020c-CVPR-MeshingAllTheWay/code/kaolin/kaolin/__init__.py", line 17, in <module>
    from kaolin import conversions
  File "/home/tonirv/Documents/Research/Papers/2020c-CVPR-MeshingAllTheWay/code/kaolin/kaolin/conversions/__init__.py", line 1, in <module>
    from kaolin.conversions.meshconversions import *
  File "/home/tonirv/Documents/Research/Papers/2020c-CVPR-MeshingAllTheWay/code/kaolin/kaolin/conversions/meshconversions.py", line 22, in <module>
    from kaolin.metrics.point import directed_distance as directed_distance
  File "/home/tonirv/Documents/Research/Papers/2020c-CVPR-MeshingAllTheWay/code/kaolin/kaolin/metrics/__init__.py", line 2, in <module>
    from .point import *
  File "/home/tonirv/Documents/Research/Papers/2020c-CVPR-MeshingAllTheWay/code/kaolin/kaolin/metrics/point.py", line 16, in <module>
    from kaolin.nnsearch import nnsearch
ModuleNotFoundError: No module named 'kaolin.nnsearch'
```

**Comment by aradhyamathur** [comment]
Hi. Did you check the path when you launched the interpreter? The issue I was facing was that I was trying to import while still in the same directory as the repo.

**Comment by phongnhhn92** [comment]
Yeah I think we should add a line in the README that we should test kaolin outside of installation directory :dango:

**Comment by hungsing92** [comment]
source setenv.sh
