### ISSUE TITLE
importerror  undefined symbol: _ZN3c1011CPUTensorIdEv  

### ISSUE THREAD

**Issue by kobeyuan** [NVIDIAGameWorks/kaolin#30]
env: pytorch 1.3.1 , cuda 10.1 ,python 3.6.9. ubuntu-18.04, gpu: GTX 960M, driver version 435.

during import kaolin, report the import error as follows. 
builtins.ImportError: /home/xxx/.cache/Python-Eggs/kaolin-0.2.0+ed13273-py3.6-linux-x86_64.egg-tmp/kaolin/cuda/sided_distance.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1011CPUTensorIdEv

anyone in this problem?  how to solve it.

**Comment by lei1993** [comment]
have you solved it?

**Comment by krrish94** [comment]
Can you confirm that your `torch.cuda.is_available()` returns `True`?

**Comment by lei1993** [comment]
> Can you confirm that your `torch.cuda.is_available()` returns `True`?

I solved it by reinstall torch using pip

**Comment by krrish94** [comment]
This is an issue of the pytorch installation not being able to find/link to CUDA shared libraries.
Also see: https://github.com/open-mmlab/mmdetection/issues/592

**Comment by kobeyuan** [comment]
> 
> 
> Can you confirm that your `torch.cuda.is_available()` returns `True`?

Yes

**Comment by kobeyuan** [comment]
> 
> 
> This is an issue of the pytorch installation not being able to find/link to CUDA shared libraries.
> Also see: [open-mmlab/mmdetection#592](https://github.com/open-mmlab/mmdetection/issues/592)

thanks, I check it again.

**Comment by kobeyuan** [comment]
> 
> 
> have you solved it?

No.  I will try it using  the comments ways.

**Comment by Ax-For** [comment]
I met it, too

**Comment by kobeyuan** [comment]
> 
> 
> have you solved it?

yes, reinstall it on ubuntu16.4, cuda9.2, cudnn7, python3.6.9.

**Comment by muhammad-faizan-122** [comment]
will it be work without on CPU? because I am running on CPU facing a following issue
`ImportError: /home/X/miniconda3/envs/denoise/lib/python3.8/site-packages/kaolin/_C.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormat`

**Comment by samiede** [comment]
I still have the same problem, Python 3.7.16, CUDA Version: 11.7, torch 1.12.1., has anyone found a solution to this?
