### ISSUE TITLE
NMR's default fov? 

### ISSUE THREAD

**Issue by LeoZDong** [NVIDIAGameWorks/kaolin#304]
I'm trying to render a depth map using `NeuralMeshRenderer`. What is the default field of view angle for this operation? I don't fully understand this, but it seems like I only need to provide the camera intrinsics matrix `K` when I'm using "perspective" mode. Why is it not need it for "look_at" mode, which is what I use to render the depth map?

Thanks a lot!

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
https://kaolin.readthedocs.io/en/latest/

We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates.

Closing the bug as it is no longer relevant to this repo.
