### ISSUE TITLE
Qusetion about spherical harmonic parameters of DIB-R

### ISSUE THREAD

**Issue by zomkey** [NVIDIAGameWorks/kaolin#306]
Hi，thanks for your work!
When I use DIB-R algorithm to render, I found the spherical harmonic parameters is differenet from original paper （https://cseweb.ucsd.edu/~ravir/papers/envmap/envmap.pdf  ). I want to ask whether it is better to change the spherical harmonic parameters as DIB-R/frag_shtex.py, and does this change get better lighting result?
* Original define: 
![image](https://user-images.githubusercontent.com/23496247/91142542-874a9c80-e6e3-11ea-93e2-8f8e1551bbf0.png)

* DIB-R define: 
![image](https://user-images.githubusercontent.com/23496247/91142493-713cdc00-e6e3-11ea-9768-b908b677f244.png)

**Comment by shumash** [comment]
Sorry this was never addressed. Closing old bug, no longer relevant to the library. 

Check out new differentiable lighting additions in these tutorials:

- [examples/tutorial/diffuse_lighting.ipynb](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/diffuse_lighting.ipynb)
- [examples/tutorial/sg_specular_lighting.ipynb](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/sg_specular_lighting.ipynb)

You might also be interested in a general differentiable shader using Spherical Gaussian lighting: 
- [examples/tutorial/easy_mesh_render.ipynb](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/easy_mesh_render.ipynb)
