### ISSUE TITLE
Failed installation  due to gcc ?

### ISSUE THREAD

**Issue by zyz-notebooks** [NVIDIAGameWorks/kaolin#307]
Hi there,

I followed the instructions to install kaolin. However, the error shows below

/usr/include/c++/7/bits/basic_string.h:6693:95:   required from here
/usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’ without object
error: command '/usr/local/cuda-10.1/bin/nvcc' failed with exit status 1

Thanks!

**Comment by zyz-1998** [comment]
Supplement: My environment
numpy       1.17.0
olefile     0.46
Pillow      7.2.0
pip         20.1.1
setuptools  49.1.0.post20200704
six         1.15.0
torch       1.5.0
torchvision 0.6.0a0+82fd1c8

gcc 7.5

**Comment by 96wangfeng** [comment]
> Hi there,
> 
> I followed the instructions to install kaolin. However, the error shows below
> 
> /usr/include/c++/7/bits/basic_string.h:6693:95: required from here
> /usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’ without object
> error: command '/usr/local/cuda-10.1/bin/nvcc' failed with exit status 1
> 
> Thanks!

Hi, how do you solve this problem? I have the same problem with you.

**Comment by stefanopini** [comment]
I experienced the same issue. It seems to be related to an old version of CUDA 10.1 when used with gcc >= 7
https://forums.developer.nvidia.com/t/cuda-10-1-nvidia-youre-now-fixing-gcc-bugs-that-gcc-doesnt-even-have/71063

Updating to CUDA 10.2 fixed it. CUDA 10.1.168 should work as well.

**Comment by Janus-Shiau** [comment]
Same issue occurs in CUDA 10.1.105, fixed after upgrade to 10.1.168.
