### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_75'

### ISSUE THREAD

**Issue by polarisZhao** [NVIDIAGameWorks/kaolin#31]
when I use: `python3 setup.py install `, have a problem, what should I do 
```
/usr/bin/nvcc -I/home/zhaozhichao/.local/lib/python3.6/site-packages/torch/include -I/home/zhaozhichao/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/zhaozhichao/.local/lib/python3.6/site-packages/torch/include/TH -I/home/zhaozhichao/.local/lib/python3.6/site-packages/torch/include/THC -I/usr/include/python3.6m -c kaolin/cuda/furthest_point_sampling_cuda.cu -o build/temp.linux-x86_64-3.6/kaolin/cuda/furthest_point_sampling_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=furthest_point_sampling -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++11
nvcc fatal   : Unsupported gpu architecture 'compute_75'
error: command '/usr/bin/nvcc' failed with exit status 1
```
**Env:**
**System:** ubuntu 18.04
**CUDA Version** 10.0.130
**cudnn:** 7.5.0
**nvcc:**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85

**Comment by Jean-Francois-Lafleche** [comment]
Thank you for providing so much detail. Could you please also provide the GPU model you are using?

**Comment by polarisZhao** [comment]
GPU is RTX 2080Ti

add:
```
extra_compile_args={
                'nvcc':['--gpu-architecture=compute_70','--gpu-code=sm_70']
            }),
```
to cuda CUDAExtension can solve it.

**Comment by krrish94** [comment]
@polarisZhao Can you confirm that the issue is resolved?

**Comment by polarisZhao** [comment]
It works on my GPU: RTX 2080Ti, all code I add:
```
extra_compile_args={
        'cxx': ['-O2',],
        'nvcc':['--gpu-architecture=compute_70','--gpu-code=sm_70','-O3','-I./cutlass/','-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__']
}
```
I am not sure it works on other GPU.

**Comment by jiaxinxie97** [comment]
@polarisZhao  I want to ask where you add the extra_compile_args, there are 9 CUDAExtension in setup.py. You add extra_compile_args to them all?

**Comment by VictorZuanazzi** [comment]
For the cuda noobies, where exactly should I add this?

`extra_compile_args={
        'cxx': ['-O2',],
        'nvcc':['--gpu-architecture=compute_70','--gpu-code=sm_70','-O3','-I./cutlass/','-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__']
}
`
Actually is it possible to give the step-by-step of the solution? Where do I add this piece of code? Should I reinstall kaolin? should I
