### ISSUE TITLE
A more general implementation of Chamfer loss

### ISSUE THREAD

**Issue by justanhduc** [NVIDIAGameWorks/kaolin#312]
Hi there. I noticed that the Chamfer loss here is for 3D point clouds only, not for batched point cloud of varying sizes and n-dim. There is a batch version from the AtlasNet repo, but still the code is for batchable tensors of 3D point clouds. That's why I have written [here](https://github.com/justanhduc/stack-chamfer) a more generalized version to address all these issues. The current implementation is not very efficient, but it would be nice if someone can give me constructive comment on it.
Thanks!

**Comment by shumash** [comment]
Thank you for the pointer. We haven't had cycles to integrate and optimize this code, so closing for now.
