### ISSUE TITLE
python setup.py build_ext --inplace is failing with error

### ISSUE THREAD

**Issue by usk15** [NVIDIAGameWorks/kaolin#313]
Log:

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
WARNING - 
Warning: Torch did not find available GPUs on this system.
If your intention is to cross-compile, this is not an error.
By default, Kaolin will cross-compile for Pascal (compute capabilities 6.0, 6.1, 6.2),
Volta (compute capability 7.0), and Turing (compute capability 7.5).
If you wish to cross-compile for a single specific architecture,
export TORCH_CUDA_ARCH_LIST="compute capability" before running setup.py.

Building nv-usd...
Processing project file 'packman/target_deps.xml'
running build_ext
/Users/usmankhan/opt/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py:191: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++) is not compatible with the compiler Pytorch was
built with for this platform, which is clang++ on darwin. Please
use clang++ to to compile your extension. Alternatively, you may
compile PyTorch from source using g++, and then you can also use
g++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
building 'kaolin.mcubes' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/usmankhan/opt/anaconda3/include -arch x86_64 -I/Users/usmankhan/opt/anaconda3/include -arch x86_64 -Wno-deprecated-declarations -I/Users/usmankhan/opt/anaconda3/lib/python3.7/site-packages/torch/include -I/Users/usmankhan/opt/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/Users/usmankhan/opt/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/Users/usmankhan/opt/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/Users/usmankhan/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/usmankhan/opt/anaconda3/include/python3.7m -c kaolin/cython/mcubes.cpp -o build/temp.macosx-10.9-x86_64-3.7/kaolin/cython/mcubes.o -std=c++11 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=mcubes -D_GLIBCXX_USE_CXX11_ABI=0
In file included from kaolin/cython/mcubes.cpp:605:
In file included from /Users/usmankhan/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Users/usmankhan/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
In file included from /Users/usmankhan/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:
/Users/usmankhan/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
1 warning generated.
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/usmankhan/opt/anaconda3/include -arch x86_64 -I/Users/usmankhan/opt/anaconda3/include -arch x86_64 -Wno-deprecated-declarations -I/Users/usmankhan/opt/anaconda3/lib/python3.7/site-packages/torch/include -I/Users/usmankhan/opt/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/Users/usmankhan/opt/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/Users/usmankhan/opt/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/Users/usmankhan/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/usmankhan/opt/anaconda3/include/python3.7m -c kaolin/cython/pywrapper.cpp -o build/temp.macosx-10.9-x86_64-3.7/kaolin/cython/pywrapper.o -std=c++11 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=mcubes -D_GLIBCXX_USE_CXX11_ABI=0
In file included from kaolin/cython/pywrapper.cpp:24:
In file included from kaolin/cython/pywrapper.h:28:
In file included from kaolin/cython/pyarraymodule.h:33:
In file included from /Users/usmankhan/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /Users/usmankhan/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
In file included from /Users/usmankhan/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:
/Users/usmankhan/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
kaolin/cython/pywrapper.cpp:120:24: error: non-constant-expression cannot be narrowed from type 'long' to 'double' in initializer list [-Wc++11-narrowing]
    double upper[3] = {shape[0]-1, shape[1]-1, shape[2]-1};
                       ^~~~~~~~~~
kaolin/cython/pywrapper.cpp:120:24: note: insert an explicit cast to silence this issue
    double upper[3] = {shape[0]-1, shape[1]-1, shape[2]-1};
                       ^~~~~~~~~~
                       static_cast<double>( )
kaolin/cython/pywrapper.cpp:120:36: error: non-constant-expression cannot be narrowed from type 'long' to 'double' in initializer list [-Wc++11-narrowing]
    double upper[3] = {shape[0]-1, shape[1]-1, shape[2]-1};
                                   ^~~~~~~~~~
kaolin/cython/pywrapper.cpp:120:36: note: insert an explicit cast to silence this issue
    double upper[3] = {shape[0]-1, shape[1]-1, shape[2]-1};
                                   ^~~~~~~~~~
                                   static_cast<double>( )
kaolin/cython/pywrapper.cpp:120:48: error: non-constant-expression cannot be narrowed from type 'long' to 'double' in initializer list [-Wc++11-narrowing]
    double upper[3] = {shape[0]-1, shape[1]-1, shape[2]-1};
                                               ^~~~~~~~~~
kaolin/cython/pywrapper.cpp:120:48: note: insert an explicit cast to silence this issue
    double upper[3] = {shape[0]-1, shape[1]-1, shape[2]-1};
                                               ^~~~~~~~~~
                                               static_cast<double>( )
kaolin/cython/pywrapper.cpp:159:24: error: non-constant-expression cannot be narrowed from type 'long' to 'double' in initializer list [-Wc++11-narrowing]
    double upper[3] = {shape[0]-1, shape[1]-1, shape[2]-1};
                       ^~~~~~~~~~
kaolin/cython/pywrapper.cpp:159:24: note: insert an explicit cast to silence this issue
    double upper[3] = {shape[0]-1, shape[1]-1, shape[2]-1};
                       ^~~~~~~~~~
                       static_cast<double>( )
kaolin/cython/pywrapper.cpp:159:36: error: non-constant-expression cannot be narrowed from type 'long' to 'double' in initializer list [-Wc++11-narrowing]
    double upper[3] = {shape[0]-1, shape[1]-1, shape[2]-1};
                                   ^~~~~~~~~~
kaolin/cython/pywrapper.cpp:159:36: note: insert an explicit cast to silence this issue
    double upper[3] = {shape[0]-1, shape[1]-1, shape[2]-1};
                                   ^~~~~~~~~~
                                   static_cast<double>( )
kaolin/cython/pywrapper.cpp:159:48: error: non-constant-expression cannot be narrowed from type 'long' to 'double' in initializer list [-Wc++11-narrowing]
    double upper[3] = {shape[0]-1, shape[1]-1, shape[2]-1};
                                               ^~~~~~~~~~
kaolin/cython/pywrapper.cpp:159:48: note: insert an explicit cast to silence this issue
    double upper[3] = {shape[0]-1, shape[1]-1, shape[2]-1};
                                               ^~~~~~~~~~
                                               static_cast<double>( )
kaolin/cython/pywrapper.cpp:198:24: error: non-constant-expression cannot be narrowed from type 'long' to 'double' in initializer list [-Wc++11-narrowing]
    double upper[3] = {shape[0]-1, shape[1]-1, shape[2]-1};
                       ^~~~~~~~~~
kaolin/cython/pywrapper.cpp:198:24: note: insert an explicit cast to silence this issue
    double upper[3] = {shape[0]-1, shape[1]-1, shape[2]-1};
                       ^~~~~~~~~~
                       static_cast<double>( )
kaolin/cython/pywrapper.cpp:198:36: error: non-constant-expression cannot be narrowed from type 'long' to 'double' in initializer list [-Wc++11-narrowing]
    double upper[3] = {shape[0]-1, shape[1]-1, shape[2]-1};
                                   ^~~~~~~~~~
kaolin/cython/pywrapper.cpp:198:36: note: insert an explicit cast to silence this issue
    double upper[3] = {shape[0]-1, shape[1]-1, shape[2]-1};
                                   ^~~~~~~~~~
                                   static_cast<double>( )
kaolin/cython/pywrapper.cpp:198:48: error: non-constant-expression cannot be narrowed from type 'long' to 'double' in initializer list [-Wc++11-narrowing]
    double upper[3] = {shape[0]-1, shape[1]-1, shape[2]-1};
                                               ^~~~~~~~~~
kaolin/cython/pywrapper.cpp:198:48: note: insert an explicit cast to silence this issue
    double upper[3] = {shape[0]-1, shape[1]-1, shape[2]-1};
                                               ^~~~~~~~~~
                                               static_cast<double>( )
1 warning and 9 errors generated.
error: command 'gcc' failed with exit status 1

**Comment by ghost** [comment]
Did You find a solution for this bug?

**Comment by mycuriosity123** [comment]
python setup.py build_ext --inplace
running build_ext
building 'darkflow.cython_utils.nms' extension
cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\user_name\anaconda3\envs\yolo\lib\site-packages\numpy\core\include -IC:\Users\user_name\anaconda3\envs\yolo\include -IC:\Users\user_name\anaconda3\envs\yolo\include /Tcdarkflow/cython_utils/nms.c /Fobuild\temp.win-amd64-3.6\Release\darkflow/cython_utils/nms.obj
error: command 'cl.exe' failed: No such file or directory

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and this issue is no longer current. 

Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

If you encounter issues, please file new bugs. Thanks!
