### ISSUE TITLE
Mesh normal consistency?

### ISSUE THREAD

**Issue by ChengshuLi** [NVIDIAGameWorks/kaolin#314]
In [README](https://github.com/NVIDIAGameWorks/kaolin/blob/e7e513173bd4159ae45be6b3e156a3ad156a3eb9/README.md), it says Mesh has a metric of Normal consistency. However, I didn't find it in https://github.com/NVIDIAGameWorks/kaolin/blob/master/kaolin/metrics/mesh.py. Maybe I missed something? Thanks!

**Comment by shumash** [comment]
Closing old bug, no longer relevant to the library.

We put in a lot of effort to ensure consistency of normals imported from `usd`, `obj`, `gltf`. For example, we check that normals are consistent across input formats in [this test](https://github.com/NVIDIAGameWorks/kaolin/blob/master/tests/python/kaolin/io/test_mesh.py#L109).
