### ISSUE TITLE
How to download shapenet watertight meshes dataset?

### ISSUE THREAD

**Issue by jianglongye** [NVIDIAGameWorks/kaolin#315]
Hi, how can I download shapenet watertight meshes dataset? I failed to find the download link in code or doc.

**Comment by jianglongye** [comment]
I seem to be stupid. In fact, only vanilla shapenet data is needed to generate watertight meshes. 
But maybe the doc can be improved.

**Comment by zoezhou1999** [comment]
Hi @jianglongye I had a same question. could I ask from where you know "only vanilla shapenet data is needed to generate watertight meshes." That means no need to preprocess shapenetv2 to be watertight? Thank you!

**Comment by jianglongye** [comment]
It's too long ago. As far as I can remember, at that time, kaolin can take the vanilla shapenet data as input and output watertight meshes. There is a build-in preprocess for shapenet in kaolin (at that version).

**Comment by zoezhou1999** [comment]
I see. Thanks! But it seems current kaolin does not have this kind of preprocessing? So maybe no need to convert shapenet v2 to watertight?

**Comment by jianglongye** [comment]
It depends on which task your are working on.
If your are doing SDF stuff, you still need the watertight data.

**Comment by zoezhou1999** [comment]
I see. What i am confused is that in some paper it said it used kaolin to get a watertight mesh but current kaolin does not have that function (if I am not wrong?) (of course there are other GitHub repo like manifold... that can use to get watertight

**Comment by jianglongye** [comment]
Yeah, from the latest doc, I can only find this `check_sign` [function](https://kaolin.readthedocs.io/en/latest/modules/kaolin.ops.mesh.html?highlight=watertight#kaolin.ops.mesh.check_sign) which is related to **watertight**. 

Maybe you still need other ways to convert the shapenet mesh to watertight, or maybe the authors can give different solutions.
