### ISSUE TITLE
Windows, the Verifying Build step failed (but eventually works)

### ISSUE THREAD

**Issue by kfarivar** [NVIDIAGameWorks/kaolin#321]
Hi 
I have successfully installed Kaolin on windows The only problem seems to be the datasets, when importing kaolin I get this error. (I commented out all the code in __init__ and I get no errors) so I guess the problem is in the code not the OS.

(kaolin) C:\Users\User\Desktop\Kiarash\kaolin\kaolin>python -c "import kaolin; print(kaolin.__version__)"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\User\Desktop\Kiarash\kaolin\kaolin\kaolin\__init__.py", line 18, in <module>
    from kaolin import datasets
  File "C:\Users\User\Desktop\Kiarash\kaolin\kaolin\kaolin\datasets\__init__.py", line 1, in <module>
    from .shapenet import *
  File "C:\Users\User\Desktop\Kiarash\kaolin\kaolin\kaolin\datasets\shapenet.py", line 46, in <module>
    from .base import KaolinDataset
  File "C:\Users\User\Desktop\Kiarash\kaolin\kaolin\kaolin\datasets\base.py", line 56, in <module>
    class KaolinDataset(Dataset, metaclass=KaolinDatasetMeta):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

**Comment by kfarivar** [comment]
I also ran the tests and Again the same error for all of them:

============================================================================ short test summary info =============================================================================
ERROR tests/test_compute_adjacency_info.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/test_helpers.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/test_import.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/conversions/test_meshconversions.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its ...
ERROR tests/conversions/test_pointcloudconversions.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of al...
ERROR tests/conversions/test_sdfconversions.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its b...
ERROR tests/conversions/test_voxelgridconversions.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all...
ERROR tests/datasets/test_ModelNet.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/datasets/test_ShapeNet.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/datasets/test_nusc.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/datasets/test_shrec.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/datasets/test_usdfile.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/graphics/test_softras.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/mathutils/test_common.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/mathutils/test_transformations.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/metrics/test_mesh_metrics.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/metrics/test_point_metrics.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/metrics/test_voxel_metrics.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/models/test_PointNet.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/models/test_PointNet2.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/models/test_Voxel3DIWGAN.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/models/test_VoxelGAN.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/models/test_VoxelSuperresODM.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/models/test_VoxelSuperresSimple.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its b...
ERROR tests/rep/test_SDF_representation.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/rep/test_mesh_representation.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/rep/test_point_representation.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/rep/test_voxel_representation.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/transforms/test_pointcloudfunc.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/transforms/test_transforms.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/vision/test_geometry.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
ERROR tests/visualize/test_vis_usd.py - TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 32 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================================================== 32 errors in 5.42s ===============================================================================

**Comment by arseneaultj** [comment]
I had the same issue after installing on Windows. 
Changing line 56 in kaolin/datasets/base.py from 
`class KaolinDataset(Dataset, metaclass=KaolinDatasetMeta):`
to 
`class KaolinDataset(Dataset):` 
seems to fix the problem.
Not too familiar with metaclasses in Python, there might be unintended consequences from doing so but so far running a few of the examples I haven't ran into any problem.

**Comment by shumash** [comment]
Closing old bug, no longer relevant.
