### ISSUE TITLE
Kaolin installation problem (Colab/Cloud)

### ISSUE THREAD

**Issue by NikolaZubic** [NVIDIAGameWorks/kaolin#323]
I did:
`!git clone https://github.com/NVIDIAGameWorks/kaolin.git` and then
`%cd kaolin`
`!python setup.py install`
It said: **Finished processing dependencies for kaolin==0.1.0**, so I thought it's installed correctly.

However, when I try to import:
`import kaolin as kal`
`print(kal.__version__)`
it says that kal has no __version__, and also I can't use anything from kaolin.
On the other hand, another error is when line `import kaolin as kal` is not recognized because of the metaclass=KaolinDatasetMeta error.
Did anyone manage to start kaolin from Google Colab/Cloud? A few days ago everything was working...

**Comment by ashwath98** [comment]
Were you able to resolve this issue?

**Comment by NikolaZubic** [comment]
> Were you able to resolve this issue?

Unfortunately, I wasn't. But a reformat is planned in December, so it will be fixed then.

**Comment by ashwath98** [comment]
Ohh. I've  tried installing a previous commit (from August 26) and that it didn't work too.  Currently trying out this solution (https://github.com/NVIDIAGameWorks/kaolin/issues/321)

**Comment by NikolaZubic** [comment]
> Ohh. I've tried installing a previous commit (from August 26) and that it didn't work too. Currently trying out this solution (#321)

I've already tried that and it didn't work.

**Comment by ashwath98** [comment]
Changing line 56 in kaolin/datasets/base.py from

`class KaolinDataset(Dataset, metaclass=KaolinDatasetMeta):`
to
`class KaolinDataset(Dataset):`


This worked for me

**Comment by NikolaZubic** [comment]
> Changing line 56 in kaolin/datasets/base.py from
> 
> `class KaolinDataset(Dataset, metaclass=KaolinDatasetMeta):`
> to
> `class KaolinDataset(Dataset):`
> 
> This worked for me

With the new update that happened few moments ago, everything is now working on Cloud/Colab :+1: 
Great!!!

I will close issue right now.
