### ISSUE TITLE
Installation doesn't work on Ubuntu

### ISSUE THREAD

**Issue by kfarivar** [NVIDIAGameWorks/kaolin#324]
I am using:

Ubuntu 20.04
python 3.8

this is what I get when I run `python setup.py install`

```
Processing dependencies for kaolin==0.1.0
Searching for pptk==0.1.0
Reading https://pypi.org/simple/pptk/
No local packages or working download links found for pptk==0.1.0
error: Could not find suitable distribution for Requirement.parse('pptk==0.1.0')
```
I also tried `pip install pptk` gives:
```
ERROR: Could not find a version that satisfies the requirement pptk==0.1.0 (from versions: none)
ERROR: No matching distribution found for pptk==0.1.0
```

Is pptk central to the library or is it only used for viz ?

**Comment by kfarivar** [comment]
I want to add that python `setup.py build_ext --inplace` doesn't give the that error.

**Comment by ashwath98** [comment]
were you able to resolve this issue?

**Comment by kfarivar** [comment]
No, If I remember correctly I just ran the
```
>>> import kaolin as kal
>>> print(kal.__version__)
```
and commented out any related errors for datasets or ppt and built the library again. (running `python setup.py install`)

**Comment by ashwath98** [comment]
Great. Switching to a python3.6 environment also worked for me

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and this issue is no longer current. 

Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

If you encounter issues, please file new bugs. Thanks!

**Comment by kenorb** [comment]
Installing using Python 3.9 worked.
```
python3.9 -m pip install kaolin==0.12.0 --use-deprecated=html5lib -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.1_cu113.html
```
