### ISSUE TITLE
PointNet Architecture 

### ISSUE THREAD

**Issue by chrispduck** [NVIDIAGameWorks/kaolin#325]
I believe the current PointNet architecture might be incorrect. Else I am unsure how to get the implementation from the original paper from the kaolin library. If I instantiate a 12-category pointNet classifier and print the model, the result is: 

PointNetClassifier(
  (feature_extractor): PointNetFeatureExtractor(
    (conv_layers): ModuleList(
      (0): Conv1d(3, 64, kernel_size=(1,), stride=(1,))
      (1): Conv1d(64, 128, kernel_size=(1,), stride=(1,))
      (2): Conv1d(128, 1024, kernel_size=(1,), stride=(1,))
    )
    (bn_layers): ModuleList(
      (0): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (linear_layers): ModuleList(
    (0): Linear(in_features=1024, out_features=512, bias=True)
    (1): Linear(in_features=512, out_features=256, bias=True)
  )
  (bn_layers): ModuleList(
    (0): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (last_linear_layer): Linear(in_features=256, out_features=12, bias=True)
)

Compare this with the diagram from  original paper:
<img width="1131" alt="Screenshot 2020-11-25 at 11 31 08" src="https://user-images.githubusercontent.com/32284498/100222237-b7d3e980-2f11-11eb-8a59-8f4be08ba65f.png">
 It can also be compared to another implementation [here ](https://towardsdatascience.com/deep-learning-on-point-clouds-implementing-pointnet-in-google-colab-1fd65cd3a263)
 
There seems to be a large portion of network missing. I cannot see the middle layers:  64x64 MLP & TNet 64x64.

I would like to explicitly extract the 3x3 and 64x64 Tnet output transforms to better understand the features.

Any help is much appreciated.

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our [latest documentation](https://kaolin.readthedocs.io/en/latest/).

We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates.

Closing the bug as it is no longer relevant to this repo.
