### ISSUE TITLE
Render Depth map using SoftRasterizer

### ISSUE THREAD

**Issue by mrezaei92** [NVIDIAGameWorks/kaolin#326]
Hi,

I was wondering if you could provide a guidance on how to generate a depth map given a mesh using the SoftRasterizer Renderer.
For example, a minimal code snippet that loads a mesh, and then renders its corresponding depth map would be great.
Thanks.

**Comment by eriksandstroem** [comment]
I would also be interested in this. Specifically, I am looking for a method to retrieve a depth map given a signed distance grid and a pose - identical to what is performed in the paper "KinectFusion". This could be done by e.g. ray-casting.

**Comment by ZuoJiaxing** [comment]
I'm also interested in the implementation of raycasting.

**Comment by Caenorst** [comment]
Closing as the initial request is related to v0.1

for the signed distance grid, I think [SPC](https://kaolin.readthedocs.io/en/latest/notes/spc_summary.html) should be the answer!
