### ISSUE TITLE
PointNetSegmenter prints input shape

### ISSUE THREAD

**Issue by VictorZuanazzi** [NVIDIAGameWorks/kaolin#33]
I came across ghost pints when using PointNetSegmenter.

I am not sure if they are there on purpose. But the forward call of PointNet.PointNetSegmenter is printing the input shape. Line512.

**Comment by VictorZuanazzi** [comment]
For people with the same problem, monkey patching it goes around it!

```
class PointNetSegmenter(PointNet.PointNetSegmenter):
    """PointNetSegmenter without the annoying print"""

    def forward(self, x):
        r"""Forward pass through the PointNet segmentation model.

                Args:
                    x (torch.Tensor): Tensor representing a pointcloud
                        shape: :math:`B \times N \times D`, where :math:`B`
                        is the batchsize, :math:`N` is the number of points
                        in the pointcloud, and :math:`D` is the dimensionality
                        of each point in the pointcloud.
                        If self.transposed_input is True, then the shape is
                        :math:`B \times D \times N`.

                """
        batchsize = x.shape[0]
        num_points = x.shape[2] if self.transposed_input else x.shape[1]
        x = self.feature_extractor(x)
        for idx in range(len(self.conv_layers)):
            if self.batchnorm:
                x = self.activation(self.bn_layers[idx](
                    self.conv_layers[idx](x)))
            else:
                x = self.activation(self.conv_layers[idx](x))
        x = self.last_conv_layer(x)
        x = x.transpose(2, 1).contiguous()
        return x.view(batchsize, num_points, self.num_classes)
```

Just place that in your code and things should work silently again.

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates.

Closing the bug as it is no longer relevant to this repo.
