### ISSUE TITLE
rtx 3080 supported ?

### ISSUE THREAD

**Issue by kwansik** [NVIDIAGameWorks/kaolin#338]
I have tried to install with cuda 10, python 3.6 and get 
raise ValueError("Unknown CUDA arch ({}) or GPU not supported".format(arch))
ValueError: Unknown CUDA arch (8.6) or GPU not supported

p.s. Strange I successfully installed with python 3.7 enviroment but gets errors in running at
  from kaolin.nnsearch import nnsearch
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

**Comment by Caenorst** [comment]
Hi @kwansik ,

Thank you for your support, I assume you are talking about v0.1 since we don't have `kaolin.nnsearch`in v0.9.

I would suggest to update to v0.9.

**Comment by kwansik** [comment]
Thanks for your quick reply.

I needed v0.1 because I have codes that use "kaolin.models" modules and v0.9 does not seem to have such module but v0.1 does.

by the way, GPU may not be the issue. I just tested with GTX760 but still has same error:
>>raise ValueError("Unknown CUDA arch ({}) or GPU not supported".format(arch))
>>ValueError: Unknown CUDA arch (8.6) or GPU not supported

**Comment by ljq2020** [comment]
hi,
RTX3080 CUDA 11.1 supported? I created a virtual environment as follows
pytorch 1.7.1 
python 3.7.6
torchvision 0.8.2
cudatoolkit 11.0.221

**Comment by ljq2020** [comment]
hi, I have tried to install with cuda 10, python 3.7, but failed.
raise ValueError("Unknown CUDA arch ({}) or GPU not supported".format(arch))
ValueError: Unknown CUDA arch (8.6) or GPU not supported
Can you tell me how to deal with it? what is your system virtual environment?

**Comment by Caenorst** [comment]
What command lines are you running ?

**Comment by tovacinni** [comment]
No updates, closing
