### ISSUE TITLE
Contributors section of README.md - "in alphabetical order"

### ISSUE THREAD

**Issue by bl-ue** [NVIDIAGameWorks/kaolin#340]
In the contributors section of the readme, it lists them "In alphabetical order," but they're not ordered alphabetically at all.  The correct order would be the following:

>- Artem Rozantsev
>- Clement Fuji Tsang
>- Edward Smith
>- Frank Shen
>- Gavriel State
>- Jason Gorski
>- Jean-Francois Lafleche
>- Jianing Li
>- Jiehan Wang
>- Krishna Murthy
>- Masha Shugrina
>- Rev Lebaredian
>- Sanja Fidler
>- Tommy Xiang
>- Wenzheng Chen

**Comment by Caenorst** [comment]
Hi @bl-ue ! This is alphabetically sorted by last name :)

**Comment by bl-ue** [comment]
Thank you @Caenorst for the clarification!  This makes more sense, but there's an exception: in the third item of the list (Clement Fuji Tsang), the last name begins with T, and so it should come after the "Gavriel State" entry&mdash;unless "Fuji" is part of the last name...

**Comment by Caenorst** [comment]
"Fuji Tsang" is my last name ;)

Closing the issue.

**Comment by bl-ue** [comment]
Well @Caenorst sorry for the extra issue then!  But it might be better to point out in the readme that they're sorted by last name?
