### ISSUE TITLE
Add .egg files to .gitignore?

### ISSUE THREAD

**Issue by Mason-McGough** [NVIDIAGameWorks/kaolin#341]
Hello,

Just forked this repo and executed all of the tests according to the [installation documentation](https://kaolin.readthedocs.io/en/latest/notes/installation.html). Working great so far.

Several `.egg` files are showing up in my untracked files list (in folders `.eggs/` and `dist/`). Should these be added to `.gitignore`?

**Comment by Caenorst** [comment]
Hi @Mason-McGough , Thank you for your interest in Kaolin.

Adding .egg files to the .gitignore is indeed a good idea since those are generated by running setup.py.
