### ISSUE TITLE
torch 1.7.1 supported?

### ISSUE THREAD

**Issue by jiaqiAA** [NVIDIAGameWorks/kaolin#344]
System:
OS: Ubuntu 18.04
Python version: 3.7.6
PyTorch version: 1.7.1
Torchvision version: 0.8.2
CUDA/cuDNN version: 11.1/8.0.4
GPU: RTX3080
I tried running `python setup.py install` , but I experienced the following: Searching for torch<=1.7.0,>=1.5.0
so it does not support torch 1.7.1?

**Comment by tovacinni** [comment]
Solved by #389
