### ISSUE TITLE
Cannot find the classification engines in the master branch

### ISSUE THREAD

**Issue by praveenv4k** [NVIDIAGameWorks/kaolin#348]
Hi, 
I noticed that many 3D deep learning architectures were implemented until the reformatting of kaolin is done. I cannot find them in the latest master branch. Will they added eventually as part of this repo or will they moved to another repo?

**Comment by Caenorst** [comment]
Hi @praveenv4k ,

As stated in [the change logs](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0) model zoo will part of another repo.

**Comment by MBrandt-NASA** [comment]
Is there any timeline for when the Model Zoo and 3D DL "task" examples / tutorials (classification, segmentation, object detection, etc.) will be available?

I wanted to use Kaolin in my projects, but I'll have to move to another 3D DL library for the time being, until your examples and Model Zoo are released for the 0.9 version of Kaolin.

**Comment by Caenorst** [comment]
@MBrandt-NASA Do you have some model in mind? It would help us prioritize.

**Comment by GSFC-587** [comment]
Hi @Caenorst thanks for asking :).

This year I'm trying to accomplish 3 tasks with 3D DL:

1) 3D **object detection** w/ bounding boxes. (e.g. detecting a crater in lunar terrain), or potentially semantic segmentation, but I prefer objects w/ bounding boxes
2) **pose estimation** (e.g. estimating the pose of a known model -- satellite in orbit)
3) **map generation / registration** -- matching an incoming terrain patch (from a Lidar scan) with the larger containing terrain (e.g. a lunar rover, w/ Lidar, traverses a large terrain and generates a terrain map in real time as each Lidar scan comes in)

I'm evaluating models for: simplicity, reliability, and performance (speed and accuracy)

---------------- Potential models ----------------

Object Detection:
* PointPillars / SECOND (https://github.com/nutonomy/second.pytorch, https://pdfs.semanticscholar.org/5125/a16039cabc6320c908a4764f32596e018ad3.pdf)
* YOLOv4 (https://github.com/maudzung/Complex-YOLOv4-Pytorch)
* VoteNet (https://github.com/facebookresearch/votenet)
* PVR-CNN (https://arxiv.org/abs/1912.13192)
* PVCNN (_NVIDIA Jetson spotlight_ -- https://news.developer.nvidia.com/point-voxel-cnn-3d/?ncid=so-twit-99540#cid=em02_so-twit_en-us, https://github.com/mit-han-lab/pvcnn)

Pose Estimation:
* PCRNet -- _uses PointNet_ (https://github.com/vinits5/pcrnet_pytorch)

Registration:
* PointNetLK -- _uses PointNet_ (https://github.com/hmgoforth/PointNetLK)
* DeepMapping (https://github.com/ai4ce/DeepMapping)

I'm open to other models if you all know others that are simpler or have higher performance, for the above 3 tasks.

Btw, I'm trying to prototype on Windows 10 and potentially deploy to Linux if needed, so it would be nice if both OS's are supported, as with Kaolin 0.1.

I really enjoyed working with Kaolin 0.1 -- PointNet and PointNet++ both worked great for me!  So I'm looking forward to seeing task examples / tutorials for Kaolin 0.9.

**Very important -- examples / tutorials on how to adapt custom datasets** to Kaolin 0.9.

**Comment by shumash** [comment]
We are not able to support rapidly growing variety of models. Rather, Kaolin focuses on maintainable and robust fundamental building blocks. We hope you find it useful when building your own DL pipelines.
