### ISSUE TITLE
discord for this remarkable project

### ISSUE THREAD

**Issue by Delta-Ark** [NVIDIAGameWorks/kaolin#349]
y'all-- is there a discord or slack for this library? I would love to connect with people who are working on this.

**Comment by Caenorst** [comment]
Hi @saitogroup! Thank you for your interest in Kaolin!
We have recently opened a discussion board: https://github.com/NVIDIAGameWorks/kaolin/discussions.

Would that fit the way you want to connect with us and other users?

**Comment by Delta-Ark** [comment]
Hi!

I'm down to check this out and see how it goes! I think that having a
discord allows for rapid sharing of projects and chatting, etc. that
ultimately can lead to nice collaborations.

**Comment by shumash** [comment]
Thanks for the suggestion!
