### ISSUE TITLE
ImportError: cannot import name 'MISE'

### ISSUE THREAD

**Issue by OOF-dura** [NVIDIAGameWorks/kaolin#350]
```
...site-packages/kaolin-0.9.0-py3.6-linux-x86_64.egg/kaolin/ops/conversions/sdf.py", line 41, in <module>
ImportError: cannot import name 'MISE'
```

envs:
- python36
- cuda 10.1
- torch1.6.0

**Comment by zhixuanli** [comment]
@OOF-dura 
Hi, can you share the solution to this problem? Thanks!

**Comment by Caenorst** [comment]
Hi @zhixuanli can you share the whole installation process? What is your system?

**Comment by zhixuanli** [comment]
@Caenorst 
Thanks, I have reinstalled for 3 times with thoroughly deleted anything related and re-download from Github. And I have reinstalled the PyTorch too.
And the problem does not exist now. 

Thanks a lot for your fast reply!
