### ISSUE TITLE
pytest shows 7 warning

### ISSUE THREAD

**Issue by TszYiYang** [NVIDIAGameWorks/kaolin#355]
Howdy,

I've been following this package development since v0.1 and glad to see a long-term support version released. My research interests focus on using the DIB-R to render 3D meshes from single 2D images in agriculture applications. ShapeNetCore.v2 is my practice dataset for training but I'm relatively new to computer photography. Looking forward to more examples on how to use the DIB-R function.

While running $pytest /test/python. Some errors occurred. Not sure how to fix the issues.

Ubuntu 20.04
kaolin v0.9
python 3.7.8
cuda 10.2
torch 1.7.0
cython 0.29.20
scipy 1.5.2
pillow 8.1.0
usd-core 20.11

============================= test session starts ==============================
platform linux -- Python 3.7.8, pytest-5.4.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/username/kaolin
plugins: cov-2.8.1, anyio-2.0.2
collected 1310 items                                                           
.
.
.
.

=============================== warnings summary ===============================
tests/python/kaolin/io/test_materials.py::TestPBRMaterial::test_material_textures
tests/python/kaolin/io/test_usd.py::TestMeshes::test_export_single
  /home/username/kaolin/kaolin/io/obj.py:42: UserWarning: 'None' not found.
    warnings.warn(error.args[0], UserWarning)

tests/python/kaolin/io/test_obj.py::TestLoadObj::test_import_mesh[True-False]
tests/python/kaolin/io/test_obj.py::TestLoadObj::test_import_mesh[True-True]
  /home/username/kaolin/kaolin/io/obj.py:42: UserWarning: Failed to load material at path '/home/username/kaolin/tests/python/kaolin/io/../../../samples/simple_obj/model.mtl':
  [Errno 21] Is a directory: '/home/username/kaolin/tests/python/kaolin/io/../../../samples/simple_obj/.'
    warnings.warn(error.args[0], UserWarning)

tests/python/kaolin/io/test_usd.py::TestMeshes::test_export_only_faces
tests/python/kaolin/io/test_usd.py::TestMeshes::test_export_only_face_uvs
tests/python/kaolin/io/test_usd.py::TestMeshes::test_export_only_face_normals
  /home/username/kaolin/kaolin/io/usd.py:107: UserWarning: Scene object at / contains no vertices.
    warnings.warn(f'Scene object at {scene_path} contains no vertices.', UserWarning)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=========== 1292 passed, 18 skipped, 7 warnings in 128.67s (0:02:08) ===========

**Comment by shumash** [comment]
Hi, thank you for using Kaolin!

I'm going to close this bug, because the warnings generated are correct library behavior and not related to the tests (which pass). We'll consider changing our sample data so that no warnings are generated to avoid confusion.

If you haven't already check out our recently added [Detailed Tutorial on using DIB-R](https://kaolin.readthedocs.io/en/latest/notes/diff_render.html), provided as jupyter notebook. We welcome your feedback.
