### ISSUE TITLE
Joining request.

### ISSUE THREAD

**Issue by Kushal997-das** [NVIDIAGameWorks/kaolin#360]
How i can join this `NVIDIAGameWorks`  this organization?

**Comment by Caenorst** [comment]
Currently you can only join it as an NVIDIA employee. Contribution is not restricted to NVIDIAGameWorks members.

**Comment by Kushal997-das** [comment]
> Currently you can only join it as an NVIDIA employee. Contribution is not restricted to NVIDIAGameWorks members.

Could you please explain more :)

**Comment by Caenorst** [comment]
please look at "Pull Request" tutorials online. For instance: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by Kushal997-das** [comment]
> please look at "Pull Request" tutorials online. For instance: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

I want to join this organization . I know about PR and all how to join could you please tell me?

**Comment by Caenorst** [comment]
As I said, in short AFAIK you can't. Why do you want to join it?

**Comment by Kushal997-das** [comment]
> As I said, in short AFAIK you can't. Why do you want to join it?

Please add me in this organization i want to work in this organization
