### ISSUE TITLE
Missing tutorials

### ISSUE THREAD

**Issue by yogeshhk** [NVIDIAGameWorks/kaolin#369]
Not able to find tutorials in /latest/notes

Example: https://kaolin.readthedocs.io/en/latest/notes/datasets_tutorial.html

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and we are working on adding back tutorials for the rewrite. Please see our [latest documentation](https://kaolin.readthedocs.io/en/latest/) for two recently added tutorials and Watch the github repo for future updates.
