### ISSUE TITLE
PyTorch max version

### ISSUE THREAD

**Issue by mjd3** [NVIDIAGameWorks/kaolin#389]
Is there a reason for the maximum PyTorch version requirement? I've been able to install and use with PyTorch 1.8.0/1.8.1 with no issues and the max version is only listed in the actual `setup.py` file (not in the documentation online). Happy to submit a PR to update to 1.8.1 (currently 1.7.1) or remove the max version requirement entirely if that is needed! There also appears to be an environment variable "IGNORE_VER_ERR" mentioned in the comments of `setup.py` that is not used - maybe implementing this could be an option? As a side note, #344 also references this, but seems like it should be resolved by #353. 
Thanks for the awesome library!

**Comment by Caenorst** [comment]
Hi @mjd3 ! Thank you for your interest in Kaolin and the kind words!

We usually restrict pytorch version to avoid having pytorch update getting us by surprise (it happened in the past). If we were to use this `IGNORE_VER_ERR` environment variable that would probably be more elegant for us to start testing new version without modifying the code.

A PR would be appreciated!
