### ISSUE TITLE
Please help me CUDARuntimeError: cudaErrorNoDevice: no CUDA-capable device is detected

### ISSUE THREAD

**Issue by fiomfarisi** [NVIDIAGameWorks/kaolin#393]
CUDARuntimeError: cudaErrorNoDevice: no CUDA-capable device is detected

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation.

Closing the bug as it is no longer relevant to this repo.

**Comment by Caenorst** [comment]
It looks like a pytorch issue, I assume `torch.cuda.is_available()` would return False?

**Comment by tovacinni** [comment]
No updates, closing
