### ISSUE TITLE
On spherical harmonics lighting

### ISSUE THREAD

**Issue by cosw0t** [NVIDIAGameWorks/kaolin#394]
Hi guys, and congratulations on releasing a stable version of kaolin.

I couldn't help but notice that kaolin hints at using SH for illumination - which is a great option to have (unique, learnable, compact representation of a light field, all great!). 

Have you looked into how to do spatial transformations of the SH coefficients (efficiently with pytorch obviously) from matrix or quaternion + offset? I'm thinking for example if you have a camera moving around an object, and you render from these different positions, the coefficients for light calculations will have to follow the (inverse) of the camera rotation in order to give correct calculations.

I'm not an expert on this topic, but I very much would like to use SH efficiently. I will certainly do my own research, however I also wanted to ask if you have somethin "in the making" or suggestions on how to do it with the convention you chose.

Thank you vm!

**Comment by Caenorst** [comment]
Hi @michele-arrival !

Good timing, I'm exploring sampling of spherical harmonics lighting for generating data for DIB-R training, and been struggling with spherical harmonics and camera movements too :)

One of the easy ways I've found of managing this case with dibr, so far is to interpolate the face_normals BEFORE applying camera transformations, it will return the normals in the world coordinate system, which is independent to the camera position.

Something like that:
```
...
# Here we index and compute the normals of the mesh in the world coordinate system
# (assume batch_size = 1)
face_vertices = kal.ops.mesh.index_vertices_by_faces(vertices, faces)
face_normals_world = kal.ops.mesh.face_normals(face_vertices, True)

# Here we apply camera transformations (broadcast over batch axis)
# with cam_transform of shape (nb_views, 4, 3)
face_vertices_camera, face_vertices_image, face_normals = \
    kal.render.mesh.prepare_vertices(
        vertices, faces, cam_proj, camera_transform=cam_transform
    )
face_attributes = [
    face_uvs.repeat(nb_views, 1, 1, 1),
    torch.ones((nb_views, nb_faces, 3, 1), device='cuda'),
]
image_features, soft_mask, face_idx = kal.render.mesh.dibr_rasterization(
    imsize, imsize, face_vertices_camera[:, :, :, -1],
    face_vertices_image, face_attributes, face_normals[:, :, -1])
im_texture_coords, hard_mask = image_features
im_normals = face_normals_world[0, face_idx, :]
lighting = kal.render.mesh.utils.spherical_harmonic_lighting(
    im_normals, lighting_params)
```
The code will be a little bit more complex if the model don't have all the faces in the right orientation


However applying transforms on the spherical lighting parameters is a good idea, I will explore that.

**Comment by cosw0t** [comment]
Hi @Caenorst 

that's actually a great tip, since the diffuse component doesn't depend on the viewpoint, you select the faces and then you shade them withut any transformations. I'll try that!

SH won't be any good for specular component, right?

Thanks!

**Comment by Caenorst** [comment]
I believe it won't but I have limited knowledge there.

**Comment by rozentill** [comment]
@Caenorst  Hi,

I am also considering using DIB-R to generate data, however it seems there is only one lighting option - spherical harmonic lighting which seems not enough to render images like real-life photo. Do you mind sharing more ideas on the data generation? The Omniverse Kaolin's data generator seems better and has more lighting options, however I cannot load a bunch of models for generating a dataset, only can load one model at a time which is very less efficient and not useful for my task. 

Thanks,
Ryan
