### ISSUE TITLE
Sparse adjacency matrix and laplacian matrix problem

### ISSUE THREAD

**Issue by AndresCasado** [NVIDIAGameWorks/kaolin#401]
There is an inconsistency in the `adjacency_matrix` function in `kaolin.ops.mesh` that is making `uniform_laplacian` return a wrong matrix.

When `adjacency_matrix` has the parameter `sparse=True` (default behaviour), it accounts the shared edges twice. In the following mesh, it counts the edge 0-3 twice. See the code below.
```
0-----1
|\    |
| \   |
|  \  |
|   \ |
|    \|
2-----3
```

Code sample:
```python
import torch
from kaolin.ops.mesh import adjacency_matrix
f = torch.tensor([[0, 1, 3], [3, 2, 0]])

print('Sparse to dense')
print(adjacency_matrix(4, f).to_dense())
print()

print('Dense')
print(adjacency_matrix(4, f, sparse=False))
print()

```

Output:
```
Sparse to dense
tensor([[0., 1., 1., 2.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [2., 1., 1., 0.]])

Dense
tensor([[0., 1., 1., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 1., 1., 0.]])
```

Instead of setting `sparse = False`, the function `uniform_laplacian` calls `adjacency_matrix` and then calls `to_dense()` on the result, which, as shown above, is not correct. https://github.com/NVIDIAGameWorks/kaolin/blob/4f01dda27ac1655b189918c323473d4b603dcece/kaolin/ops/mesh/mesh.py#L104

# 

The fastest fix for `uniform_laplacian` would be to use `sparse=False` directly.
```python
dense_adjacency = adjacency_matrix(num_vertices, faces, sparse=False)
```

# 

For `adjacency_matrix` the solution would be to avoid the repetition of edges. For example, calling `unique` along dimension 0 before transposing the indices seems to work, although I don't know how efficient it is on large matrices.

Original code:
https://github.com/NVIDIAGameWorks/kaolin/blob/4f01dda27ac1655b189918c323473d4b603dcece/kaolin/ops/mesh/mesh.py#L70-L74

Proposed edit:
```python
    if sparse:
        indices = indices.unique(dim=0)
        indices = indices.t()
        # If vertex i and j have an edge connect to it, A[i, j] = 1
        values = torch.ones(indices.shape[1], device=device)
        adjacency = torch.sparse.FloatTensor(indices, values, (num_vertices, num_vertices))
```

**Comment by Caenorst** [comment]
Hi @AndresCasado !

Good catch! Do you want to proceed for an MR? I would gladly welcome it, otherwise I will fix it ASAP.

I think we should also add an additional test to verify that adjacencies are matching between sparse and dense.
