### ISSUE TITLE
Cannot import kaolin.metrics.mesh etc...

### ISSUE THREAD

**Issue by hengtaoguo** [NVIDIAGameWorks/kaolin#414]
Hi! Thanks for developing this tool!

I have been trying to install kaolin in my Linux docker. Now the installation is complete, and I can see the info through `pip show kaolin` and successfully `import kaolin`. However, I cannot succeed any imports other than that. All these following imports do not work for me and gives "No module named 'xxx'":

`import kaolin.rep`, `import kaolin.metrics.mesh`, `kaolin.cuda`...

Also, when I install kaolin through `python setup.py develop`, it fives an error "No local pacakges or working download links found for usd-core==20.11". I tried to install this usd-core through manually downloaded packages, but also gives me error "usd_core-20.11-cp36-none-manylinux2014_x86_64.whl is not a supported wheel on this platform". So I commented out the line `requirements.append('usd-core==20.11')` in setup.py and finished installing. I am not sure whether this is the problem.

Thank you so much for your time and patience! Looking forward to hearing from you!

**Comment by Caenorst** [comment]
Hi @Tonight1121 ! Thank you for your interest in Kaolin!

Can you specify your system? (Linux OS? Python version? Pytorch version? CUDA version?)

Thanks!

**Comment by hengtaoguo** [comment]
> Hi @Tonight1121 ! Thank you for your interest in Kaolin!
> 
> Can you specify your system? (Linux OS? Python version? Pytorch version? CUDA version?)
> 
> Thanks!

Thank you so much for the timely reply! Here are my settings:

Ubuntu 18.04.3
Python 3.8.8
Pytorch 1.9.0
Cuda 10.2
Cython 0.29.23
Scipy 1.21.0
Pillow 8.3.1

**Comment by Caenorst** [comment]
So, be aware that USD related features only works with python `>=3.6,<3.8`, however Kaolin should install without USD if python version is outside of this supported range. Can you describe your installation process?

**Comment by hengtaoguo** [comment]
> So, be aware that USD related features only works with python `>=3.6,<3.8`, however Kaolin should install without USD if python version is outside of this supported range. Can you describe your installation process?

I was configuring these environments in a docker container on the Linux system. Inside this docker image, I followed the [instructions](https://kaolin.readthedocs.io/en/latest/notes/installation.html):

`git clone --recursive https://github.com/NVIDIAGameWorks/kaolin`
`cd kaolin`
`git checkout v0.9.0`
`python setup.py develop`

Note that in order to complete the installation, I commented out the requirements of USD. Besides, I also tried to install kaolin in a virtual environment, but when I ran `python setup.py develop`, it showed:

> no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'at::TensorList {aka c10::ArrayRef<at::Tensor>}'       
error: command 'gcc' failed with exit status 1

**Comment by Caenorst** [comment]
Just to be sure, do you want the release v0.9.0 or the latest version of kaolin? There have been several changes since v0.9.0, if you still want to use v0.9.0, then the corresponding documentation is: https://kaolin.readthedocs.io/en/v0.9.0/

**Comment by hengtaoguo** [comment]
> Just to be sure, do you want the release v0.9.0 or the latest version of kaolin? There have been several changes since v0.9.0, if you still want to use v0.9.0, then the corresponding documentation is: https://kaolin.readthedocs.io/en/v0.9.0/

Hi thank your for your hint! I have successfully build v0.9.0 kaolin, but noticed that the codes, from other author's public [project](https://github.com/taconite/PTF), was built depending on your older version v0.1. There are many function callings are inconsistent with the newer version v0.9.0. For example, I cannot find `kaolin.rep, kaolin.metrics.mesh`. Also some other functions are miss-matching including "_compute_edge_dist, _compute_planar_dist, TriangleDistance, point_to_surface". Do you have any suggestions on how can I modify the codes (built on kaolin v0.1) to fit the newer version v0.9.0? In other words, how can I find the correspondences of each functions from old to new?

I am really much appreciated for your help! Thanks a lot in advance!

**Comment by Caenorst** [comment]
v0.9.0 went through a reformat, so we didn't specifically look for correspondences.

For instance I see that in the project you've linked they used `TriangleMesh` which doesn't exist anymore in v0.9.0, we figured out that the representation was a little bit awkward to use, so we decided to remove it for now. However, we do have sometimes very similar functions, like the `laplacian_loss` used in the project.

The project recommend checkout to a specific commit and so if you intend to use exactly the same project you should follow their recommendation, but if you want to use the latest features I recommend just always following master.

**Comment by Tanmay98** [comment]
Hi can you let me know how to install the previous version of kaolin (V0.1)? Thanks in advance

**Comment by Xuanmeng-Zhang** [comment]
> v0.9.0 went through a reformat, so we didn't specifically look for correspondences.
> 
> For instance I see that in the project you've linked they used `TriangleMesh` which doesn't exist anymore in v0.9.0, we figured out that the representation was a little bit awkward to use, so we decided to remove it for now. However, we do have sometimes very similar functions, like the `laplacian_loss` used in the project.
> 
> The project recommend checkout to a specific commit and so if you intend to use exactly the same project you should follow their recommendation, but if you want to use the latest features I recommend just always following master.

Hello, I want to know what function can calculate the laplacian_loss of two meshes in the latest version.
