### ISSUE TITLE
Unable to resolve Cuda issue

### ISSUE THREAD

**Issue by shersoni610** [NVIDIAGameWorks/kaolin#42]
Hello,

I am running Ubuntu 18.04 with Cuda 10.1. However, I am unable to resolve the error message
coming from "pytest tests". What should I check for?

(kaolin)$ pytest tests
============================================= test session starts ==============================================
platform linux -- Python 3.6.7, pytest-5.2.4, py-1.8.0, pluggy-0.13.0
rootdir: /Software/MLearn/kaolin
plugins: cov-2.8.1
collected 163 items / 1 errors / 162 selected                                                                  

==================================================== ERRORS ====================================================
____________________________ ERROR collecting tests/test_compute_adjacency_info.py _____________________________
tests/test_compute_adjacency_info.py:31: in <module>
    ef, ef_count = Mesh.compute_adjacency_info(vertices_gpu, faces_gpu)
/home//Disk/Software/Anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.2.0+ed13273-py3.6-linux-x86_64.egg/kaolin/rep/Mesh.py:534: in compute_adjacency_info
    [faces[:,[-1,0]]], dim=0)
E   RuntimeError: CUDA error: no kernel image is available for execution on the device
=============================================== warnings summary ===============================================
/home/Disk/Software/Anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.2.0+ed13273-py3.6-linux-x86_64.egg/kaolin/nnsearch.py:3
  /home/Disk/Software/Anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.2.0+ed13273-py3.6-linux-x86_64.egg/kaolin/nnsearch.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

/home/Disk/Software/Anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.2.0+ed13273-py3.6-linux-x86_64.egg/kaolin/datasets/shapenet.py:861
/home/Disk/Software/Anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.2.0+ed13273-py3.6-linux-x86_64.egg/kaolin/datasets/shapenet.py:861
  /home/Disk/Software/Anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.2.0+ed13273-py3.6-linux-x86_64.egg/kaolin/datasets/shapenet.py:861: DeprecationWarning: invalid escape sequence \*

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================= 3 warnings, 1 error in 4.12s ====

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

Closing the bug as it is no longer relevant to this repo.
