### ISSUE TITLE
Parsing realistic 2d Images

### ISSUE THREAD

**Issue by Medoalmasry** [NVIDIAGameWorks/kaolin#423]
Is there a way to load a realistic 2D image, with it's corresponding mask into the kaolin library?
As in without any camera properties, or the omniverse application?

**Comment by Caenorst** [comment]
Hi @Medoalmasry !

You can use a Deep Learning model to do the segmentation, in [DIB-R paper](https://nv-tlabs.github.io/DIB-R/files/diff_shader.pdf), it is said that the mask in PASCAL3D+ is estimated from Mask R-CNN.

**Comment by Medoalmasry** [comment]
Would you please direct me towards a simple tutorial or at the very least reference the relevant api calls to load a single realistic image with it's mask and produce the corresponding point cloud or mesh?

**Comment by Caenorst** [comment]
There is is no such functionality directly implemented in Kaolin, there is a torchvision tutorial for Mask R-CNN here: https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html
