### ISSUE TITLE
ModuleNotFoundError: No module named 'Cython'

### ISSUE THREAD

**Issue by nikogamulin** [NVIDIAGameWorks/kaolin#43]
Environment: Ubuntu 18.04
When running python setup.py install, I get the following error:

```

> Using /home/niko/workspace/kaolin/venv/lib/python3.6/site-packages
> Finished processing dependencies for kaolin==0.2.0+1accd3e
> Traceback (most recent call last):
>   File "setup.py", line 98, in <module>
>     import Cython
> ModuleNotFoundError: No module named 'Cython'

```
### Installation procedure:
```
virtualenv -p /usr/bin/python3.6 venv #create virtual environment
# activate virtual environment
pip install numpy
pip install torch torchvision
python setup.py install
```

The same error occurred in case of using conda instead of pip

**Comment by bobiblazeski** [comment]
Did you tried upgrading cython via conda?

`$ conda install -c anaconda cython`

**Comment by nikogamulin** [comment]
> Did you tried upgrading cython via conda?
> 
> `$ conda install -c anaconda cython`

Thanks, this solved the issue.
