### ISSUE TITLE
Typo in materials.py?

### ISSUE THREAD

**Issue by clemense** [NVIDIAGameWorks/kaolin#443]
https://github.com/NVIDIAGameWorks/kaolin/blob/2158b5ec7a28d57d7df7e606adbb0c693a0145f0/kaolin/io/materials.py#L260

This looks like a little bug, I think it should be:
```
texture_file_path = posixpath.join(usd_dir, texture_path)
```
?

**Comment by Caenorst** [comment]
Hi @clemense , good catch! We addressed it on MR #445
