### ISSUE TITLE
It doesn't import obj file (v0.9.1)

### ISSUE THREAD

**Issue by typest** [NVIDIAGameWorks/kaolin#447]
I tried loading obj file that contain faces constructed by various number of vertices (faces constructed 3 or 4 vertices). But model.obj.import_mehs() returns exception "expected sequence of length 3 at dim 1 (got 4)".

**Comment by Caenorst** [comment]
Hi @typest our obj loader currently only support homogeneous meshes.

If you want to load heterogeneous mesh do you want to keep them heterogeneous or eventually convert them to triangle mesh?

**Comment by Caenorst** [comment]
Added `heterogeneous_mesh_handler` to `kaolin.io.obj.import_mesh`.
