### ISSUE TITLE
Surface extraction in voxels is wide

### ISSUE THREAD

**Issue by le-Greg** [NVIDIAGameWorks/kaolin#448]
Hello, 

In kaolin/ops/voxelgrid.py, extract_surface() removes internal voxels to keep only external voxels. It does this by keeping the filled voxels that are next to an empty voxel in a 3x3 radius. In the Trimesh library, there is a hollow function that does the same on the processor, but it has an option to choose the adjacency matrix, and by default it only keeps filled voxels that are directly next to a empty voxel. It gives a finer surface.

I made an illustration in 2D, but it is the same in 3D : 

```
import matplotlib.pyplot as plt
import torch
import numpy as np

device = "cuda" if torch.cuda.is_available() else "cpu"

noise = np.random.randn(3, 3) + 1j * np.random.randn(3, 3)
binary_map = np.fft.ifft2(noise, (100, 100)).real
binary_map = binary_map > np.median(binary_map)

plt.imshow(binary_map)
plt.show()
```
First i made a binary image made of random blob (yellow=True)
![Figure_1](https://user-images.githubusercontent.com/68744272/135157747-4617ce9e-9f63-4959-bd5f-c54feecbf889.png)

```
def trimesh_surface(dense, structure=None):
    from scipy.ndimage import binary_dilation
    # dense = np.pad(dense, np.ones((3, 2), dtype=int), mode='constant')
    dense = np.pad(dense, np.ones((2, 2), dtype=int), mode='constant')
    empty = np.logical_not(dense)
    dilated = binary_dilation(empty, structure=structure)
    # surface = np.logical_and(dense, dilated)[1:-1, 1:-1, 1:-1]
    surface = np.logical_and(dense, dilated)[1:-1, 1:-1]
    return surface


trimesh_map = trimesh_surface(binary_map)
plt.imshow(trimesh_map)
plt.show()
```
Thin surface
![Figure_2](https://user-images.githubusercontent.com/68744272/135157767-0c88f248-182b-493d-8bc9-52df1fcf0736.png)

```
def kaolin_surface(voxelgrids):
    import torch.nn.functional as F

    voxelgrids = voxelgrids.float()

    # output = F.avg_pool3d(voxelgrids.unsqueeze(1), kernel_size=(3, 3, 3), padding=1, stride=1).squeeze(1)
    output = F.avg_pool2d(voxelgrids.unsqueeze(1), kernel_size=(3, 3), padding=1, stride=1).squeeze(1)

    output = (output < 1) * voxelgrids.bool()

    return output


kaolin_map = torch.from_numpy(binary_map).unsqueeze(0).to(device)
kaolin_map = kaolin_surface(kaolin_map)
kaolin_map = kaolin_map.squeeze(0).cpu()
plt.imshow(kaolin_map)
plt.show()
```
Wide surface
![Figure_3](https://user-images.githubusercontent.com/68744272/135157783-ff198ca7-0467-417f-9c18-5e8195d21561.png)

I want to extract the surfaces of the voxels and then calculate the SDF, and I guess I will have better results if I use the thinnest layer. Is there a reason why the wide surfaces is preferred? I could do a PR to make the two options available (wide and thin), would that be useful ?

**Comment by Caenorst** [comment]
Hi @le-Greg ,

I'm not sure there is a specific reason we chose the "wide" version, but if a thinner version is useful for you then it may be useful for others too!

I believe you can implement it just by using a conv3d with a cross-pattern instead of `avg_pool3d` here: https://github.com/NVIDIAGameWorks/kaolin/blob/2158b5ec7a28d57d7df7e606adbb0c693a0145f0/kaolin/ops/voxelgrid.py#L119-L120

**Comment by le-Greg** [comment]
Indeed, we can implement this function using a convolution and an edge detection filter, like this : 

```
kernel = [[[0, 0, 0], [0, -1, 0], [0, 0, 0]],
              [[0, -1, 0], [-1, 6, -1], [0, -1, 0]],
              [[0, 0, 0], [0, -1, 0], [0, 0, 0]]]

output = F.conv3d(voxelgrids.unsqueeze(1),
                  weight=torch.tensor(kernel, dtype=torch.float, device=voxelgrids.device)[None, None],
                  bias=None, stride=1, padding=1, dilation=1, groups=1).squeeze(1)

output = output > 0.5
```

For my project, I had adapted what had been done before with average pooling. It's less flexible than convolution since you can't change the filter, but it's faster. I did a quick speed comparison on a 128x128x128 voxel grid, and it took 27e-4 seconds with convolution, and 3e-4 seconds with pooling, on GPU

```
output_z = F.avg_pool3d(voxelgrids.unsqueeze(1), kernel_size=(1, 1, 3), padding=(0, 0, 1), stride=1).squeeze(1)
output_y = F.avg_pool3d(voxelgrids.unsqueeze(1), kernel_size=(1, 3, 1), padding=(0, 1, 0), stride=1).squeeze(1)
output_x = F.avg_pool3d(voxelgrids.unsqueeze(1), kernel_size=(3, 1, 1), padding=(1, 0, 0), stride=1).squeeze(1)

output = ((output_x < 1) | (output_y < 1) | (output_z < 1)) * voxelgrids.bool()
```

Moreover, if the "wide" option has no interest, compared to the "thin" option, it should perhaps be just removed? Or put the thin option by default ? It breaks the backward compatibility though

What is the right approach in your opinion?

**Comment by Caenorst** [comment]
Didn't expect the avg_pool3d approach to be faster! :+1: 

I suggest to add a string "mode" as argument (use "wide" by default to be backward compatible:
```
def extract_surface(voxelgrids, mode="wide"):
[...]
if mode == "wide":
[...]
elif mode == "thin":
[...]
else:
    raise ValueError(f'mode "{mode}" not supported.')
[...]
```
