### ISSUE TITLE
ImportError: cannot import name 'ClassificationEngine' from 'kaolin'

### ISSUE THREAD

**Issue by shakirsadiq6** [NVIDIAGameWorks/kaolin#450]
I found a resource on the internet for 3D object detection using torch and kaolin. I installed the Kaolin and I was able to import it but I am not able to find/import these attributes.
from kaolin import ClassificationEngine
from kaolin.datasets import ModelNet
from kaolin.models.PointNet import PointNetClassifier
import kaolin.transforms
The resource link is https://towardsdatascience.com/3d-object-classification-in-6-steps-using-kaolin-and-colab-9ecb079143a8

**Comment by tovacinni** [comment]
Please refer to issue #348
