### ISSUE TITLE
Missing trianglemeshes_to_spcs

### ISSUE THREAD

**Issue by Talmaj** [NVIDIAGameWorks/kaolin#452]
The Documentation mentions `trianglemeshes_to_spcs` function, which is not in the repository.

**Comment by Caenorst** [comment]
Hi @Talmaj ! 

Indeed we postponed the merging of this function as we found some issues. We should fix that in the current documentation.

In the meanwhile the solution we recommend is to heavily sample points from meshes and convert the point clouds to SPC

**Comment by Caenorst** [comment]
Addressed!
