### ISSUE TITLE
Unable to find instructions to load objs to sdf and back to objs

### ISSUE THREAD

**Issue by fire** [NVIDIAGameWorks/kaolin#459]
Hi I was impressed by the demo images.

Hoping to find a short instruction on how to do these mesh operations:

1. Install kaolin.
1. load objs to sdf
1. save sdfs
1. from sdfs create a obj

**Comment by fire** [comment]
Instructions were split into https://kaolin.readthedocs.io/en/v0.9.1/notes/installation.html and https://kaolin.readthedocs.io/en/v0.9.1/notes/checkpoints.html. 

Perhaps something can be done for a quick start example.

**Comment by tovacinni** [comment]
Hi @fire , thanks for your interest in Kaolin. Currently probably the best way to learn Kaolin is to take a look through the documentation and look for relevant functions. We hope to make more demos which will make learning Kaolin smoother in the future.

The functions which will be useful to you would be:

`kaolin.io.obj.import_mesh` to import a mesh.

`torch.meshgrid` to generate a bunch of 3D coordinates of a voxel grid.

`kaolin.metrics.trianglemesh.point_to_mesh_distance` to get the distance function for those points.

`kaolin.ops.mesh.check_sign` to get the sign of the points to multiply with the distance.

`kaolin.ops.conversions.voxelgrids_to_trianglemeshes` to convert the SDF grid to a mesh.

**Comment by fire** [comment]
Would you be interested in a demo or a guide as the result of my learning?

**Comment by tovacinni** [comment]
PRs are always definitely welcome! A good place to put one would be in here: https://github.com/NVIDIAGameWorks/kaolin/tree/master/examples/tutorial 

Let us know if you have any more questions in the mean time.

**Comment by fire** [comment]
Since you're around. I'm looking for a LOD-type triangle mesh triangle count reduce method.

In theory, I can resample the SDF grid to reduce the triangle density of `voxelgrids_to_trianglemeshes`.

**Comment by tovacinni** [comment]
That would definitely be one way of doing level of detail, especially if you have a mechanism of doing adaptive grids with adaptive marching cubes (it's not currently something we support, though).

Another approach could be just to use a library like `libigl` (https://github.com/libigl/libigl) and use one of the geometry decimation algorithms like `qslim` which based on this paper: http://people.eecs.berkeley.edu/~jrs/meshpapers/GarlandHeckbert2.pdf . `libigl` also has Python bindings but I'm not 100% sure if it has `qslim` in the current bindings.

**Comment by fire** [comment]
Of course there's also Neural Geometric Level of Detail: Real-time Rendering with Implicit 3D Surfaces https://github.com/nv-tlabs/nglod.

**Comment by fire** [comment]
Thanks. I'll close this for now.
