### ISSUE TITLE
Has kaolin any point cloud to mesh built-in system?

### ISSUE THREAD

**Issue by FrankEscobar** [NVIDIAGameWorks/kaolin#468]
I've seen several images like this one https://developer.nvidia.com/sites/default/files/akamai/kaolin/kaolin_004.png but I didn't saw a function to make the meshing is there any prebuilt fuction we could test?

Thank you.

**Comment by shumash** [comment]
We currently support the following conversions:

<img width="560" alt="Screen Shot 2021-11-18 at 12 44 47 AM" src="https://user-images.githubusercontent.com/298785/142359061-692dc9f6-2adc-4ef8-a49b-9bc5d5f9a7b1.png">

See docs:
https://kaolin.readthedocs.io/en/latest/modules/kaolin.ops.conversions.html 
https://kaolin.readthedocs.io/en/latest/modules/kaolin.ops.mesh.html#kaolin.ops.mesh.sample_points
