### ISSUE TITLE
kaolin-dash3d can not show mesh_0.usd generated by dibr_tutorial.ipynb

### ISSUE THREAD

**Issue by rainsoulsrx** [NVIDIAGameWorks/kaolin#473]
I follow the dibr_tutorial.ipynb and generate some files in tutorial/logs/optimized_mesh/optimized_mesh, as followed:
![image](https://user-images.githubusercontent.com/24955512/142357198-7ae2fba6-a37c-4482-9648-9e221ea539ee.png)

 and I use "kaolin-dash3d --logdir=./ --port=80" to show the mesh, nothing show in the screen:

![image](https://user-images.githubusercontent.com/24955512/142357252-2d74ec4b-0ef8-4815-9443-a7b7b25612bb.png)

**Comment by shumash** [comment]
Hi, I'd like the verify if the problem is with the mesh or the viewer. Could you please:

- paste the output of `ls ` for the directory you are passing as --logdir. 
- share the logdir generated by `Timelapse`

**Comment by rainsoulsrx** [comment]
I ran the command `kaolin-dash3d --logdir=./ --port=80` in the folder `logs/optimized_mesh/optimized_mesh` , the file tree are as followed:

![image](https://user-images.githubusercontent.com/24955512/142361580-5e405def-d599-4286-80d7-a7ee37a21032.png)


Generated files are as followed 
[logs.zip](https://github.com/NVIDIAGameWorks/kaolin/files/7560375/logs.zip)
:


> Hi, I'd like the verify if the problem is with the mesh or the viewer. Could you please:
> 
> * paste the output of `ls ` for the directory you are passing as --logdir.
> * share the logdir generated by `Timelapse`

**Comment by rainsoulsrx** [comment]
I run the tutorial again, now it works,  thanks!
