### ISSUE TITLE
it fails to load textures of usdc file!

### ISSUE THREAD

**Issue by dedoogong** [NVIDIAGameWorks/kaolin#481]
Hello I'm using kaolin for generating train data.

I have a usdc mesh file and texture.png, normal.png, ao.png, disp.png,  roughness.png files. 

I successfully loaded the usdc file on blender even though I had to specify the paths of the texture and other png files by myself. 

After modifying the mesh(deleting some redundant vertexes), I exported it to a usdc file. 

When I imported the exported usdc file, it shows only the modified mesh, without texture or any png files together. 

I can't fine any way to specify the path or png file. 

Please help me!

**Comment by Caenorst** [comment]
Hi @dedoogong ! Thank you for your interest in Kaolin.

We are currently working on the usd importer support for materials, which should arrive **very** soon!

**Comment by Caenorst** [comment]
Hi @dedoogong we have updated the exporter, we now support [https://kaolin.readthedocs.io/en/latest/modules/kaolin.io.materials.html#kaolin.io.materials.PBRMaterial](PBR materials) !

Closing this issue
