### ISSUE TITLE
Maintaining object origin location through TriangleMesh to VoxelGrid conversion

### ISSUE THREAD

**Issue by NSkoronski** [NVIDIAGameWorks/kaolin#483]
Hello, I am using Kaolin to remove geometry inside of a triangle mesh through converting it to a voxelgrid. Currently during this conversion the geometry is shifted to a single quadrant with its local origin matching the global origin, which would normally not be an issue but as I do not know the location of the trianglemesh local origin I cannot compare the resulting voxel to it. Is there a way to get that origin transformation from the conversion or is that something that is going to be implemented in the future?

Thank you!

**Comment by Caenorst** [comment]
Hi @NSkoronski , thank you for your interest in Kaolin,
currently the default behavior of `trianglemeshes_to_voxelgrids` if you don't provide a scale and origin will try to fit the whole mesh into `[0, 1]`

> [...] I do not know the location of the trianglemesh local origin

I'm not sure to understand why can't you find the origin or your triangle? (It is basically the min of all dimensions over your vertices coordinates)

**Comment by Caenorst** [comment]
Here is how I would suggest to use the mesh => voxelgrid => mesh for keeping the scale:
```
resolution = 128
voxelgrids = kal.ops.conversions.trianglemeshes_to_voxelgrids(vertices.unsqueeze(0), faces, resolution)
origin = torch.min(vertices, dim=0)[0]
scale = torch.max(torch.max(vertices, dim=0)[0] - origin, dim=-1)[0]
new_mesh = kal.ops.conversions.voxelgrids_to_trianglemeshes(voxelgrids)
new_vertices = new_mesh[0][0]
new_faces = new_mesh[1][0]
scaled_vertices = ((new_vertices - 0.5) * (scale / resolution)) + origin
```

**Comment by Caenorst** [comment]
![Screenshot 2021-12-10 122535](https://user-images.githubusercontent.com/10882588/145616308-0dc02fe2-f3be-410d-8725-92eefb1a989b.png)
Here is a visualization, from far to near: the original mesh, the processed and rescaled mesh, the combined mesh (it looks almost 100% like the rescaled mesh)

**Comment by Caenorst** [comment]
![Screenshot 2021-12-10 122623](https://user-images.githubusercontent.com/10882588/145616438-e2654bb7-b2ee-47f5-b4f7-c2cdaa53a3d3.png)
And here is what happens on the combined mesh once I multiply the scale by `0.8` (so the mesh is a little bit smaller, and closer from the origin, hence the fact that it's coming out on one "corner")

**Comment by Caenorst** [comment]
Hope that answer your issue, closing now feel free to reopen if not :)
