### ISSUE TITLE
MeshCNN implementation

### ISSUE THREAD

**Issue by francescomilano172** [NVIDIAGameWorks/kaolin#49]
Hi,
Thank you for the great work. Has the implementation of MeshCNN already been released? I can't seem to find it either in the `kaolin/models` folder or anywhere else in the repo.

Thanks!

**Comment by mattans** [comment]
Same here.

**Comment by mattans** [comment]
I don't think kaolin released a MeshCNN implantation (though it's in the kaolin paper).

We can use the official implementation from https://github.com/ranahanocka/MeshCNN

**Comment by mattans** [comment]
@krrish94 can you please clarify this? Is kaolin expected to release a MeshCNN model?

**Comment by lancefi** [comment]
Any update to this?

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates.

Closing the bug as it is no longer relevant to this repo.
