### ISSUE TITLE
missing kaolin.nnsearch

### ISSUE THREAD

**Issue by mpicci** [NVIDIAGameWorks/kaolin#5]
Hello,
when I import kaolin
ModuleNotFoundError: No module named 'kaolin.nnsearch'

During compiulation I got a lot of warning due to cython but no errors.

**Comment by justanhduc** [comment]
if you want to use the lib right away, you can install [torch_cluster](https://github.com/rusty1s/pytorch_cluster) and replace line 16 in kaolin/kaolin/metrics/point.py to:
`from torch_cluster import nearest as nn search`

**Comment by ToniRV** [comment]
#3

**Comment by krrish94** [comment]
Just trying to get a better sense. Was the build from a new `conda` environment?
