### ISSUE TITLE
Point Set Registration

### ISSUE THREAD

**Issue by mvandermerwe** [NVIDIAGameWorks/kaolin#50]
A useful feature would be strong baselines for point set registration, e.g., Iterative Closest Point, Coherent Point Drift, PointNetLK, FilterReg to name a few classics and recents.

**Comment by shumash** [comment]
Following restructuring with v0.9.0, Kaolin library does not include baselines or model training, but rather modular functions to support 3D DL. Thank you for the useful suggestions; we'll keep them in mind.

Here are the latest docs on Kaolin library and what it supports:
https://kaolin.readthedocs.io/en/latest/notes/overview.html
