### ISSUE TITLE
How to replace TriangleMesh.from_tensors   kaolin.rep  in v0.1?

### ISSUE THREAD

**Issue by 8468370** [NVIDIAGameWorks/kaolin#501]
Hi,

I want to use v0.9.1. Could you tell me how to replace TriangleMesh.from_tensor which is used in  in v0.1.

Thanks

**Comment by Caenorst** [comment]
Hi @8468370 ,

Thank you for your interest in Kaolin, you will see that in Kaolin for the moment we decided to drop the usage of TriangleMesh as the usage were often mixed with tensors. We may recreate a new high level class at some point. In the meanwhile you are free to implement your own, or just use the tensors `faces`, `vertices`...
