### ISSUE TITLE
Headless Rendering

### ISSUE THREAD

**Issue by andrearosasco** [NVIDIAGameWorks/kaolin#505]
Hi, is headless rendering supported on kaolin? I have to render and save some images on a remote server and it would be a useful feature.

**Comment by Caenorst** [comment]
Hi @andrearosasco !

Are you talking about the library? Because Kaolin library doesn't require any UI for rendering (so you can render on any remote server)

**Comment by andrearosasco** [comment]
Yep about the library! Why? Is there also a Kaolin application?

By the way, I asked because some other rendering libraries (e.g. open3d, pyrender, etc.) wouldn't normally let you do rendering if a screen isn't detected on the machine. To do so they require to be recompiled with specific flags and openmesa installed on the machine.

Well, that's great, thank you!
