### ISSUE TITLE
setup.py is getting hung after trying to find nv-usd-py36.

### ISSUE THREAD

**Issue by stephendb** [NVIDIAGameWorks/kaolin#51]
Setup.py is getting hung after trying to find nv-usd-py36.

Processing project file 'packman/target_deps.xml'
Package 'nv-usd-py36' at version '19.11.139.596f7aaf-linux-x86_64' is missing from local storage.
(hangs here)

Ubuntu 18.04

I had no trouble installing last Friday with a near identical build on another computer. Not sure why this is broken now. Can probably reproduce by nuking your packman-repo to simulate having a fresh setup and then running: `python setup.py install`

Other packman-repo packages are getting pulled and installed correctly for example:
Processing project file '/home/stephen/packman-repo/packman-common/6.1.3/deps.packman.xml'
Package '7za' at version '16.02.4' is missing from local storage.
Downloading from 'packman-bootstrap.s3.amazonaws.com': 7za@16.02.4.zip (4.33 MiB)
100.00% (speed 10.4 MiB/s)

Seems the url is no longer valid?

Edit*
I just downloaded and copied the files into the packman-repo and named the directory accordingly. Quick fix for anyone waiting for this to get fixed. Here's the file: https://developer.nvidia.com/usd

**Comment by halldorfannar** [comment]
Could you please try this command and see if it works:
```
wget https://public.packman.nvidia.com/nv-usd-py36%4019.11.139.596f7aaf-linux-x86_64.7z
```
This is effectively what packman is doing when pulling down the package.

**Comment by 96wangfeng** [comment]
> Could you please try this command and see if it works:
> 
> ```
> wget https://public.packman.nvidia.com/nv-usd-py36%4019.11.139.596f7aaf-linux-x86_64.7z
> ```
> 
> This is effectively what packman is doing when pulling down the package.

I have downloaded this package. There's not 'setup.py' for installation.How to install this package?

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and this issue is no longer current. 

Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

If you encounter issues, please file new bugs. Thanks!
