### ISSUE TITLE
IGNORE_TORCH_VER issue

### ISSUE THREAD

**Issue by etaoxing** [NVIDIAGameWorks/kaolin#510]
https://github.com/NVIDIAGameWorks/kaolin/blob/ac5bf684d89cdeefc17b0b082345bcb76b0ee69a/setup.py#L35-L44

I think L44 should be indented? So that `missing_modules` will not include torch if `IGNORE_TORCH_VER=1`.

**Comment by Caenorst** [comment]
Hi @etaoxing indeed that seems to be a mistake

**Comment by Caenorst** [comment]
Fixed in #519
