### ISSUE TITLE
Does trilinear interpolation in SPC calculate the gradient on grid too or it's only for features?

### ISSUE THREAD

**Issue by vahidEtt** [NVIDIAGameWorks/kaolin#530]

**Comment by tovacinni** [comment]
Thanks for your interest in Kaolin!

The backprop is only with respect to the features which exist on the grid. What do you mean by "gradient on the grid"?

**Comment by vahidEtt** [comment]
OK. Thanks. 

I was thinking the same thing as torch.grid_sampler that has gradient on both feature and grid.
