### ISSUE TITLE
f_score computation issue

### ISSUE THREAD

**Issue by shleecs** [NVIDIAGameWorks/kaolin#544]
Hello,

I have a question about the metric 'f_score'.

When I compute the f_score between p1 and p2 with different shapes(e.g. p1.shape: (1,955194,3), p2.shape (1,276953,3), it occurs runtime error because of shape mismatch.

I checked the document already, it seems to support the computation between points with different shapes.

I will be looking forward to your reply.

Thank you!

**Comment by JerryJiehanWang** [comment]
Hi @shleecs, we've fixed the problem in the most recent PR. Basically there was an error when handling with axis. You can have a look and test to see if it works again.
