### ISSUE TITLE
Rendering 

### ISSUE THREAD

**Issue by shersoni610** [NVIDIAGameWorks/kaolin#55]
Hello,

I was able to run the following command from the document:
>>> from kaolin.datasets import shapenet
>>> from torch.utils.data import DataLoader
>>> meshes = shapenet.ShapeNet_Meshes(root=shapenet_dir, categories=['plane'])

But do not know how to render the models as shown in the document. Can someone help?

**Comment by Jean-Francois-Lafleche** [comment]
Hi, you can try this:

```python
from kaolin.datasets import shapenet
from kaolin.rep import TriangleMesh
meshes = shapenet.ShapeNet_Meshes(root=shapenet_dir, categories=['plane'])
for sample in meshes:
    data = sample['data']
    mesh = TriangleMesh.from_tensors(data['vertices'], data['faces'])
    mesh.show()
```

**Comment by shersoni610** [comment]
Hello
Thank you very much. I had downloaded ShapeNetCore.v2 data and it seems
that the folders do not
have model.obj. Instead, they have files like:

model_normalized.json  model_normalized.obj  model_normalized.surface.binvox
model_normalized.mtl   model_normalized.solid.binvox


How do I change the code to see ShapeNetCore.v2 data?

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

Closing the bug as it is no longer relevant to this repo.
