### ISSUE TITLE
Multiple light source in a scene

### ISSUE THREAD

**Issue by Entongsu** [NVIDIAGameWorks/kaolin#552]
Hello,

Thank you for sharing this great project.

I have a question about the lighting setting. I wonder whether kaolin supports Multiple light source rendering in the same scene. Thank you!

**Comment by Caenorst** [comment]
Hi @Entongsu ! Thank you for your interest in Kaolin! Currently we support spherical harmonics which should be usable for multiple light sources. We are planning to add more related features, is there anything in particular that you are looking for?

**Comment by Entongsu** [comment]
Thank you for your reply. I wonder how many light sources that I can add in a scene. I am not very sure how to add multiple light sources in the same scene. Could you give me some hints over this? Thank you.

**Comment by Caenorst** [comment]
What do you want to do with those light sources?

**Comment by Entongsu** [comment]
I plan to render a scene with different light sources with different colors from different locations.

**Comment by Caenorst** [comment]
What renderer are you intending to use?

**Comment by Entongsu** [comment]
I want to use kaolin for the rasterizer and rendering.

**Comment by Caenorst** [comment]
Hi @Entongsu , we recently added spherical gaussian features for lighting, see:
- https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/diffuse_lighting.ipynb
- https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/sg_specular_lighting.ipynb

**Comment by shumash** [comment]
Closing inactive bug.
