### ISSUE TITLE
Problem about the tutorial 'understanding_spcs_tutorial.ipynb'

### ISSUE THREAD

**Issue by StarryN** [NVIDIAGameWorks/kaolin#553]
Firstly, Thanks for your work to open source such an excellent library. 
The tutorial 'understanding_spcs_tutorial.ipynb' may have a minor mistake. The max index of points belonging to level 1 should be 7 rather than 8.
![Screenshot from 2022-04-20 14-53-17](https://user-images.githubusercontent.com/8968747/164235362-426f7c9f-27a4-4193-b8cc-a36dda14a4a5.png)

**Comment by Caenorst** [comment]
Hi @StarryN , Thank you for your interest in Kaolin. We have addressed the issue in #570 .

Closing this issue.
