### ISSUE TITLE
is there anyone has installed kaolin successfully?could you tell me about  your software and hardware?

### ISSUE THREAD

**Issue by liujiacheng1009** [NVIDIAGameWorks/kaolin#56]
like ubuntu16,rtx2060,cuda 9.1, conda,pytorch 1.3...? the more the better

**Comment by Jean-Francois-Lafleche** [comment]
Kaolin is tested with Ubuntu 18.04, Cuda 10.1, python 3.6 and pytorch 1.2+. We are in the process of expanding our testing tools to ensure compatibility with more configurations. Could you please provide details on your setup? We can then try to replicate the issue and fix it. Thank you!

**Comment by liujiacheng1009** [comment]
my environment is rtx2070,ubuntu 18..04,cuda 10.2 pytorch 1.3.0,python 3.6.but got the error
`nvcc fatal   : Unsupported gpu architecture 'compute_75'`

> Kaolin is tested with Ubuntu 18.04, Cuda 10.1, python 3.6 and pytorch 1.2+. We are in the process of expanding our testing tools to ensure compatibility with more configurations. Could you please provide details on your setup? We can then try to replicate the issue and fix it. Thank you!

**Comment by ujjawalcse** [comment]
I also could not install kaolin.
I'm getting this error - error: **no commands supplied**.
My configuration is **RTX2070 Super**,**ubuntu18.04**, **cuda 10.1**, **pytorch 1.3.1**, **python 3.6.9**.

**Comment by krrish94** [comment]
There was a similar issue with RTX 2080Ti, which was fixed this way: https://github.com/NVIDIAGameWorks/kaolin/issues/31#issuecomment-557776519

Probably try this solution?
