### ISSUE TITLE
cuda_dir is None when run "python setup.py develop"

### ISSUE THREAD

**Issue by Xiaoyao-Li** [NVIDIAGameWorks/kaolin#561]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str' on line 105 File "setup.py" Raised when running "python setup.py develop"
Speculate may be the cuda_dir is None.

dependency:
numpy==1.22.2
torch==1.10.2+cu113
trimesh==3.9.34

**Comment by Caenorst** [comment]
Hi @Xiaoyao-Li , please provide the full logs so I can help you.

Can you tell me more about your system? (OS? GPU?)

**Comment by Xiaoyao-Li** [comment]
Hello @Caenorst , thanks for your reply. We fixed this issue now.
Our system: Windows11, RTX3050Ti Laptop
The issue description:
when executing `python setup.py develop`, may encounter this problem logged as:
```bash
Traceback (most recent call last):
    ...
    raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
This means that the program cannot find a CUDA library on the platform if someone installed CUDA following PyTorch Installation. Follow the instruction below to deal with it, contributed by @[YuyangLee](https://github.com/YuyangLee):
1. Install `CUDA Toolkits` and `cuDNN` Library.
2. Refer to [Kaolin Installation](https://kaolin.readthedocs.io/en/latest/notes/installation.html) to install `CUDA_INSTALLATION_PATH/`.
3. Add system Environment Variables.
5. Testing Installation.
