### ISSUE TITLE
module 'kaolin._C' has no attribute 'render'

### ISSUE THREAD

**Issue by vivcheng01** [NVIDIAGameWorks/kaolin#578]
<img width="565" alt="Screen Shot 2022-06-01 at 6 17 49 PM" src="https://user-images.githubusercontent.com/60167936/171527011-991af94f-b5d4-4e06-a4a0-58149fe8fe7d.png">

Hi, I am trying to run kaolin in a docker image. I'm using Cuda 10.2 and installing in the dockerfile using " 

"pip install git+https://github.com/NVIDIAGameWorks/kaolin@838d982cb0765de75d3c5de15083d80b849fa737"
Do you know why I keep running into the above error? Thanks!

**Comment by Caenorst** [comment]
Hi @vccheng2001 , thank you for your interest in Kaolin.

This is not the recommended way to install kaolin, please refer to https://kaolin.readthedocs.io/en/latest/notes/installation.html
