### ISSUE TITLE
NeuralMeshRenderer fails to find Lighting

### ISSUE THREAD

**Issue by kzmttr** [NVIDIAGameWorks/kaolin#58]
I am using kaolin.graphics.NeuralMeshRenderer.render() 
but it fails with the following error.

kaolin/graphics/NeuralMeshRenderer.py", line 293, in lighting
NameError: name 'Lighting' is not defined

NeuralMeshRenderer.py seems to import functions of Lighting.py,
but doesn't import Lighting.py itself.

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

Closing the bug as it is no longer relevant to this repo.
