### ISSUE TITLE
no module named 'dmtet_network''

### ISSUE THREAD

**Issue by pinjiang** [NVIDIAGameWorks/kaolin#584]
Complete Kaolin installation and verification:
" (kaolin) jiangpin@xxxx:~$ python -c "import kaolin; print(kaolin.__version__)"
0.11.0 ”

Following "Reconstructing Point Cloud with DMTet" tutorial , get error :

Traceback (most recent call last):
  File "kaolin_test.py", line 4, in <module>
    from dmtet_network import Decoder

**Comment by Caenorst** [comment]
Hi @pinjiang , thank you for your interest in Kaolin.

What is this `kaolin_test.py` file?

**Comment by pinjiang** [comment]
It's just test python script, tries to load dmtet_network module

**Comment by Caenorst** [comment]
I'm not sure what you are trying to do @pinjiang but `dmtet_network.py` is not part of the public API but a helper python module for the example.

**Comment by pinjiang** [comment]
The first step in "https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/dmtet_tutorial.ipynb"is : 
from dmtet_network import Decoder，I just try to follow the tutorial

**Comment by Caenorst** [comment]
`kaolin_test.py` is not part of the tutorial, the missing file is not part of kaolin as a module but part of the example
