### ISSUE TITLE
Error: Microsoft Visual C++ 14.0 or greater is required

### ISSUE THREAD

**Issue by mumesh10** [NVIDIAGameWorks/kaolin#586]
![image](https://user-images.githubusercontent.com/108412495/176452822-9a25d5c6-872c-4860-b0e0-b4d265eeb27b.png)

I am facing this error while installing on windows.

I am following this tutorial to setup kaolin library on my PC: https://youtu.be/BwZ7s7DqbFs

**Comment by Caenorst** [comment]
Hi @mumesh10 , thank you for you interest in Kaolin.

The video being 1 year old I would simply suggest to follow [our installation instructions](https://kaolin.readthedocs.io/en/latest/notes/installation.html). 

Looking at the error, this seems to be a pytorch dependency issue, i.e missing Microsoft Visual Studio, I suggest looking at tutorial for installing Microsoft Visual Studio or build tools, you might find some useful information [here](https://pytorch.org/docs/stable/notes/windows.html).

**Comment by mumesh10** [comment]
Is there a possibility that I am facing this issue because of my GPU AMD Radeon RX Vega 10 graphics?

**Comment by Caenorst** [comment]
I'm sorry mumesh10, we currently don't support AMD GPUs (and to my knowledge AMD GPUs are not very well supported by Pytorch)
