### ISSUE TITLE
A weird bug: The data is not on the same device.

### ISSUE THREAD

**Issue by caiyongqi** [NVIDIAGameWorks/kaolin#591]
> https://github.com/YuliangXiu/ICON/issues/93#issue-1306710028

**Comment by Caenorst** [comment]
Hi @caiyongqi that's indeed a weird bug, I'll have a look

**Comment by Caenorst** [comment]
Should be fixed!

**Comment by caiyongqi** [comment]
> Should be fixed!

Thanks!
