### ISSUE TITLE
Attempt to install on Windows

### ISSUE THREAD

**Issue by psx2** [NVIDIAGameWorks/kaolin#593]
I would like the developers of this repository to attempt to install on a fresh Windows.

One error leads to another, and another, and another... 

The installation instructions provided must be severely outdated. I followed them precisely, matching the exact dependencies, and have unable to get anywhere.

**Comment by Caenorst** [comment]
Hi @psx2 , we are currently working on setting up the windows CI, but I can tell that we have been able to install Kaolin on a windows machine without issue.

Usually Windows + pytorch is finicky, but we can't help you if you don't share more information about your system.

**Comment by DocSavage** [comment]
Not OP but I can give you some data on my Win install that kind of worked though I'll have to wait to see if detected errors are roadblocks.  This was a kaolin install within an [attempt to install wisp](https://github.com/NVIDIAGameWorks/kaolin-wisp#4-install-kaolin) using a new conda environment.

OS = Win 10 Enterprise, 21H2, OS build 19044.1889, running on VMWare vWS with nvidia licensing (VDI solution)
GPU = 3 x GRID RTX6000P-24Q.  Driver 472.39
Pytorch 1.12.1 via standard approach. However `nvcc --version` showed I was at CUDA 11.4 and only 11.3 was available via conda packages, which I presume can work with 11.4, so did `cudatoolkit=11.3`.
Python 3.8 installed when creating conda environment. Went with what Wisp install suggested.
Kaolin version HEAD (commit `54876e0`). When I tried doing checkout to `v0.12.0` ran into bug that seems to have been patched. Was syntax error in `kaolin\csrc\ops\mesh\mesh_intersection_cuda.cu`.  Will note that there were a lot of warnings and output when running `python setup.py develop` for kaolin install.

On doing `python -c "import kaolin; print(kaolin.__version__)"`:
```
C:\Users\X\Anaconda3\envs\wisp\lib\site-packages\scipy-1.7.2-py3.8-win-amd64.egg\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
0.12.0
```

Installed what was suggested for exhaustive checks via pytest.  For the most part it passed or skipped with a few exceptions:
```
tests\python\kaolin\io\test_modelnet.py EEEEEEEEEEEE                                                                                       [  0%]
...
tests\python\kaolin\io\test_shapenet.py EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE [  1%]
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE [  2%]
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE                                       [  3%]
tests\python\kaolin\io\test_shrec.py EEEEEEEEEEEEEEFFFFFFFEEEEEEEEEEEEEEFFFFFFFEEEEEEEEEEEEEEFFFFFFFEEEEEEEEEEEEEEFFFFFFF                  [  4%]
... (all other tests passed or were skipped)
... (lots of error dumps skipped)
________________________________________________ TestSHREC16.test_neg_index[-2-test-categories5] ________________________________________________

self = <test_shrec.TestSHREC16 object at 0x00000116DC9D6D60>, shrec16_dataset = <kaolin.io.shrec.SHREC16 object at 0x00000116802A5A60>, index = -2

    @pytest.mark.parametrize('index', [-1, -2])
    def test_neg_index(self, shrec16_dataset, index):

>       assert len(shrec16_dataset) > 0
E       assert 0 > 0
E        +  where 0 = len(<kaolin.io.shrec.SHREC16 object at 0x00000116802A5A60>)

tests\python\kaolin\io\test_shrec.py:88: AssertionError
________________________________________________ TestSHREC16.test_neg_index[-2-test-categories6] ________________________________________________

self = <test_shrec.TestSHREC16 object at 0x00000116DC9D6DF0>, shrec16_dataset = <kaolin.io.shrec.SHREC16 object at 0x0000011680311EB0>, index = -2

    @pytest.mark.parametrize('index', [-1, -2])
    def test_neg_index(self, shrec16_dataset, index):

>       assert len(shrec16_dataset) > 0
E       assert 0 > 0
E        +  where 0 = len(<kaolin.io.shrec.SHREC16 object at 0x0000011680311EB0>)

tests\python\kaolin\io\test_shrec.py:88: AssertionError
=============================================================== warnings summary ================================================================
...
ERROR tests/python/kaolin/io/test_shrec.py::TestSHREC16::test_neg_index[-2-val-categories5] - ValueError: Class 02691156 (['airplane', 'aeropla...
ERROR tests/python/kaolin/io/test_shrec.py::TestSHREC16::test_neg_index[-2-val-categories6] - ValueError: Class 02691156 (['airplane', 'aeropla...
=========================== 28 failed, 12596 passed, 1024 skipped, 108337 warnings, 404 errors in 1706.10s (0:28:26) ============================
```

**Comment by Caenorst** [comment]
Thanks @DocSavage for sharing your configs.

The errors are expected since you don't have the datasets at the specific location, if you set `CI` environment variable to `'true'` those test should be ignored
