### ISSUE TITLE
Confused about the x0 and y0 in PinholeIntrinsics() class

### ISSUE THREAD

**Issue by pableeto** [NVIDIAGameWorks/kaolin#609]
Hi,
Thanks for releasing this great library!
I am a little bit confused about the definition of x0 and y0 in PinholeIntrinsics(). According to the API documentation, it says
```
x0 (optional, [float](https://docs.python.org/3/library/functions.html#float)) – horizontal origin of the image plane. Default: 0.

y0 (optional, [float](https://docs.python.org/3/library/functions.html#float)) – vertical origin of the image place. Default: 0.
```
Which from my understanding, it basic says "x0 and y0 stands for the cx and cy in pinhole cameras".

However, it seems x0 and y0 actually refer to the "offset" of the origin of the image plane, but not the origin itself, as described and used in line 218 of nerf_standard.py:
```
    # The principal point in wisp are always a displacement in pixels from the center of the image.
    x0 = 0.0
    y0 = 0.0
    # The standard dataset generally stores the absolute location on the image to specify the principal point.
    # Thus, we need to scale and translate them such that they are offsets from the center.
    if 'cx' in transform_dict[split]:
        x0 = (float(transform_dict[split]['cx']) / (2**mip)) - (w//2)
    if 'cy' in transform_dict[split]:
        y0 = (float(transform_dict[split]['cy']) / (2**mip)) - (h//2)
```

As a lot of people might suffer from converting coordinate systems from different data representations, maybe some further clarification might be useful? Please point out if I have some wrong understanding:)

**Comment by orperel** [comment]
Hi @pableeto !
Your understanding is correct: kaolin's definition of x0, y0 should be the principal point **offset** from the origin, which by default is defined at the center of the canvas:
https://github.com/NVIDIAGameWorks/kaolin/blob/9085d1454c041b6300afc95ab6320e729430bb81/kaolin/render/camera/intrinsics_pinhole.py#L474

Hence the wisp documentation is correct, and the Kaolin documentation you cited should be revised.
Thanks for pointing this one out!

**Comment by pableeto** [comment]
Thanks @orperel for the clarification! :)
