### ISSUE TITLE
GoBig out-of-index

### ISSUE THREAD

**Issue by Cainor** [NVIDIAGameWorks/kaolin#618]
Once I clicked on "Process" it started the first image for GoBig upscale I got the result below: 

![image](https://user-images.githubusercontent.com/36992322/188040379-37f5cda5-a6b5-4d67-9d28-917494e27eef.png)

**Comment by Caenorst** [comment]
Hi @Cainor I'm sorry I don't understand your issue, what does it have to do with Kaolin?

**Comment by Cainor** [comment]
Oh my god .. I’m really sorry.

Got too many repos open in my browser and got it mixed up. Really sorry for the inconvenience.
