### ISSUE TITLE
Is there any one could provide the `obj` file which be rendered in `clock_rendered.zip`

### ISSUE THREAD

**Issue by Matt-V50** [NVIDIAGameWorks/kaolin#624]
@Caenorst 

Could you put a link to the original `clock.obj`?

I wanna re-render it with other software to compare them.

`clock_rendered.zip` could be downloaded at [here](https://github.com/NVIDIAGameWorks/kaolin/blob/4d8f49dd3e617cb1fec3e2c2bc3b2903ff952321/examples/samples/rendered_clock.zip).

**Comment by Caenorst** [comment]
Hi @FavorMylikes , thank you for your interest in Kaolin, here is the dataset we used https://graphics.pixar.com/usd/release/dl_kitchen_set.html

**Comment by Matt-V50** [comment]
@Caenorst 
Thank you for responding. But this data is `usd` format, I'm trying to find a way to convert it to an `obj` file, do you have any suggestions?

**Comment by Caenorst** [comment]
We do not offer obj exporter, what software are you using? The tutorial generate an USD checkpoint for you, you can do the comparison in Omniverse

**Comment by Matt-V50** [comment]
@Caenorst 
Due to the hardware requirement of kaolin, I can not run it on my computer with only one 1060ti GPU.
I just found a way to load the `.usd` file on `Blender` and convert it to a file with `obj` format.
But I still can not understand what's the meaning of the `metadata` file which in `rendered_clock.zip`.
It looks like a 4x4 matrix, but why the translation vector is the same [0,0,0], whether it's a camera or an object?
Is there any documentation that could give more explanation? I have already read the doc on [Kaolin Library Documentation](https://kaolin.readthedocs.io/en/latest/index.html#welcome-to-kaolin-library-documentation)

**Comment by Caenorst** [comment]
Hi @FavorMylikes , you can find how we are using the metadata in our loader: https://github.com/NVIDIAGameWorks/kaolin/blob/master/kaolin/io/render.py#L106-L125
