### ISSUE TITLE
shapenet voxels

### ISSUE THREAD

**Issue by JTT94** [NVIDIAGameWorks/kaolin#629]
Hello, 

I saw in the docs "Kaolin supports multiple formats in which you can load a ShapeNet class (eg. meshes, pointclouds, voxels, " at https://kaolin.readthedocs.io/en/v0.1/notes/datasets_tutorial.html

However I can no longer find the dataset object  shapenet.ShapeNet_Voxels. Has this been depreciated?

**Comment by Caenorst** [comment]
Hi @JTT94 thanks for you interest in Kaolin, as you can see from the URL this is 0.1 version of Kaolin, we indeed dropped this "dataset" but it's very easy to reproduce by applying a [CachedDataset](https://kaolin.readthedocs.io/en/latest/modules/kaolin.io.dataset.html#kaolin.io.dataset.CachedDataset) on our [ShapeNet datasets](https://kaolin.readthedocs.io/en/latest/modules/kaolin.io.shapenet.html)

**Comment by JTT94** [comment]
Thank you for your response. 

I do not see how the cachedataset provides voxels? 

Ultimately, is it possible to get voxels and corresponding texture coordinates for shapenet using kaolin?

**Comment by jiazhou2023** [comment]
I am also interest if Kaolin support voxels with texture.
