### ISSUE TITLE
About kaolin-mesh-DIBR to render a scene with multi OBJ

### ISSUE THREAD

**Issue by lai-pf** [NVIDIAGameWorks/kaolin#637]
I need kaolin-mesh-DIBR to render a scene with multi mesh objects. And I have try this way in previous 
 https://github.com/NVIDIAGameWorks/kaolin/issues/267#issuecomment-633305199
It seems that batch rendering should be support in 2020？but I havn't seen relative version.
can you show me the correct method to render a scene with multi mesh objects? thanks

**Comment by lai-pf** [comment]
the method in https://github.com/NVIDIAGameWorks/kaolin/issues/267#issuecomment-633305199  has tried
but this method may lead all the objects in one coordinate system and share one zero point.  This leads my rotation can not be the local rotation which centered in the assigned object. It can only be the global rotation centered in global system zero point, even if I just want to rotate the assigned obj.

**Comment by Caenorst** [comment]
Hi @lai-pf, I'm confused by what you are trying to do, are you rendering a single scene with multiple meshes? Or a multiple scene with one mesh per scene?

**Comment by lai-pf** [comment]
> Hi @lai-pf, I'm confused by what you are trying to do, are you rendering a single scene with multiple meshes? Or a multiple scene with one mesh per scene?

Hi,Caenorst
I 've met two question while using kaolin in my work.

1.    I want to use kaolin to render two meshes(mesh-A,mesh-B) in one scene. I use the gradient to guide the  mesh-A to translate and rotate,  so that mesh-A should learn it's proper position.  
But use concat way https://github.com/NVIDIAGameWorks/kaolin/issues/267#issuecomment-633305199 to merge two meshes as one mesh, they will share one coordinate system and the rotation learned from gradient would be global rotation, not the local rotation in mesh-A's coordinate system. Are there any way can render two meshes in one scene,not in concat way.
2.    about the randomness. Are there any randomness in kaolin rendering?
I follow a paper which use kaolin as render, although I have fixed all the seed, I found it's gradient are not the same. It seems that gradient in backward is different leads to different optimization results. Are this randomness comes from kaolin render?
![image](https://user-images.githubusercontent.com/32856760/197378892-dc25f647-d165-4801-a875-e48040b2abb3.png)
In the process of optimization，little randomness in iteration one can make the optimization results really different.
we use cuda as rast-backend in DIBR function. 
![image](https://user-images.githubusercontent.com/32856760/197379058-5f817d2c-3a5b-4014-b7e5-82d63eb97967.png)
I found the issue about randomness in nvdiffrast  https://github.com/NVlabs/nvdiffrast/issues/13#issuecomment-767484493
but my code use the cuda rast-backend not the nvdiffrast. So I just want to know that are this randomness comes from kaolin
and Inevitable？ or this randomness comes from my code part?
thanks very much, I would appreciate it if you could answer my question, this can be really helpful.

**Comment by Caenorst** [comment]
I’m gonna adress 1) if you don’t mind opening a new issue for 2) for reference for other users (in short I don’t think our renderer has any non-determinism)

The method suggested in #267 works for rendering multiple object. If you want to learn the rotation / translation of one object, just apply a parametrized rotation / translation to the mesh before doing the step suggested in #267 .

I suggest having a look at our CameraExtrinsics class

**Comment by lai-pf** [comment]
> 

thanks, I think I've known the answer of question one. and I've submit a new issue about the question two the randomness.
