### ISSUE TITLE
Here looks like have lots of memory waste.

### ISSUE THREAD

**Issue by Matt-V50** [NVIDIAGameWorks/kaolin#639]
I load a simplified model which has almost 50k vertices. And there is an `OOM`.

Here is the key code. It limits kaolin to rendering large models.

https://github.com/NVIDIAGameWorks/kaolin/blob/bcce7a95506847b3ced48fcfc3207f61488dcb42/kaolin/ops/mesh/mesh.py#L116

Is there any plan for improvement?

**Comment by Caenorst** [comment]
Hi @FavorMylikes , Thank you for your interest in Kaolin and good catch!

We might be able to optimize this by using [torch.diagonal](https://pytorch.org/docs/stable/generated/torch.diagonal.html). I will try to test it on my side but do give it a try for your own use case! :)

**Comment by Caenorst** [comment]
Adressed, please try the updated version!
