### ISSUE TITLE
Npz files

### ISSUE THREAD

**Issue by Siziff** [NVIDIAGameWorks/kaolin#640]
Hi everyone ^_^
I don't quite understand the logic of creating an nzp file and how do I make the same one with a higher resolution? I am trying to run the DMtet algorithm on my data and it works every other time showing the following error:
File "test_kaolin.py", line 203, in kao
    loss = loss_f(mesh_verts, mesh_faces, points, it)
  File "test_kaolin.py", line 180, in loss_f
    pred_points = kaolin.ops.mesh.sample_points(mesh_verts.unsqueeze(0), mesh_faces, 70000)[0][0]
  File "/dsk1/kaolin/kaolin/ops/mesh/trianglemesh.py", line 215, in sample_points
    face_dist = torch.distributions.Categorical(areas)
  File "/root/miniconda3/envs/kaolin/lib/python3.7/site-packages/torch/distributions/categorical.py", line 64, in __init__
    super(Categorical, self).__init__(batch_shape, validate_args=validate_args)
  File "/root/miniconda3/envs/kaolin/lib/python3.7/site-packages/torch/distributions/distribution.py", line 56, in __init__
    f"Expected parameter {param} "
ValueError: Expected parameter probs (Tensor of shape (1, 0)) of distribution Categorical(probs: torch.Size([1, 0])) to satisfy the constraint Simplex(), but found invalid values:
tensor([], device='cuda:0', size=(1, 0), grad_fn=<DivBackward0>)
 
How to fix this error ?

**Comment by Caenorst** [comment]
Hi @Siziff , thank you for your interest in Kaolin.

I assume you are talking about the grid tets, as specified in the notebook we are using [Quartet](https://github.com/crawforddoran/quartet) to generate the grid.

I unfortunately can't help you without a code to reproduce your issue.

**Comment by Siziff** [comment]
@Caenorst Thanks for the answer, I'm trying to run a file dmtet_tutorial.ipynb to convert a point cloud into a mesh and I get a ball .why it's happened? I just consistently run your guide and get the ball instead of bear...

**Comment by Caenorst** [comment]
@Siziff just tested the tutorial again and can confirm the model converge to a bear, make sure to visualize the last iteration, not the first

**Comment by Siziff** [comment]
@Caenorst Thank you very much, if you run your script not in a notebook, then only the first result is recorded, I fixed this error and now I see the result. Thank you:)

**Comment by GKCsdfsGKC** [comment]
> @Caenorst Thank you very much, if you run your script not in a notebook, then only the first result is recorded, I fixed this error and now I see the result. Thank you:)

Hello, can you tell me how to generate the two npz files ?
Thank you!
