### ISSUE TITLE
Kaolin built without CUDA

### ISSUE THREAD

**Issue by Siziff** [NVIDIAGameWorks/kaolin#654]
Hi , @Caenorst ) I checked all the dependencies and the availability of CUDA versions , but kaolin is still installed without a GPU , what could be the problem?? i'm trying to use DMTet tutorial. 
![image](https://user-images.githubusercontent.com/42972554/202120784-78c15e72-636e-4d92-b572-7be21a75729d.png)

![image](https://user-images.githubusercontent.com/42972554/202120045-cad55bbe-f983-4118-b1c7-d2f8fd93586d.png)
![image](https://user-images.githubusercontent.com/42972554/202120151-5eaed5ac-e69c-4af1-b7b9-fe8427153f74.png)
![image](https://user-images.githubusercontent.com/42972554/202121744-13d441c9-f548-4300-b59d-75932b795da9.png)

**Comment by Caenorst** [comment]
Hi @Siziff , I suggest to clean your local repo (remove `build/`, `kaolin._C.so`) and reinstall and copy the installation logs (if you still have issues)

**Comment by gushengbo** [comment]
Hello, @Siziff , Have you solve this problem?

**Comment by shumash** [comment]
Closing inactive bug.
