### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by auk003150** [NVIDIAGameWorks/kaolin#655]
I have followed the stable version in the installation page https://kaolin.readthedocs.io/en/stable/notes/installation.html, and I have this issue

C:\Users\miche\kaolin>python setup.py develop
setup.py:37: UserWarning: Kaolin is compatible with PyTorch >=1.5.0, <=1.11.0, but found version 1.12.1+cu113. Continuing with the installed version as IGNORE_TORCH_VER is set.
  f'Kaolin is compatible with PyTorch >={TORCH_MIN_VER}, <={TORCH_MAX_VER}, '
Traceback (most recent call last):
  File "setup.py", line 300, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 218, in get_extensions
    include_dirs = get_include_dirs()
  File "setup.py", line 270, in get_include_dirs
    _, bare_metal_major, _ = get_cuda_bare_metal_version(CUDA_HOME)
  File "setup.py", line 105, in get_cuda_bare_metal_version
    raw_output = subprocess.check_output([cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Please review and help for this issue. Thanks a lot to anyone who may solve it.

**Comment by DopeorNope-Lee** [comment]
In this case, CUDA_HOME us not defined yet. 
It means, there is path problem or not installed CUDA yet.
So, If you appropriate install CUDA, then see the envs path..!

Good Luck

**Comment by auk003150** [comment]
Thanks! @dopeornope-Lee 

And now I have another issue 
```
C:/Users/miche/AppData/Local/Programs/Python/Python37/lib/site-packages/torch/include\ATen/record_function.h(19): warning: modifier is ignored on an enum specifier

Error: Internal Compiler Error (codegen): "there was an error in verifying the lgenfe output!"

error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\bin\\nvcc.exe' failed with exit status 2
```

I searched online and those answers said it will show a specific file uncapable, but I can't see it from the output.

**Comment by Caenorst** [comment]
Hi @auk003150 , please provide full logs

**Comment by shumash** [comment]
Closing inactive bug. 

Note: kaolin now comes with pre-built wheels.
