### ISSUE TITLE
cannot import name '_C' from 'kaolin'

### ISSUE THREAD

**Issue by MikePelton** [NVIDIAGameWorks/kaolin#664]
Hi - have followed the installation instructions for Windows and am falling at the first fence, trying the
python -c "import kaolin; print(kaolin.__version__)
test. I'm no stranger to conda, CUDA etc. so this is presumably me doing something dumb - any words of wisdom gratefully received!

**Comment by Caenorst** [comment]
Hi @MikePelton ,

Can you provide me a little bit more information such as the installation logs and the exact logs of when you are doing `import kaolin`?

Also can you tell me more about your system? GPU / python version / pytorch  version / OS

Thanks!

**Comment by MikePelton** [comment]
Hi and thanks for coming back so quickly. I am following the[ installation instructions](url) on Windows 10 22H2, GPU is an A6000, working in a conda environment with Python 3.7 and CUDA toolkit 11.6 (so not 11.3 as suggested - this could be an issue of course). I'm now away from the machine annoyingly so can't get you the logs. If nothing springs to mind for you immediately I'll get you better data on Monday, I'll also try an install on Ubuntu 22.04 then.

**Comment by Caenorst** [comment]
Unfortunately without the logs it's gonna be very hard, by the look of the error message, the build failed (this `_C` module is the basically the C++/CUDA pybinded module)

**Comment by MikePelton** [comment]
All good - will swap 11.6 out for 11.3 on Monday and rebuild, will let you know how I get on. If you want to close this issue feel free - if I'm still struggling on Monday I'll open a new issue then. Thanks for your help thus far  - fingers crossed I'll be able to leave you in peace!

**Comment by MikePelton** [comment]
No problem at all building on Ubuntu 22.04 with CUDA 11.3 (apart from having to downgrade gcc and g++ to version 9 - in case that's alien to other readers the instructions [here ](https://linuxconfig.org/how-to-switch-between-multiple-gcc-and-g-compiler-versions-on-ubuntu-20-04-lts-focal-fossa)are good). If someone manages to get this to build under Windows please could they document their environment as I hit several roadblocks - Visual Studio 2019 Community is required for example - VS2022 Community won't work with CUDA 11.3 - but as Windows isn't essential for us I threw in the towel after some hours' trying.

**Comment by Caenorst** [comment]
Pytorch has been notoriously difficult to use with Windows, while we are trying our best to support Windows (we have a CI section dedicated to it) there are just too many variable, in case you still want to try with Windows, I suggest looking at our dockerfile: https://github.com/NVIDIAGameWorks/kaolin/blob/master/tools/windows/Dockerfile .

Closing but feel free to reopen if you have more questions
