### ISSUE TITLE
the error when install kaolin, nvcc?

### ISSUE THREAD

**Issue by gushengbo** [NVIDIAGameWorks/kaolin#674]
@Caenorst 

Excuse me, my error when I setup kaolin is following:

WARNING - Including default CUB_HOME (/home/shengbo/ICON-master/kaolin/third_party/cub).
Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
Compiling kaolin/cython/ops/mesh/triangle_hash.pyx because it changed.
Compiling kaolin/cython/ops/conversions/mise.pyx because it changed.
[1/2] Cythonizing kaolin/cython/ops/conversions/mise.pyx
/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/shengbo/ICON-master/kaolin/kaolin/cython/ops/conversions/mise.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
warning: kaolin/cython/ops/conversions/mise.pyx:90:33: Not all members given for struct 'Voxel'
warning: kaolin/cython/ops/conversions/mise.pyx:90:33: Not all members given for struct 'Voxel'
warning: kaolin/cython/ops/conversions/mise.pyx:284:33: Not all members given for struct 'Voxel'
warning: kaolin/cython/ops/conversions/mise.pyx:284:33: Not all members given for struct 'Voxel'
[2/2] Cythonizing kaolin/cython/ops/mesh/triangle_hash.pyx
/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/shengbo/ICON-master/kaolin/kaolin/cython/ops/mesh/triangle_hash.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
INFO - running develop
/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
INFO - running egg_info
INFO - writing kaolin.egg-info/PKG-INFO
INFO - writing dependency_links to kaolin.egg-info/dependency_links.txt
INFO - writing requirements to kaolin.egg-info/requires.txt
INFO - writing top-level names to kaolin.egg-info/top_level.txt
/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
INFO - reading manifest template 'MANIFEST.in'
INFO - adding license file 'LICENSE'
INFO - writing manifest file 'kaolin.egg-info/SOURCES.txt'
INFO - running build_ext
INFO - building 'kaolin._C' extension
INFO - gcc -pthread -B /home/shengbo/anaconda3/envs/icon/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -I/home/shengbo/ICON-master/kaolin/third_party/cub -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/TH -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shengbo/anaconda3/envs/icon/include/python3.8 -c kaolin/csrc/bindings.cpp -o build/temp.linux-x86_64-cpython-38/kaolin/csrc/bindings.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
INFO - gcc -pthread -B /home/shengbo/anaconda3/envs/icon/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -I/home/shengbo/ICON-master/kaolin/third_party/cub -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/TH -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shengbo/anaconda3/envs/icon/include/python3.8 -c kaolin/csrc/metrics/sided_distance.cpp -o build/temp.linux-x86_64-cpython-38/kaolin/csrc/metrics/sided_distance.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
INFO - /usr/local/cuda/bin/nvcc -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -I/home/shengbo/ICON-master/kaolin/third_party/cub -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/TH -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shengbo/anaconda3/envs/icon/include/python3.8 -c kaolin/csrc/metrics/sided_distance_cuda.cu -o build/temp.linux-x86_64-cpython-38/kaolin/csrc/metrics/sided_distance_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
INFO - gcc -pthread -B /home/shengbo/anaconda3/envs/icon/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -I/home/shengbo/ICON-master/kaolin/third_party/cub -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/TH -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shengbo/anaconda3/envs/icon/include/python3.8 -c kaolin/csrc/metrics/unbatched_triangle_distance.cpp -o build/temp.linux-x86_64-cpython-38/kaolin/csrc/metrics/unbatched_triangle_distance.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
INFO - /usr/local/cuda/bin/nvcc -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -I/home/shengbo/ICON-master/kaolin/third_party/cub -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/TH -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shengbo/anaconda3/envs/icon/include/python3.8 -c kaolin/csrc/metrics/unbatched_triangle_distance_cuda.cu -o build/temp.linux-x86_64-cpython-38/kaolin/csrc/metrics/unbatched_triangle_distance_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
INFO - gcc -pthread -B /home/shengbo/anaconda3/envs/icon/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -I/home/shengbo/ICON-master/kaolin/third_party/cub -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/TH -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shengbo/anaconda3/envs/icon/include/python3.8 -c kaolin/csrc/ops/conversions/mesh_to_spc/mesh_to_spc.cpp -o build/temp.linux-x86_64-cpython-38/kaolin/csrc/ops/conversions/mesh_to_spc/mesh_to_spc.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
INFO - /usr/local/cuda/bin/nvcc -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -I/home/shengbo/ICON-master/kaolin/third_party/cub -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/TH -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shengbo/anaconda3/envs/icon/include/python3.8 -c kaolin/csrc/ops/conversions/mesh_to_spc/mesh_to_spc_cuda.cu -o build/temp.linux-x86_64-cpython-38/kaolin/csrc/ops/conversions/mesh_to_spc/mesh_to_spc_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
INFO - gcc -pthread -B /home/shengbo/anaconda3/envs/icon/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -I/home/shengbo/ICON-master/kaolin/third_party/cub -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/TH -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shengbo/anaconda3/envs/icon/include/python3.8 -c kaolin/csrc/ops/conversions/unbatched_mcube/unbatched_mcube.cpp -o build/temp.linux-x86_64-cpython-38/kaolin/csrc/ops/conversions/unbatched_mcube/unbatched_mcube.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
INFO - /usr/local/cuda/bin/nvcc -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -I/home/shengbo/ICON-master/kaolin/third_party/cub -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/TH -I/home/shengbo/anaconda3/envs/icon/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/shengbo/anaconda3/envs/icon/include/python3.8 -c kaolin/csrc/ops/conversions/unbatched_mcube/unbatched_mcube_cuda.cu -o build/temp.linux-x86_64-cpython-38/kaolin/csrc/ops/conversions/unbatched_mcube/unbatched_mcube_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 -DWITH_CUDA -DTHRUST_IGNORE_CUB_VERSION_CHECK -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++14
kaolin/csrc/ops/conversions/unbatched_mcube/unbatched_mcube_cuda.cu(659): error: more than one instance of overloaded function "log2" matches the argument list:
            function "log2(double)"
            function "log2(float)"
            argument types are: (int)

kaolin/csrc/ops/conversions/unbatched_mcube/unbatched_mcube_cuda.cu(660): error: more than one instance of overloaded function "log2" matches the argument list:
            function "log2(double)"
            function "log2(float)"
            argument types are: (int)

kaolin/csrc/ops/conversions/unbatched_mcube/unbatched_mcube_cuda.cu(661): error: more than one instance of overloaded function "log2" matches the argument list:
            function "log2(double)"
            function "log2(float)"
            argument types are: (int)

3 errors detected in the compilation of "/tmp/tmpxft_000036b9_00000000-6_unbatched_mcube_cuda.cpp1.ii".
error: command '/usr/local/cuda/bin/nvcc' failed with exit code 1

my torch is 1.10.0, CUDA 10.2

when I run nvcc, I got a error, 
The program 'nvcc' is currently not installed. To run 'nvcc' please ask your administrator to install the package 'nvidia-cuda-toolkit'

It seems that I have no nvcc?

**Comment by Caenorst** [comment]
@gushengbo please reply under the existing issue don’t open new issue.

Closing
