### ISSUE TITLE
Support for python 3.10?

### ISSUE THREAD

**Issue by ubt0001** [NVIDIAGameWorks/kaolin#689]
The document says kaolin doesn't support python 3.10 yet. Will it be ported to python 3.10?

**Comment by ubt0001** [comment]
https://github.com/PixarAnimationStudios/USD/issues/1857

**Comment by ubt0001** [comment]
According to the link above, maybe usd-core on python 3.10 is no longer a blocker?

**Comment by shumash** [comment]
We added support.
