### ISSUE TITLE
assert download, f'ShapeNet Images are not found, and download is set to False'

### ISSUE THREAD

**Issue by ArmanAstudUc3m** [NVIDIAGameWorks/kaolin#7]
Hi,

Once i've installed kaolin pkg (without errors), and try to import kaolin, i get the following assert error:

![image](https://user-images.githubusercontent.com/56833420/68939226-5dea0100-07a0-11ea-95a6-9fb89d9bfc96.png)

My Setup:
- conda env w/ Python 3.5.6
- tensorRT 5.0

Do you have any idea to solve this problem?
Thanks for your great work!

**Comment by Jean-Francois-Lafleche** [comment]
Hi, please upgrade to Python 3.6 or above. I see you're using Anaconda, you can upgrade your python version by running `conda install python=3.6`. 

F-strings (used in that line) are not supported in python < 3.5.

**Comment by VictorZuanazzi** [comment]
I could not make it work with Python 3.7. So make sure that you environment is using python 3.6.9
