### ISSUE TITLE
Wrong ShapeNet surface extraction 

### ISSUE THREAD

**Issue by EdwardSmith1884** [NVIDIAGameWorks/kaolin#70]
https://github.com/NVIDIAGameWorks/kaolin/blob/e65450a4e6edee526fde435cf3f2cebbecae8fda/kaolin/datasets/shapenet.py#L389

I am not sure that this is doing what it is supposed to, in that I don't think it guarantees a watertight mesh with no interior structure. To clarify the order of operations should be: 
1. Convert high resolution voxel grid from mesh 
2. Extract a low resolution voxel grid from  the high resolution voxel grid 
3. Up sample the low resolution voxel grid to the same size as the high resolution voxel grid 
4. Extract ODMs from the high resolution voxel grids
5. Apply the ODMs to the upsampled voxel gird 
6. Convert the result back to a Mesh

**Comment by Jean-Francois-Lafleche** [comment]
Thanks Edward. The current conversion procedure is unchanged from the original implementation:
1. Convert mesh to voxel at resolution `res`. (this involves conversion to voxel, filling voxel grid, extracting and projecting ODMs)
2. Convert Voxel to Mesh
3. Apply Laplacian Smoothing to mesh
4. Realign mesh to original mesh.

What you're proposing, if I understand correctly, is to to add a Downsample-Upsample step before extracting ODMs. I assume this is to fill in holes in the mesh, but I wonder if the `fill` method currently used does not end up doing this in a different way?

**Comment by EdwardSmith1884** [comment]
So that would be true if the meshes were watertight. The down and upsampling is to compensate for the fact that are often not. If the meshes are not watertight then the fill will not work as a hole would mean that in voxel space the intended interior space is not distinguishable from the exterior.  The downsampling at a low enough resolution makes the holes disappear in voxel space ( see section C of the supplemental [here](https://arxiv.org/pdf/1802.09987.pdf) ). If you could find another way to force the meshes to be watertight that this would also work.

**Comment by shumash** [comment]
This issue is no longer relevant to current version of the library. Closing.

Latest docs: https://kaolin.readthedocs.io/en/latest/notes/overview.html
