### ISSUE TITLE
How to export mesh to `.obj` format?

### ISSUE THREAD

**Issue by Ir1d** [NVIDIAGameWorks/kaolin#700]
Currently kaolin supports loading mesh from `.obj` and writing mesh to `usd`. I wonder how to output obj format mesh. Thanks!

**Comment by Caenorst** [comment]
Hi @Ir1d , what is your use case?

**Comment by shumash** [comment]
Sorry, we are not planning to support a full-featured obj exporter as there are other libraries out there that do this.
