### ISSUE TITLE
Documentation is incomplete

### ISSUE THREAD

**Issue by aniket-agarwal1999** [NVIDIAGameWorks/kaolin#71]
Hi,
The documentation seems to be pretty incomplete with most of the sections written as under development. Would love if it could be updated soon,
Thanks!

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

Closing the bug as it is no longer relevant to this repo.
