### ISSUE TITLE
Package manager not able to install Kaolin

### ISSUE THREAD

**Issue by zaiisao** [NVIDIAGameWorks/kaolin#711]
Hello, I am working on a project that uses Kaolin and have been using the following command without any issues -- at least, until just a couple of days ago.

```pip install kaolin==0.12.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.1_cu113.html```

However, this ended up in an installation error:

> Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
> Looking in links: https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.1_cu113.html
> ERROR: Could not find a version that satisfies the requirement kaolin==0.12.0 (from versions: 0.0)
> ERROR: No matching distribution found for kaolin==0.12.0

It is strange, mainly because this exact same command worked just a couple of days ago.

I ended up trying a Kaolin installation without the version number specification (i.e. removing the `==0.12.0` from the above command). This ended up installing version 0.0 of Kaolin which I was able to verify when running `pip list`.

As a result, I cloned this GitHub repo and compiled the package on my own, which ended up working. As a result, there seems to be something wrong with the package manager, or the amazonaws link that is used above (although I'm not an expert on how these package managers work, so my assessment might have some problems).

**Comment by aegonwolf** [comment]
I have the same issue, I'll try cloning the repo, thanks, edit: can you use the latest version like that? I am getting an import error no Module ipyevents when installing via cloning the repo

**Comment by zaiisao** [comment]
I'm not sure as I didn't get such an error when installing running installation via `python setup.py install`.

**Comment by Caenorst** [comment]
Hi, can you check your python version? We currently only support python from 3.7 to 3.9 (will support 3.10 in the next release). Please open a separate issue for the ipyevents version issue.

**Comment by olokobayusuf** [comment]
@Caenorst any ETA on the next release with Python 3.10 support?

**Comment by odusseys** [comment]
The documentation says 3.10 is supported but I am getting the same error.

**Comment by shumash** [comment]
Python 3.10 is currently supported. Please reopen if running into issues with latest wheels and within our supportrange.
