### ISSUE TITLE
RROR: Could not find a version that satisfies the requirement kaolin==0.13.0 (from versions: 0.0) ERROR: No matching distribution found for kaolin==0.13.0

### ISSUE THREAD

**Issue by dellshan** [NVIDIAGameWorks/kaolin#712]
RROR: Could not find a version that satisfies the requirement kaolin==0.13.0 (from versions: 0.0)
ERROR: No matching distribution found for kaolin==0.13.0

**Comment by dellshan** [comment]
(base) [yshan@neptune5 textured-3d-gan]$ pip install kaolin==0.13.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.0.0+cu117_cu117.html
Looking in links: https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.0.0+cu117_cu117.html
ERROR: Could not find a version that satisfies the requirement kaolin==0.13.0 (from versions: 0.0)
ERROR: No matching distribution found for kaolin==0.13.0
(base) [yshan@neptune5 textured-3d-gan]$ pip install kaolin==0.13.0
ERROR: Could not find a version that satisfies the requirement kaolin==0.13.0 (from versions: 0.0)
ERROR: No matching distribution found for kaolin==0.13.0
(base) [yshan@neptune5 textured-3d-gan]$ pip install kaolin==0.13.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.1_cu113.html
Looking in links: https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.1_cu113.html
ERROR: Could not find a version that satisfies the requirement kaolin==0.13.0 (from versions: 0.0)
ERROR: No matching distribution found for kaolin==0.13.0
(base) [yshan@neptune5 textured-3d-gan]$ pip install kaolin==0.13.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.0.0_cu117.html
Looking in links: https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.0.0_cu117.html
ERROR: Could not find a version that satisfies the requirement kaolin==0.13.0 (from versions: 0.0)
ERROR: No matching distribution found for kaolin==0.13.0

**Comment by dellshan** [comment]
It seems by use PIP, the kaolin==0.13.0 is not exist there ?  why this error happen there ?????

**Comment by dellshan** [comment]
Title: Unable to install Kaolin 0.13.0 on Red Hat 8.6 with Python 3.10.9

Description:
I am unable to install Kaolin 0.13.0 on my system, which is running Red Hat 8.6 and Python 3.10.9. I have tried installing the package using the following command:

bash
Copy code
pip install kaolin==0.13.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.0.0+cu117_cu117.html
However, this results in the following error:

yaml
Copy code
ERROR: Could not find a version that satisfies the requirement kaolin==0.13.0 (from versions: 0.0)
ERROR: No matching distribution found for kaolin==0.13.0
I have also tried installing Kaolin using other versions of PyTorch, but have not had any success. Here is the output of my torch and nvcc commands:

ruby
Copy code
$ python -c "import torch; print(torch.__version__)"
2.0.0+cu117

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
Please let me know if there are any additional steps I should take to install Kaolin on my system, or if there is any additional information I can provide to assist with troubleshooting. Thank you!

**Comment by GraystoneZ** [comment]
I think this will help you. @dellshan 

https://kaolin.readthedocs.io/en/latest/notes/installation.html

Here you can find a table about supported version of CUDA and torch. Also it says they support python <= 3.9 in requirements section.

**Comment by shumash** [comment]
Please post a new bug if running into issues [installing from latest wheels](https://kaolin.readthedocs.io/en/latest/notes/installation.html) within our python/torch/cuda support range. Thanks!
