### ISSUE TITLE
Asking support for pytorch 2.0.1.

### ISSUE THREAD

**Issue by sparse-mvs-2** [NVIDIAGameWorks/kaolin#730]
I'm using kaolin on other project which requires pytorch 2.0.1, which will get: No module named 'torch._six'.

**Comment by zhangai6666** [comment]
Hi @sparse-mvs-2, Any luck since then? I'm about to start getting kaolin work with pytorch 2.0.1

**Comment by Caenorst** [comment]
Hi @sparse-mvs-2 , @zhangai6666 I'm currently addressing this, expect an update very soon, v0.14.0 will be compatible with 2.0.1

**Comment by samiede** [comment]
Hey! Can I jump on this and ask for pytorch 2.1.0 support, too? 😇

**Comment by shumash** [comment]
Done. See support matrix [here](https://kaolin.readthedocs.io/en/latest/notes/installation.html).
