### ISSUE TITLE
How to get 2D keypoints from the 3D bounding box generated from Kaolin and reversing it back? 

### ISSUE THREAD

**Issue by mustafamirrAR** [NVIDIAGameWorks/kaolin#743]
I am using Kaolin for synthetic dataset generation and annotating 3D bounding box. I am using standard equations to convert from 3D to 2D and from 2D to 3D but not able to get it properly. Any more equations involved? What is the role of transform, asset transforms in json file?

**Comment by Caenorst** [comment]
Hi @mustafamirrAR , assuming you are talking about the metadata output by the OV extension. assets transforms are the transforms applied to the mesh (things like transform the mesh to scene, normalization, axis change). Can you provide more details about how things are wrong?

**Comment by mustafamirrAR** [comment]
I am transforming the 3D bounding box coordinates generated by the kaolin into 2D coordinates using standard equations . Again I am reconstructing back those 2D coordinates to 3D bounding box coordinates using standard equations. But I am not getting the box at the proper place. I want to know the equations involved in this transform according to your Kaolin application. Any elaborated documentation available of this kaolin synthetic data generation and its json file? 
If possible can we have a google meet to discuss the problem?





<http://www.mirrar.com>

Mustafa Sameer, Ph.D.

AI/ ML Researcher

***@***.***

+91 9852500922 <+919852500922>

Bengaluru, India | New Jersey, US

mirrar.com <http://www.mirrar.com>

**Comment by Caenorst** [comment]
Closing as the Omniverse App is deprecated
