### ISSUE TITLE
ImportError: cannot import name 'TriangleMesh' from 'kaolin.rep'

### ISSUE THREAD

**Issue by ERICXUCHI** [NVIDIAGameWorks/kaolin#753]
Hi guys, does anyone encounter this error:
```
ImportError: cannot import name 'TriangleMesh' from 'kaolin.rep' (/home/testuser/miniconda3/envs/3dmesh/lib/python3.8/site-packages/kaolin/rep/__init__.py)
```
I just followed strictly with the instructions and my environments are as below:
linux
python 3.8
torch 1.13.0
cuda 11.7
kaolin 0.13

Moreover, I could not find 'TriangleMesh' in 'kaolin/rep'.

**Comment by Caenorst** [comment]
Hi @ERICXUCHI , there is no `TriangleMesh` in Kaolin 0.13, I assume you want to use 0.1 which is a very old version of Kaolin?

**Comment by yangqinhui0423** [comment]
> Hi guys, does anyone encounter this error:
> 
> ```
> ImportError: cannot import name 'TriangleMesh' from 'kaolin.rep' (/home/testuser/miniconda3/envs/3dmesh/lib/python3.8/site-packages/kaolin/rep/__init__.py)
> ```
> 
> I just followed strictly with the instructions and my environments are as below: linux python 3.8 torch 1.13.0 cuda 11.7 kaolin 0.13
> 
> Moreover, I could not find 'TriangleMesh' in 'kaolin/rep'.

Hey , I wonder how you solved the problem. I tried to use the Kaolin 0.1 but it remind me that:
ImportError: This is the kaolin placeholder wheel from https://pypi.org/project/kaolin/. Please follow https://kaolin.readthedocs.io/en/latest/notes/installation.html for installation.

**Comment by Caenorst** [comment]
Hi @yangqinhui0423 Unfortunately we only made wheels for v0.11.0 and above, for what usage are you trying to use v0.1?

**Comment by yangqinhui0423** [comment]
> Hi @yangqinhui0423 Unfortunately we only made wheels for v0.11.0 and above, for what usage are you trying to use v0.1?

In the code as follows(from the work IPNet——https://github.com/bharat-b7/IPNet):
![image](https://github.com/user-attachments/assets/be5185f0-6256-402f-ac91-d4d5ff6a91e1)
kaolin.rep.Trianglemesh

**Comment by shumash** [comment]
This is the old version of the library no longer supported. Closing bug. 

Note that for new code, we now support a [SurfaceMesh](https://kaolin.readthedocs.io/en/latest/modules/kaolin.rep.surface_mesh.html#kaolin-rep-surfacemesh) class. Here's a [video tutorial](https://www.youtube.com/watch?v=sRAgqNhsfJA&t=5s&ab_channel=NVIDIADeveloper) on how to use it, and [visualization tutorial](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/easy_mesh_render.ipynb).
