### ISSUE TITLE
Running the test code did not yield results

### ISSUE THREAD

**Issue by muses0229** [NVIDIAGameWorks/kaolin#755]

**Comment by yejr0229** [comment]
kaolin version:0.10.0 
torch1.11.0+cu11.5

**Comment by yejr0229** [comment]
gpu:1080Ti

**Comment by yejr0229** [comment]
when I change to kaolin version 0.11.0,error is Check failed: error == cudaSuccess (209 vs. 0)  no kernel image is available

**Comment by Caenorst** [comment]
Hi @yejr0229 , please test the newer easy_render API.

Closing
