### ISSUE TITLE
Building documentation error

### ISSUE THREAD

**Issue by felixboevr** [NVIDIAGameWorks/kaolin#76]
When trying to build the documentation by
$ cd docs
$ sphinx-build . _build

I get 

> Exception` occurred: File "/../../anaconda2/envs/kaolin/lib/python3.6/site-packages/Sphinx-2.2.2-py3.6.egg/sphinx/util/nodes.py", line 151, in apply_source_workaround for classifier in reversed(node.parent.traverse(nodes.classifier)): TypeError: '_traversal_list' object is not reversible

**Comment by Jean-Francois-Lafleche** [comment]
Thanks for reporting! I was able to repro as well. Issue is caused by docutils==0.16b0.dev. You can resolve by running  `pip install docutils==0.15.2`. Issued a PR to pin sphinx to 2.2.0 to avoid issue in the future.
