### ISSUE TITLE
ImportError: /home/j222/vid2avatar-main/kaolin/kaolin/_C.so: undefined symbol: _ZNK2at10TensorBase8data_ptrIdEEPT_v

### ISSUE THREAD

**Issue by 2601705041** [NVIDIAGameWorks/kaolin#768]
my cuda version is 11.1
pytorch use it:
pip install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html

ImportError: /home/j222/vid2avatar-main/kaolin/kaolin/_C.so: undefined symbol: _ZNK2at10TensorBase8data_ptrIdEEPT_v

**Comment by Caenorst** [comment]
Hi @2601705041, how did you install Kaolin?

**Comment by 2601705041** [comment]
through this:https://kaolin.readthedocs.io/en/v0.10.0/notes/installation.html

**Comment by Caenorst** [comment]
@2601705041 , please show command-line the installation instructions are showing multiple ways to install

**Comment by shumash** [comment]
Closing inactive bug.
