### ISSUE TITLE
Nvdiffrast not installed automatically?

### ISSUE THREAD

**Issue by odusseys** [NVIDIAGameWorks/kaolin#772]
I am running kaolin on Google Colab.

The installation instructions do not mention the need to install nvdiffrast as a requirement - but the examples use it, so I assumed it was included - is this not the case? If not perhaps the examples should be updated to reflect this. Otherwise not sure why nvdiffrast isn't found.

**Comment by Caenorst** [comment]
Hi @odusseys , We could add nvdiffrast as dependency, however I believe it will build it on the fly since nvdiffrast has no wheels

**Comment by odusseys** [comment]
I had to install it manually on colab at least but works fine when I do

**Comment by shumash** [comment]
To allow for maximal flexibility in environments, nvdiffrast is optional. It is up to the users of Kaolin to install it if they need extra functionality.
