### ISSUE TITLE
Cannot render a mesh which only contains vertices and faces. no uvmap.

### ISSUE THREAD

**Issue by kuwan2e** [NVIDIAGameWorks/kaolin#779]
Hi , I have an .obj file and I want to render it to images. But it seems that  in camera_and_rasterization.ipynb and dibr_tutorial.ipynb, we can only render a mesh with uvmap. How should I change the code? Thanks!

**Comment by Caenorst** [comment]
Hi @kuwan2e , if there is no UVmap what are using to represent the texture / color of the mesh?

**Comment by shumash** [comment]
Please try our new general shader [kaolin.render.easy_render.render_mesh](https://kaolin.readthedocs.io/en/latest/modules/kaolin.render.easy_render.mesh.html#kaolin.render.easy_render.mesh.render_mesh) (see [visualization tutorial here](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/easy_mesh_render.ipynb) or [easy script](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/render_mesh.py) here). If you run into issues, please file a bug.
