### ISSUE TITLE
Runtime with flexicubes

### ISSUE THREAD

**Issue by reynoldscem** [NVIDIAGameWorks/kaolin#781]
Hi, roughly how long does it take to reconstruct an object using flexicubes and nvdiffrec?

**Comment by shumash** [comment]
That depends on various factors. We are not able to provide detailed timings. 

You can reach out to flexicubes authors on [their github](https://github.com/nv-tlabs/FlexiCubes). The original authors have ported the Kaolin version of flexi-cubes and timings should be the same as in the paper.
