### ISSUE TITLE
Request for CPU-Only Wheels for Non-GPU Dependent Modules

### ISSUE THREAD

**Issue by prokolyvakis** [NVIDIAGameWorks/kaolin#782]
#### Summary:
I would like to bring attention to the need for CPU-only wheel distributions for parts of Kaolin that do not inherently require GPU support. While understanding that the core functionalities of Kaolin leverage GPU acceleration for efficiency, there are components, particularly related to I/O operations (e.g., USD file handling), that are not GPU-bound and could benefit from being executable on CPU-only environments.

#### Issue:
The [current version](https://pypi.org/project/kaolin/) available on PyPI (**0.1)** appears to be a placeholder and does not offer practical usability. This limitation poses a challenge in scenarios where only CPU-based execution is feasible or desired, such as running unit tests in CI/CD pipelines (e.g., GitHub Actions) where GPU resources may not be available or required. This functionality is really important for repos building upon kaolin that want to differentiate the code unittesting between CPU and GPU only.  

#### Use Case:
An immediate application of CPU-only modules is in the context of continuous integration testing. Being able to test parts of the codebase that interact with file systems, perform data preprocessing, or any other non-GPU intensive task, without the necessity for GPU resources, would greatly enhance the development workflow. This is particularly relevant for validating changes that affect the aforementioned aspects of the library, ensuring robustness and functionality without the overhead of GPU dependencies in testing environments.

#### Suggestion:
It would be highly beneficial for the development and user community if CPU-only wheels could be made available for those segments of Kaolin that do not necessitate GPU computation apart from the [already existing CUDA using wheels](https://nvidia-kaolin.s3.us-east-2.amazonaws.com/). This would not only facilitate broader testing strategies but also enable use cases where GPU resources are either unavailable or unnecessary.

Thank you for your great work! :)

**Comment by shash29-dev** [comment]
+1

**Comment by Caenorst** [comment]
Hi @prokolyvakis ! Thank you for raising this issue. I will create wheels for CPU, but It may take a little bit of time to set that up since I may need to create new CI scripts.

**Comment by prokolyvakis** [comment]
Thank you very much @Caenorst ! I am looking forward to it !

**Comment by Caenorst** [comment]
I've uploaded for cpu-only wheels for v0.16.0, enjoy!
