### ISSUE TITLE
Invitation to Your First Open Source Project Organization

### ISSUE THREAD

**Issue by SirBang** [NVIDIAGameWorks/kaolin#784]
Hello, I am a senior Game Developer.
I want to contribute to this open source.

**Comment by orperel** [comment]
Hi @SirBang , great to hear! :-)
We welcome external PRs, please see the contribution guidelines: https://github.com/NVIDIAGameWorks/kaolin/blob/master/CONTRIBUTING.md

**Comment by shumash** [comment]
Closing inactive bug.
