### ISSUE TITLE
Any suggestion about rendering transparent part?

### ISSUE THREAD

**Issue by XiongFenghhh** [NVIDIAGameWorks/kaolin#790]
Hello, I have a model with pbr mat which has transparent part ，but I don't know how to render it correctly. I got the basecolor of the transparent part instead of the color behind it. Is there a way to render it correctly?

**Comment by Caenorst** [comment]
@XiongFenghhh , If you are using nvdiffrast, you could use `nvdiffrast.torch.DepthPeeler`

**Comment by XiongFenghhh** [comment]
> @XiongFenghhh , If you are using nvdiffrast, you could use `nvdiffrast.torch.DepthPeeler`

Thank you for your suggestion, I got the desired render result based on the nvdiffrast document. However, according to the doc, 
 the hyperparameter "num_layers" need to be set. Is there a way to automatically set it？ or does it currently only support manual settings？

```python
with nvdiffrast.torch.DepthPeeler(glctx, pos, tri, resolution) as peeler:
  for i in range(num_layers):
    rast, rast_db = peeler.rasterize_next_layer()
    (process or store the results)
```

**Comment by XiongFenghhh** [comment]
> > @XiongFenghhh , If you are using nvdiffrast, you could use `nvdiffrast.torch.DepthPeeler`
> 
> Thank you for your suggestion, I got the desired render result based on the nvdiffrast document. However, according to the doc, the hyperparameter "num_layers" need to be set. Is there a way to automatically set it？ or does it currently only support manual settings？
> 
> ```python
> with nvdiffrast.torch.DepthPeeler(glctx, pos, tri, resolution) as peeler:
>   for i in range(num_layers):
>     rast, rast_db = peeler.rasterize_next_layer()
>     (process or store the results)
> ```

I set num_layers to a safe value.

**Comment by shumash** [comment]
Thanks for your question @XiongFenghhh . Closing the issue as we are not able to help with your custom rendering pipelines. 
Questions specific to nvdiffrast, should be addressed to [nvidiffrast github](https://github.com/NVlabs/nvdiffrast/issues?q=) issue board.
