### ISSUE TITLE
Python3.11 builds

### ISSUE THREAD

**Issue by jloveric** [NVIDIAGameWorks/kaolin#791]
Any plans to make a python3.11 builds?

**Comment by Caenorst** [comment]
Hi @jloveric ! Planning that for next release

**Comment by guillochon** [comment]
@Caenorst any ETA on this? is the USD package the reason they currently aren't available? Need any help? 😄

**Comment by Caenorst** [comment]
@guillochon v0.16.0 now have wheels support for 3.11, unfortunately usd-core is not supporting 3.12 yet, but I will update once it does.
