### ISSUE TITLE
How to render shadow on the ground?

### ISSUE THREAD

**Issue by XiongFenghhh** [NVIDIAGameWorks/kaolin#792]
Hello, I try to render glb file following this [tutorial](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/gltf_viz.ipynb).

However, I found that the shadow on the ground cannot be rendered. For example, the first pic is rendered by blender, the shadow on the ground can be seen. In the second pic rendered by nvdiffrast, the shadow on the cloth can be seen but the shadow on the ground disapears
![blend](https://github.com/NVIDIAGameWorks/kaolin/assets/12598348/181f96c6-98bd-4ec3-bea6-3664f5d9bb16)
![test_view3](https://github.com/NVIDIAGameWorks/kaolin/assets/12598348/1345fde4-d1b9-4191-8d18-551865ac2053)

**Comment by shumash** [comment]
The shadows are currently not supported, as our differentiable rendering pipeline is purely rasterization-based (so no tracing of light in the scene). There are various differentiable ray-tracing and shadow-mapping implementations out there, but we would not be able to suggest one.

If it's still useful without shadows, note that the `glb/gltf` rendering is now consistent with `usd` and `obj` types and is exposed as a function [kaolin.render.easy_render.render_mesh](https://kaolin.readthedocs.io/en/latest/modules/kaolin.render.easy_render.mesh.html#kaolin.render.easy_render.mesh.render_mesh). Please see [Easy Mesh Render Tutorial](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/easy_mesh_render.ipynb).
