### ISSUE TITLE
No module named 'dmtet_network'

### ISSUE THREAD

**Issue by ms0109p** [NVIDIAGameWorks/kaolin#795]
Where can I download the dmtet_network module when this error occurs?
![스크린샷 2024-05-08 213515](https://github.com/NVIDIAGameWorks/kaolin/assets/127375471/df9fffbf-afd0-4084-ace0-c4c6c8dcd373)

**Comment by shumash** [comment]
The `dmtet_network` module is under tutorial: [examples/tutorial/dmtet_network.py](https://github.com/NVIDIAGameWorks/kaolin/blob/master/examples/tutorial/dmtet_network.py)
