### ISSUE TITLE
  ERROR: Failed building wheel for kaolin

### ISSUE THREAD

**Issue by merterbak** [NVIDIAGameWorks/kaolin#798]
when I run the code !mamba env create -f /content/X-Mesh/xmesh.yml on colab I get this error.

xmesh.yml file below:
name: xmesh
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.3
  - matplotlib=3.5.2
  - jupyter=1.0.0
  - pip=21.1.2
  - pip:
    - git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
    - git+https://github.com/NVIDIAGameWorks/kaolin@a00029e5e093b5a7fe7d3a10bf695c0f01e3bd98

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: / By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.htmldone
Installing pip dependencies: | Ran pip subprocess with arguments:
['/usr/local/envs/xmesh/bin/python', '-m', 'pip', 'install', '-U', '-r', '/content/X-Mesh/condaenv.pzymv1fo.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1 (from -r /content/X-Mesh/condaenv.pzymv1fo.requirements.txt (line 1))
  Cloning https://github.com/openai/CLIP.git (to revision d50d76daa670286dd6cacf3bcd80b5e4823fc8e1) to /tmp/pip-req-build-f2mfql99
Collecting git+https://github.com/NVIDIAGameWorks/kaolin@a00029e5e093b5a7fe7d3a10bf695c0f01e3bd98 (from -r /content/X-Mesh/condaenv.pzymv1fo.requirements.txt (line 2))
  Cloning https://github.com/NVIDIAGameWorks/kaolin (to revision a00029e5e093b5a7fe7d3a10bf695c0f01e3bd98) to /tmp/pip-req-build-yeh7e6c3
Collecting ftfy
  Downloading ftfy-6.2.0-py3-none-any.whl (54 kB)
Collecting regex
  Downloading regex-2024.5.15-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (774 kB)
Collecting tqdm
  Downloading tqdm-4.66.4-py3-none-any.whl (78 kB)
Requirement already satisfied: torch in /usr/local/envs/xmesh/lib/python3.9/site-packages (from clip==1.0->-r /content/X-Mesh/condaenv.pzymv1fo.requirements.txt (line 1)) (1.12.1)
Requirement already satisfied: torchvision in /usr/local/envs/xmesh/lib/python3.9/site-packages (from clip==1.0->-r /content/X-Mesh/condaenv.pzymv1fo.requirements.txt (line 1)) (0.13.1)
Collecting scipy<=1.7.2,>=1.2.0
  Downloading scipy-1.7.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (39.8 MB)
Requirement already satisfied: Pillow>=8.0.0 in /usr/local/envs/xmesh/lib/python3.9/site-packages (from kaolin==0.12.0->-r /content/X-Mesh/condaenv.pzymv1fo.requirements.txt (line 2)) (8.4.0)
Collecting usd-core<22.8
  Downloading usd_core-22.5.post1-cp39-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (24.3 MB)
Collecting numpy<1.23.0,>=1.16.5
  Downloading numpy-1.22.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Requirement already satisfied: wcwidth<0.3.0,>=0.2.12 in /usr/local/envs/xmesh/lib/python3.9/site-packages (from ftfy->clip==1.0->-r /content/X-Mesh/condaenv.pzymv1fo.requirements.txt (line 1)) (0.2.13)
Requirement already satisfied: typing_extensions in /usr/local/envs/xmesh/lib/python3.9/site-packages (from torch->clip==1.0->-r /content/X-Mesh/condaenv.pzymv1fo.requirements.txt (line 1)) (4.11.0)
Requirement already satisfied: requests in /usr/local/envs/xmesh/lib/python3.9/site-packages (from torchvision->clip==1.0->-r /content/X-Mesh/condaenv.pzymv1fo.requirements.txt (line 1)) (2.31.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/envs/xmesh/lib/python3.9/site-packages (from requests->torchvision->clip==1.0->-r /content/X-Mesh/condaenv.pzymv1fo.requirements.txt (line 1)) (2.2.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/envs/xmesh/lib/python3.9/site-packages (from requests->torchvision->clip==1.0->-r /content/X-Mesh/condaenv.pzymv1fo.requirements.txt (line 1)) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/envs/xmesh/lib/python3.9/site-packages (from requests->torchvision->clip==1.0->-r /content/X-Mesh/condaenv.pzymv1fo.requirements.txt (line 1)) (2024.2.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/envs/xmesh/lib/python3.9/site-packages (from requests->torchvision->clip==1.0->-r /content/X-Mesh/condaenv.pzymv1fo.requirements.txt (line 1)) (3.3.2)
Building wheels for collected packages: clip, kaolin
  Building wheel for clip (setup.py): started
  Building wheel for clip (setup.py): finished with status 'done'
  Created wheel for clip: filename=clip-1.0-py3-none-any.whl size=1369370 sha256=b4f7ba1b85185ff9acc1ef624ad63533a6b19715ce8d24809630a16e7237535c
  Stored in directory: /root/.cache/pip/wheels/ba/02/1a/4fbb37579f56a822bb4c55518ff214b926611fdfb3e4d6b532
  Building wheel for kaolin (setup.py): started
  Building wheel for kaolin (setup.py): finished with status 'error'
  Running setup.py clean for kaolin
Successfully built clip
Failed to build kaolin
Installing collected packages: numpy, usd-core, tqdm, scipy, regex, ftfy, kaolin, clip
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
    Running setup.py install for kaolin: started
    Running setup.py install for kaolin: finished with status 'error'

Pip subprocess error:
  Running command git clone -q https://github.com/openai/CLIP.git /tmp/pip-req-build-f2mfql99
  Running command git rev-parse -q --verify 'sha^d50d76daa670286dd6cacf3bcd80b5e4823fc8e1'
  Running command git fetch -q https://github.com/openai/CLIP.git d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  Running command git checkout -q d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  Running command git clone -q https://github.com/NVIDIAGameWorks/kaolin /tmp/pip-req-build-yeh7e6c3
  Running command git rev-parse -q --verify 'sha^a00029e5e093b5a7fe7d3a10bf695c0f01e3bd98'
  Running command git fetch -q https://github.com/NVIDIAGameWorks/kaolin a00029e5e093b5a7fe7d3a10bf695c0f01e3bd98
  Running command git checkout -q a00029e5e093b5a7fe7d3a10bf695c0f01e3bd98
  Running command git submodule update --init --recursive -q
  ERROR: Failed building wheel for kaolin
ERROR: Command errored out with exit status 1: /usr/local/envs/xmesh/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-yeh7e6c3/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-yeh7e6c3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5s64qvqr/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/envs/xmesh/include/python3.9/kaolin Check the logs for full command output.failed

CondaEnvException: Pip failed

**Comment by Ghul-huan** [comment]
怎么解决的
