### ISSUE TITLE
Tests fail due to missing module "pxr"

### ISSUE THREAD

**Issue by mbahri** [NVIDIAGameWorks/kaolin#80]
Hi

I installed kaolin and can import the library, however, running `pytest tests/` fails due to the missing module `pxr`, which appears to be related to USD files.

I thought packman was supposed to install the dependencies for manipulating USD files. Should pxr be installed manually?

**Platform:**

- Ubuntu 18.04
- Python 3.7.5
- Pytorch 1.3.1
- CUDA 10.1.243 with CUDNN 7.6.3

**Comment by felixboevr** [comment]
see
https://github.com/NVIDIAGameWorks/kaolin/issues/35#issuecomment-557361561

**Comment by aluo-x** [comment]
Still encountering this error building from master on CentOS 7, Python 3.7.5, CUDA 10.1. Otherwise the tests seem to pass.

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and this issue is no longer current.

Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

**Comment by feboz** [comment]
Hi,
I'm still having this error while testing a 0.9.0 installation after command "pytest tests/python/", on Ubuntu 20.0 in a Python virtual environment (Python 3.8.6, pytest-5.4.2, py-1.10.0, pluggy-0.13.1). It stops in script test_usd.py, error : " ModuleNotFoundError: No module named 'pxr'".

**Comment by Caenorst** [comment]
Hi @feboz ,
[usd-core](https://pypi.org/project/usd-core/) (which is basically this `pxr` module) is only compatible with python 3.6 or 3.7. You should have a warning about usd-core not getting installed when python version is at 3.8 or above.

**Comment by MoyGcc** [comment]
> Hi @feboz ,
> [usd-core](https://pypi.org/project/usd-core/) (which is basically this `pxr` module) is only compatible with python 3.6 or 3.7. You should have a warning about usd-core not getting installed when python version is at 3.8 or above.

Hi @Caenorst,

thank you for the contribution of this great work and kind help! I would make a follow-up question. The latest version of usd-core (like 21.8) is now compatible with python3.8 however the usd-core 20.11 is unfortunately yet not. I can still notice the installation of the newer version of kaolin 0.9.1 still needs usd-core 20.11 as an optional dependency. Will kaolin also be compatible with a newer version of usd-core which supports python3.8?

**Comment by Caenorst** [comment]
Hi @MoyGcc ,

It's already the case! see: https://github.com/NVIDIAGameWorks/kaolin/pull/426 merged 10 days ago :)

PS: v0.9.1 is still a Draft, should be officially released soon!
