### ISSUE TITLE
Inquiry About Upcoming Release with `easy_render` Feature

### ISSUE THREAD

**Issue by prokolyvakis** [NVIDIAGameWorks/kaolin#801]
### What

I would like to ask if there are any plans to release a minor update or patch that includes the new `easy_render` feature along with the relevant wheels? This feature, as described in the [documentation](https://kaolin.readthedocs.io/en/latest/modules/kaolin.render.easy_render.common.html), would be a valuable addition even before a major release.

I would greatly appreciate it if you could provide any information regarding this.

Thank you very much for your outstanding work & contributions!

**Comment by shumash** [comment]
Thanks for your interest! We are planning a major release really soon. Please subscribe to the repo to get updates.
