### ISSUE TITLE
Python 3.11 on Windows Builds

### ISSUE THREAD

**Issue by calebbuffa** [NVIDIAGameWorks/kaolin#816]
Great to see 0.16 was released! However I noticed the only wheels with Python 3.11 support are for linux. Are there any plans to support windows?

**Comment by Caenorst** [comment]
Hi @calebbuffa ! Yes, it's on the way, the CD cluster is a bit busy right now but hopefully everything should be posted today :)

**Comment by calebbuffa** [comment]
Fantastic! Thank you!

**Comment by calebbuffa** [comment]
I don't mean to bother! Reopening because I noticed the Windows builds still aren't up. I'm sure you all are busy, just wanted to see if there was an ETA @Caenorst

**Comment by Caenorst** [comment]
No problem, CI is a bit capricious, is there a specific pytorch version you are interested into? I can prioritize that for you.

Please keep the issue open I will close it once all the wheels are up.

**Comment by calebbuffa** [comment]
> No problem, CI is a bit capricious

Totally understand

> is there a specific pytorch version you are interested into? I can prioritize that for you.

2.0.1 would be great! thank you!

> Please keep the issue open I will close it once all the wheels are up.

will do!

**Comment by Caenorst** [comment]
Uploaded wheels for 2.0.0 and 2.0.1!

**Comment by calebbuffa** [comment]
You are a life saver, thank you!

**Comment by Caenorst** [comment]
All the wheels for windows have now been uploaded, sorry for the delay!
