### ISSUE TITLE
memory issue when normalize flag set to False for kalin.conversions.trianglemesh_to_voxelgrid

### ISSUE THREAD

**Issue by marlinilram** [NVIDIAGameWorks/kaolin#82]
In conversions.trianglemesh_to_voxelgrid, `smallest_side = (1. / resolution)**2` assumes a normalized mesh regardless of parameter `normalize`. 

If `normalize = True`, it should be `smallest_side = ((verts_max - verts_min) / resolution)**2`  .
Otherwise it easily eats up all memory.

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

We changed the interface of `trianglemesh_to_voxelgrid` now you can specify your own scale and origin (and whatever is between 0 and 1 will be voxelized)

Closing the bug as it is no longer relevant to this repo.
