### ISSUE TITLE
How to use the Kaolin library to load 3D medical images as 2D slices?

### ISSUE THREAD

**Issue by samanehAb** [NVIDIAGameWorks/kaolin#84]
Hi,

I was wondering if there is any support for loading the 3D medical images as 2D slices using the pytorch dataloader. I couldn't find any instructions about it here.

Bests,
Samaneh

**Comment by Caenorst** [comment]
Hi, @samanehAb , thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

What format of 3D medical images are you using? Depending on the format it may be as easy as indexing a tensor.

**Comment by shumash** [comment]
Closing for lack of response. Please file a new bug if there is a specific feature request.
