### ISSUE TITLE
Transforming point clouds of an object captured from one angle to other

### ISSUE THREAD

**Issue by ShettyHarapanahalli** [NVIDIAGameWorks/kaolin#85]
Can we transform point clouds of an object captured from one angle to other:

I want to capture the point cloud data of an object and transform it into another angle like I want to capture an object from low angle convert to bottom angle. can w edo this with Kaolin ? 
![views](https://user-images.githubusercontent.com/42834966/70531646-3a229c80-1b4d-11ea-80bb-38d776441d76.jpg)

**Comment by saphtea** [comment]
try it!

**Comment by Caenorst** [comment]
Hi, @ShettyHarapanahalli , thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

By "converting" do you mean
1) generating a new view at angle B **only** from a view at angle A? That might be doable with some models that would generate a 3d point cloud from a single view then render the point cloud from a new model, but you would have to design the solution.

2) From the 3d point cloud with coordinates system based on camera A => coordinate system based on camera B, that should be super easy, you must know the coordinate of the camera B in the system A and generate your camera matrices using [kaolin.render.camera.generate_rotate_translate_matrices](https://github.com/NVIDIAGameWorks/kaolin/blob/master/kaolin/render/camera.py#L39) and apply them with [kaolin.render.camera.rotate_translate_points](https://github.com/NVIDIAGameWorks/kaolin/blob/master/kaolin/render/camera.py#L21).

Closing this, feel free to reopen if you have further questions :)
