### ISSUE TITLE
Plan for future support?

### ISSUE THREAD

**Issue by lvzhaoyang** [NVIDIAGameWorks/kaolin#9]
Hi, 

Thanks for the great efforts that merging all the great work together. 

Will it be an ongoing efforts to keep merging more state-of-the-art work with open sourced codebase, e.g. DeepSDF(https://github.com/facebookresearch/DeepSDF), occupancy flow (https://github.com/autonomousvision/occupancy_flow) ? 

If there is a plan, it will be extremely helpful to also share in the readme how it will evolve so that the community can learn more or help.

**Comment by krrish94** [comment]
Yes, that's the plan :)

We are charting a contributions policy and a roadmap, and will share it publicly once it's ready.

**Comment by lvzhaoyang** [comment]
Great! Looking forward to it.
