### ISSUE TITLE
NVCC Fatal: Could not set up the environment for Microsoft Visual Studio

### ISSUE THREAD

**Issue by saphtea** [NVIDIAGameWorks/kaolin#91]
OS: Windows 10
Python: 3.7.4
virtualenv: anaconda
Pytorch:1.3.1
Cuda: 10.2

![image](https://user-images.githubusercontent.com/272940/70684141-f2d60200-1c59-11ea-99f1-ea3d7d9e767f.png)
Hey! I keep running into an issue with compilation I'm not sure quite what's going on even after a bit of research. Cuda's in my path, pytorch is installed, if y'all have any ideas I'd be appreciative! Thank you!

**Comment by VictorZuanazzi** [comment]
I had a similar issue, I manage to install it with python 3.6

**Comment by maleficca** [comment]
Have the same problem. Tried to install it with Cuda 10.1, but to no success. If someone would have any kind of idea what's causing this problem it'd be greatly appreciated!

**Comment by hjoonpark** [comment]
Same problem here.. still not resolved.
