### ISSUE TITLE
furthest_point_sampling_cuda breaks in nvidia v100

### ISSUE THREAD

**Issue by VictorZuanazzi** [NVIDIAGameWorks/kaolin#94]
Hello,

I have found the library quite unstable when it comes to GPU compatibility.

Particularly the function in  kaolin/cuda/furthest_point_sampling_cuda.cu does not run on nvidias v100 nor on Geforce GTX TITAN X.

I get the following error message:
```
CUDA kernel failed : no kernel image is available for execution on the device
void furthest_point_sampling_kernel_launcher(int, int, int, const float*, float*, int*) at L:253 in kaolin/cuda/furthest_point_sampling_cuda.cu
```

Anyone with a similar problem? Any ideas on how to solve it? 

I have tried re-installing the environment (including kaolin) from scratch, it did not work.

**Comment by preddy5** [comment]
Hey @VictorZuanazzi did you manage to find a solution for this problem? I have been encountering the same issue.

**Comment by VictorZuanazzi** [comment]
@preddy5 What worked for me was the following:
I re-installed the environment from scratch;
Then I re-cloned kaolin and installed it using the GPU I wanted to use it for experiments;
It works on that GPU type, but does not work on the others

**Comment by preddy5** [comment]
Thank you for the reply @VictorZuanazzi 
I managed to get it to work. The problem in my case was a version mismatch between the anaconda cuda environment and cuda environment(nvcc) used to compile the library.

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates.

Closing the bug as it is no longer relevant to this repo.
